---
sidebar: sidebar 
permalink: concept-overview.html 
keywords: overview, concepts, features, use case, cloud manager 
summary: BlueXPは、ITエキスパートとクラウドアーキテクトが、ネットアップのクラウドソリューションを使用してハイブリッドマルチクラウドインフラを一元管理できるようにします。 
---
= BlueXPの詳細をご覧ください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


BlueXP（旧Cloud Manager）を使用すると、ITエキスパートとクラウドアーキテクトは、ネットアップのクラウドソリューションを使用してハイブリッドマルチクラウドインフラを一元管理できます。



== の機能

BlueXPは、エンタープライズクラスのSaaSベースの管理プラットフォームであり、場所を問わずデータを管理できます。

* をセットアップして使用します https://cloud.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] 複数のクラウドにわたって効率的なマルチプロトコルデータ管理を実現します。
* ファイルストレージサービスをセットアップして使用
+
** https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files の特長"^]
** https://cloud.netapp.com/fsx-for-ontap["ONTAP 対応の Amazon FSX"^]
** https://cloud.netapp.com/cloud-volumes-service-for-aws["Cloud Volumes Service for AWS"^]
** https://cloud.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service for Google Cloud"^]


* ボリュームの作成、クラウドへのバックアップ、ハイブリッドクラウド間でのデータのレプリケート、クラウドへのコールドデータの階層化を行うことで、オンプレミスの ONTAP クラスタを検出して管理できます。
* 次のような統合 クラウド サービス を有効にします。
+
** https://cloud.netapp.com/cloud-compliance["クラウドデータの意味"^]
** https://cloud.netapp.com/cloud-insights["Cloud Insights の機能です"^]
** https://cloud.netapp.com/cloud-backup-service["クラウドバックアップ"^]




https://cloud.netapp.com/cloud-manager["BlueXPの詳細をご覧ください"^]。



== サポートされているオブジェクトストレージプロバイダ

BlueXPを使用すると、クラウドストレージを管理し、Amazon Web Services、Microsoft Azure、Google Cloudで クラウド サービス を使用できます。



== コスト

BlueXPソフトウェアはネットアップから無償で提供されています。

ほとんどのタスクでは、クラウドネットワークにConnectorを導入するように求められます。これにより、コンピューティングインスタンスと関連ストレージのクラウドプロバイダから料金が発生します。Connector ソフトウェアをオンプレミスで実行することもできます。

link:reference-connector-default-config.html["コネクタのデフォルト設定について説明します"]。



== BlueXPの仕組み

BlueXPには'BlueXP Webサイトに統合さCloud Volumes ONTAP れたSaaSベースのインタフェースと'BlueXPやその他の クラウド サービス を管理するコネクタが含まれています



=== ソフトウェアサービス

BlueXPには、からアクセスできます https://cloudmanager.netapp.com["SaaS ベースのユーザインターフェイス"^] API を使用できます。この SaaS エクスペリエンスを利用すると、リリース時に最新機能に自動的にアクセスしたり、ネットアップのアカウントとコネクタを簡単に切り替えることができます。


TIP: アウトバウンドのインターネットアクセスが利用できない環境で操作している場合は、その環境にConnectorソフトウェアをインストールし、コネクタで使用できるローカルユーザインターフェイスにアクセスできます。 link:concept-connectors.html["コネクタの詳細については、こちらをご覧ください"]。



=== BlueXPのWebサイト

https://cloud.netapp.com["BlueXPのWebサイト"^] 一元的な場所でアクセスと管理を行うことができます https://www.netapp.com/us/products/cloud-services/use-cases-for-netapp-cloud-services.aspx["ネットアップのクラウドサービス"^]。一元管理されたユーザ認証を使用すると、同じクレデンシャルセットを使用してBlueXPやCloud Insights などの他の クラウド サービス にアクセスできます。



=== ネットアップアカウント

BlueXPに初めてログインすると、_NetAppアカウント_の作成を求めるメッセージが表示されます。このアカウントはマルチテナンシーを提供し、分離されたワークスペース内でユーザとリソースを整理することができます。



=== コネクタ

多くの場合、BlueXPアカウント管理者は、クラウドまたはオンプレミスネットワークに_コネクタ_を導入する必要があります。Connectorを使用すると、BlueXPはパブリッククラウド環境内のリソースとプロセスを管理できます。

link:concept-connectors.html["コネクタが必要になる状況とその方法については、こちらをご覧ください 仕事"]。



== SOC 2 Type 2 認定

独立認定された公認会計士企業およびサービス監査役は、BlueXP、Cloud Sync 、クラウド階層化、クラウドデータセンス、クラウドバックアップ（BlueXPプラットフォーム）について調査し、該当する信頼サービス基準に基づいてSOC 2 Type 2レポートを達成したことを確認しました。

https://www.netapp.com/company/trust-center/compliance/soc-2/["ネットアップの SOC 2 レポートをご覧ください"^]
