---
sidebar: sidebar 
permalink: concept-connectors.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: コネクタは、クラウドネットワークまたはオンプレミスネットワークで実行されるネットアップのソフトウェアです。データインフラを管理するためにBlueXPが実行する必要のあるアクションを実行します。Connectorは、必要なアクションについてBlueXP SaaSレイヤを定期的にポーリングします。BlueXPの使用を開始するにはコネクタは必要ありませんが、コネクタを作成してBlueXPのすべての機能とサービスを有効にする必要があります。 
---
= コネクタについて説明します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A_connector_は、クラウドネットワークまたはオンプレミスネットワークで実行されるネットアップのソフトウェアです。データインフラを管理するためにBlueXPが実行する必要のあるアクションを実行します。コネクタは、実行する必要があるアクションについて、BlueXP  ソフトウェアサービス（SaaS）レイヤを常にポーリングします。BlueXPの使用を開始するにはコネクタは必要ありませんが、コネクタを作成してBlueXPのすべての機能とサービスを有効にする必要があります。



== コネクタなしでできること

BlueXPの使用を開始するためにコネクタは必要ありません。コネクタを作成することなく、BlueXPで複数の機能やサービスを使用できます。

コネクタなしでBlueXPの次の機能とサービスを使用できます。

* NetApp ONTAP 対応の Amazon FSX
+
一部のアクションでは、コネクタまたはBlueXP  ワークロードファクトリリンクが必要です。 https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html["コネクタまたはリンクが必要なアクションを確認する"^]

* 自動化カタログ
* Azure NetApp Files の特長
+
Azure NetApp Files のセットアップと管理にコネクタは必要ありませんが、BlueXP分類を使用してAzure NetApp Files データをスキャンする場合はコネクタが必要です。

* Cloud Volumes Service for Google Cloud
* コピーと同期
* デジタルアドバイザ
* デジタルウォレット（ライセンスのみ、サブスクリプションの監視にはコネクタが必要）
+
ほとんどすべての場合、コネクタなしでデジタルウォレットにライセンスを追加できます。

+
デジタルウォレットにライセンスを追加するためにコネクタが必要なのは、Cloud Volumes ONTAP _ノードベース_ライセンスのみです。この場合、 Cloud Volumes ONTAP システムにインストールされているライセンスのデータを使用するため、コネクタが必要です。

* オンプレミスのONTAP クラスタを直接検出
+
オンプレミスのONTAP クラスタを直接検出する場合はコネクタは必要ありませんが、BlueXPのその他の機能を利用する場合はコネクタが必要です。

+
https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["オンプレミスのONTAP クラスタの検出オプションと管理オプションの詳細については、こちらをご覧ください"^]

* ソフトウェアの更新
* 持続可能性
* ワークロードファクトリ




== コネクタが必要な場合

BlueXPを標準モードで使用する場合、BlueXPの次の機能やサービスにはコネクタが必要です。

* アラート
* ONTAP 管理機能用の Amazon FSX
* Amazon S3ストレージ
* Azure BLOBストレージ
* バックアップとリカバリ
* 分類
* Cloud Volumes ONTAP
* ディザスタリカバリ
* Eシリーズシステム
* 経済性^ 1^
* Google Cloud Storageバケット
* オンプレミスのONTAP クラスタとBlueXPデータサービスの統合
* 運用の耐障害性^1^
* ランサムウェアからの保護
* StorageGRID システム
* 階層化
* ボリュームキャッシュ


^1^コネクタなしでこれらのサービスにアクセスできますが、サービスからアクションを開始するにはコネクタが必要です。

BlueXPを制限モードまたはプライベートモードで使用するには、コネクタが必要です。



== コネクタは常に動作している必要があります

コネクタは、BlueXPサービスアーキテクチャの基本要素です。関連するコネクタが常に稼働し、アクセス可能であることを確認するのは、お客様の責任です。このサービスは、コネクタの可用性の短い停止を克服するように設計されていますが、インフラストラクチャの障害を修復するために必要なときにすぐに対処する必要があります。

このドキュメントにはEULAが適用されます。製品がドキュメントに従って操作されていない場合、製品の機能と操作、およびEULAに基づくお客様の権利に悪影響を及ぼす可能性があります。



=== Cloud Volumes ONTAP への影響

コネクタは、Cloud Volumes ONTAP の正常性と動作における重要なコンポーネントです。コネクタの電源がオフの場合は、Cloud Volumes ONTAP PAYGOシステムと容量ベースのBYOLシステムは、コネクタとの通信を14日以上切断したあとでシャットダウンします。これは、コネクタがシステムのライセンスを毎日更新するためです。

Cloud Volumes ONTAP システムにノードベースのBYOLライセンスがある場合は、ライセンスがCloud Volumes ONTAP システムにインストールされているため、14日後もシステムは実行されたままになります。



== サポートされている場所

コネクタは次の場所でサポートされています。

* Amazon Web Services の
* Microsoft Azure
+
Azureのコネクタは、管理するCloud Volumes ONTAPシステムと同じAzureリージョンに導入するか、Cloud Volumes ONTAPシステムの場合はに導入する必要があります https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Azure リージョンペア"^]。この要件により、Cloud Volumes ONTAPとそれに関連付けられたストレージアカウントの間でAzure Private Link接続が使用されるようになります。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["Cloud Volumes ONTAP での Azure プライベートリンクの使用方法をご確認ください"^]

* Google Cloud
+
BlueXPサービスをGoogle Cloudで使用する場合は、Google Cloudで実行されているコネクタを使用する必要があります。

* オンプレミス




== クラウドプロバイダとの通信

このコネクタは、AWS、Azure、Google Cloudへのすべての通信にTLS 1.2を使用します。



== 制限モードとプライベートモード

BlueXPを制限モードまたはプライベートモードで使用するには、まずBlueXPでコネクタをインストールし、コネクタでローカルに実行されているユーザインターフェイスにアクセスします。

link:concept-modes.html["BlueXPの導入モードについて説明します"]。



== コネクタを作成する方法

コネクタは、BlueXP  またはクラウドプロバイダのマーケットプレイスから直接作成することも、手動で独自のLinuxホストにインストールすることもできます。BlueXPを標準モード、制限モード、プライベートモードのいずれで使用しているかによって、作業を開始する方法が異なります。

* link:concept-modes.html["BlueXPの導入モードについて説明します"]
* link:task-quick-start-standard-mode.html["BlueXPを標準モードで開始する"]
* link:task-quick-start-restricted-mode.html["制限モードでのBlueXPの使用を開始する"]
* link:task-quick-start-private-mode.html["BlueXPのプライベートモードで開始する"]




== 権限

BlueXPからコネクタを直接作成するには特定の権限が必要です。コネクタインスタンス自体には別の権限セットが必要です。AWSまたはAzureでBlueXPから直接コネクタを作成する場合は、必要な権限でコネクタがBlueXPによって作成されます。

標準モードでBlueXPを使用している場合、権限の付与方法はコネクタの作成方法によって異なります。

アクセス許可の設定方法については、以下を参照してください。

* 標準モード
+
** link:concept-install-options-aws.html["AWSでのコネクタのインストールオプション"]
** link:concept-install-options-azure.html["Azureでのコネクタのインストールオプション"]
** link:concept-install-options-google.html["Google Cloudでのコネクタのインストールオプション"]
** link:task-install-connector-on-prem.html#step-4-set-up-cloud-permissions["オンプレミス環境のクラウド権限を設定"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["制限モードの権限を設定します"]
* link:task-prepare-private-mode.html#step-6-prepare-cloud-permissions["プライベートモードの権限を設定します"]


コネクタが日常的な操作に必要とする正確な権限を表示するには、次のページを参照してください。

* link:reference-permissions-aws.html["ConnectorでのAWS権限の使用方法について説明します"]
* link:reference-permissions-azure.html["ConnectorでのAzure権限の使用方法について説明します"]
* link:reference-permissions-gcp.html["ConnectorでのGoogle Cloud権限の使用方法について説明します"]


以降のリリースで新しい権限が追加された場合は、コネクタポリシーを更新する必要があります。新しい権限が必要な場合は、リリースノートに記載されます。



== コネクタのアップグレード

私たちは通常、コネクタソフトウェアを毎月更新して新機能を導入し、安定性を向上させています。BlueXP  プラットフォームのサービスと機能のほとんどはSaaSベースのソフトウェアで提供されますが、一部の機能はコネクタのバージョンに依存します。Cloud Volumes ONTAP 管理、オンプレミスの ONTAP クラスタ管理、設定、ヘルプが含まれます。

標準モードまたは制限モードでBlueXPを使用すると、ソフトウェアの更新を取得するためにアウトバウンドのインターネットアクセスが確立されていれば、コネクタは自動的にソフトウェアを最新バージョンに更新します。BlueXPをプライベートモードで使用している場合は、コネクタを手動でアップグレードする必要があります。

link:task-upgrade-connector.html["プライベートモードを使用しているときにコネクタソフトウェアを手動でアップグレードする方法について説明します。"]です。



== オペレーティングシステムとVMのメンテナンス

コネクタホストでのオペレーティングシステムの保守は、お客様の責任で行ってください。たとえば、ユーザー(顧客)は、オペレーティングシステムの配布に関する会社の標準手順に従って、コネクタホスト上のオペレーティングシステムにセキュリティ更新プログラムを適用する必要があります。

マイナーなセキュリティ更新プログラムを適用する場合は、コネクタホスト上のサービスを停止する必要はありません。

コネクタVMを停止してから起動する必要がある場合は、クラウドプロバイダのコンソールから、またはオンプレミス管理の標準手順を使用して起動する必要があります。

<<コネクタは常に動作している必要があります,コネクタは常に動作している必要があることに注意してください>>。



== 複数の作業環境とコネクタ

コネクタは、BlueXPで複数の作業環境を管理できます。1 つのコネクタで管理できる作業環境の最大数は、環境によって異なります。管理対象は、作業環境の種類、ボリュームの数、管理対象の容量、ユーザの数によって異なります。

大規模な導入の場合は、ネットアップの担当者にご相談のうえ、環境のサイジングを行ってください。途中で問題が発生した場合は、製品内のチャットでお問い合わせください。

コネクタが 1 つしか必要ない場合もありますが、 2 つ以上のコネクタが必要な場合もあります。

次にいくつかの例を示します。

* マルチクラウド環境（AWSやAzureなど）で、コネクタの1つをAWSに、もう1つをAzureに配置したいと考えています。各で、それらの環境で実行される Cloud Volumes ONTAP システムを管理します。
* サービスプロバイダは、1つのBlueXP  組織を使用して顧客にサービスを提供し、別の組織を使用してビジネスユニットの1つにディザスタリカバリを提供することができます。各組織には個別のコネクタがあります。

