---
sidebar: sidebar 
permalink: concept-overview.html 
keywords: overview, concepts, features, use case, cloud manager, bluexp, how bluexp works, supported cloud providers, cloud providers, hyperscalers 
summary: NetApp BlueXPは、オンプレミス環境とクラウド環境にわたってデータの構築、保護、ガバナンスを支援する単一のコントロールプレーンです。BlueXPのSaaSプラットフォームは、ストレージとデータサービスで構成され、ストレージ管理、データモビリティ、データ保護、データ分析と制御を実現します。管理機能は、WebベースのコンソールとAPIを介して提供されます。 
---
= BlueXPの詳細をご覧ください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXPは、オンプレミス環境とクラウド環境にわたってデータの構築、保護、ガバナンスを支援する単一のコントロールプレーンです。BlueXPのSaaSプラットフォームは、ストレージとデータサービスで構成され、ストレージ管理、データモビリティ、データ保護、データ分析と制御を実現します。管理機能は、WebベースのコンソールとAPIを介して提供されます。



== 機能

BlueXPプラットフォームは、データ管理において、ストレージ、モビリティ、保護、分析と制御という4つの主要な柱を提供します。

ストレージ:: AWS、Azure、Google Cloud、オンプレミスのいずれであっても、ストレージを検出、導入、管理できます。
+
--
* をセットアップして使用します https://bluexp.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] 複数のクラウドにわたって効率的なマルチプロトコルデータ管理を実現します。
* クラウドファイルストレージサービスをセットアップして使用
+
** https://bluexp.netapp.com/azure-netapp-files["Azure NetApp Files の特長"^]
** https://bluexp.netapp.com/fsx-for-ontap["ONTAP 対応の Amazon FSX"^]
** https://bluexp.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service for Google Cloud"^]


* 検出と管理 https://bluexp.netapp.com/netapp-on-premises["オンプレミスストレージ"^]：
+
** Eシリーズシステム
** ONTAP クラスタ
** StorageGRID システム


* オーケストレーションと保護 https://bluexp.netapp.com/solutions/kubernetes["Kubernetesの永続的データ"^]


--
モビリティ:: データを同期、コピー、階層化、キャッシュすることで、必要な場所にデータを移動できます。
+
--
* https://bluexp.netapp.com/cloud-sync-service["コピーと同期"^]
* https://bluexp.netapp.com/global-file-cache["エッジキャッシュ"^]
* https://bluexp.netapp.com/cloud-tiering["階層化"^]


--
保護:: 自動化された保護メカニズムを使用して、データ損失、計画外停止、ランサムウェアなどのサイバー脅威からデータを保護します。
+
--
* https://bluexp.netapp.com/cloud-backup["バックアップとリカバリ"^]
* https://bluexp.netapp.com/replication["レプリケーション"^]


--
分析と管理:: ツールを使用して、データストレージとインフラを監視、マッピング、最適化できます。
+
--
* https://bluexp.netapp.com/netapp-cloud-data-sense["分類"^]
* https://bluexp.netapp.com/digital-advisor["デジタルアドバイザ"^]
* https://bluexp.netapp.com/ransomware-protection["ランサムウェアからの保護"^]


--


https://bluexp.netapp.com/["BlueXPを活用して組織を支援する方法をご紹介します"^]



== サポートされているクラウドプロバイダ

BlueXPを使用すると、クラウドストレージを管理し、Amazon Web Services、Microsoft Azure、Google Cloudで クラウド サービス を使用できます。



== コスト

BlueXPの価格は、使用する予定のサービスによって異なります。 https://bluexp.netapp.com/pricing["BlueXPの価格設定についてはこちらをご覧ください"^]



== BlueXPの仕組み

BlueXPには、SaaSレイヤを通じて提供されるWebベースのコンソール、マルチテナンシーを提供するアカウント、Cloud Volumes ONTAP やその他のクラウドサービスを管理するコネクタが含まれています。



=== ソフトウェアサービス

BlueXPには、からアクセスできます https://console.bluexp.netapp.com["Webベースのコンソール"^] API を使用できます。このSaaSエクスペリエンスでは、リリースされた最新機能に自動的にアクセスし、BlueXPアカウントとコネクタを簡単に切り替えることができます。



=== BlueXPアカウント

BlueXPに初めてログインすると、_BlueXPアカウント_を作成するように求められます。このアカウントはマルチテナンシーを提供し、分離されたワークスペース内でユーザとリソースを整理することができます。

link:concept-netapp-accounts.html["アカウントの詳細については、こちらをご覧ください"]。



=== コネクタ

BlueXPの使用を開始するにはコネクタは必要ありませんが、コネクタを作成してBlueXPのすべての機能とサービスを有効にする必要があります。コネクタにより、オンプレミス環境とクラウド環境にわたってリソースとプロセスを管理できます。Cloud Volumes ONTAP などのデータサービスを使用する必要があります。

link:concept-connectors.html["コネクタの詳細については、こちらをご覧ください"]。



=== 制限モードとプライベートモード

BlueXPは、セキュリティや接続が制限されている環境でもサポートされます。restricted mode_or_private mode__を使用して、アウトバウンド接続をBlueXP SaaSレイヤへの制限できます。

link:concept-modes.html["BlueXPの導入モードの詳細については、こちらをご覧ください"]。



== SOC 2 Type 2 認定

独立した公認会計士事務所およびサービス監査人がBlueXPを調査し、該当するトラストサービスの基準に基づいてSOC 2 Type 2レポートを達成したことを確認しました。

https://www.netapp.com/company/trust-center/compliance/soc-2/["ネットアップの SOC 2 レポートをご覧ください"^]
