---
sidebar: sidebar 
permalink: concept-overview.html 
keywords: overview, concepts, features, use case, cloud manager 
summary: BlueXPは、ITエキスパートとクラウドアーキテクトが、ネットアップのクラウドソリューションを使用してハイブリッドマルチクラウドインフラを一元管理できるようにします。 
---
= BlueXPの詳細をご覧ください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP（旧Cloud Manager）を使用すると、ITエキスパートとクラウドアーキテクトは、ネットアップのクラウドソリューションを使用してハイブリッドマルチクラウドインフラを一元管理できます。



== の機能

BlueXPは、エンタープライズクラスのSaaSベースの管理プラットフォームであり、場所を問わずデータを管理できます。

* をセットアップして使用します https://cloud.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] 複数のクラウドにわたって効率的なマルチプロトコルデータ管理を実現します。
* クラウドファイルストレージサービスをセットアップして使用
+
** https://bluexp.netapp.com/azure-netapp-files["Azure NetApp Files の特長"^]
** https://bluexp.netapp.com/fsx-for-ontap["ONTAP 対応の Amazon FSX"^]
** https://bluexp.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service for Google Cloud"^]


* 検出と管理 https://bluexp.netapp.com/netapp-on-premises["オンプレミスストレージ"^]
+
** Eシリーズシステム
** ONTAP クラスタ
** StorageGRID システム


* BlueXPのサービスを使用して'データの移動'データ保護'データの分析と管理を行うことができます
+
** https://bluexp.netapp.com/cloud-backup["クラウドバックアップ"^]
** https://bluexp.netapp.com/netapp-cloud-data-sense["クラウドデータの意味"^]
** https://bluexp.netapp.com/cloud-sync-service["Cloud Sync"^]
** https://bluexp.netapp.com/cloud-tiering["クラウド階層化"^]
** https://bluexp.netapp.com/digital-advisor["Digital Advisor"^]
** https://bluexp.netapp.com/global-file-cache["グローバルファイルキャッシュ"^]
** https://bluexp.netapp.com/k8s["Kubernetes"^]
** https://bluexp.netapp.com/ransomware-protection["ランサムウェアからの保護"^]
** https://bluexp.netapp.com/replication["レプリケーション"^]




https://cloud.netapp.com/cloud-manager["BlueXPの詳細をご覧ください"^]



== サポートされているクラウドプロバイダ

BlueXPを使用すると、クラウドストレージを管理し、Amazon Web Services、Microsoft Azure、Google Cloudで クラウド サービス を使用できます。



== コスト

BlueXPの価格は、使用する予定のサービスによって異なります。 https://bluexp.netapp.com/pricing["BlueXPの価格設定についてはこちらをご覧ください"^]。



== BlueXPの仕組み

BlueXPには'BlueXP Webサイトに統合さCloud Volumes ONTAP れたSaaSベースのインタフェースと'BlueXPやその他の クラウド サービス を管理するコネクタが含まれています



=== ソフトウェアサービス

BlueXPには、からアクセスできます https://console.bluexp.netapp.com["SaaS ベースのユーザインターフェイス"^] API を使用できます。この SaaS エクスペリエンスを利用すると、リリース時に最新機能に自動的にアクセスしたり、ネットアップのアカウントとコネクタを簡単に切り替えることができます。


TIP: アウトバウンドのインターネットアクセスが利用できない環境で操作している場合は、その環境にConnectorソフトウェアをインストールし、コネクタで使用できるローカルユーザインターフェイスにアクセスできます。 link:concept-connectors.html["コネクタの詳細については、こちらをご覧ください"]。



=== BlueXPのWebサイト

https://cloud.netapp.com["BlueXPのWebサイト"^] 一元的な場所でアクセスと管理を行うことができます https://www.netapp.com/us/products/cloud-services/use-cases-for-netapp-cloud-services.aspx["ネットアップのクラウドサービス"^]。一元管理されたユーザ認証を使用すると、同じクレデンシャルセットを使用してBlueXPやCloud Insights などの他の クラウド サービス にアクセスできます。



=== ネットアップアカウント

BlueXPに初めてログインすると、_NetAppアカウント_の作成を求めるメッセージが表示されます。このアカウントはマルチテナンシーを提供し、分離されたワークスペース内でユーザとリソースを整理することができます。



=== コネクタ

多くの場合、BlueXPアカウント管理者は、クラウドまたはオンプレミスネットワークに_コネクタ_を導入する必要があります。Connectorを使用すると、BlueXPはパブリッククラウド環境内のリソースとプロセスを管理できます。 link:concept-connectors.html["コネクタが必要になる状況とその方法については、こちらをご覧ください 仕事"]。



==== コネクタは常に動作している必要があります

コネクタは、NetApp BlueXPサービスアーキテクチャの基本要素です。関連するコネクタが常に稼働し、アクセス可能であることを確認するのは、お客様の責任です。このサービスは、コネクタの可用性の短い停止を克服するように設計されていますが、インフラストラクチャの障害を修復するために必要なときにすぐに対処する必要があります。

このドキュメントにはEULAが適用されます。製品がドキュメントに従って操作されていない場合、製品の機能と操作、およびEULAに基づくお客様の権利に悪影響を及ぼす可能性があります。



==== コネクタの可用性がCloud Volumes ONTAP に与える影響

コネクタは、Cloud Volumes ONTAP の正常性と動作における重要なコンポーネントです。コネクタの電源がオフの場合は、Cloud Volumes ONTAP PAYGOシステムと容量ベースのBYOLシステムは、コネクタとの通信を14日以上切断したあとでシャットダウンします。これは、コネクタがシステムのライセンスを毎日更新するためです。


NOTE: Cloud Volumes ONTAP システムにノードベースのBYOLライセンスがある場合は、ライセンスがCloud Volumes ONTAP システムにインストールされているため、14日後もシステムは実行されたままになります。



== SOC 2 Type 2 認定

独立認定された公認会計士企業およびサービス監査役は、BlueXP、Cloud Sync 、クラウド階層化、クラウドデータセンス、クラウドバックアップ（BlueXPプラットフォーム）について調査し、該当する信頼サービス基準に基づいてSOC 2 Type 2レポートを達成したことを確認しました。

https://www.netapp.com/company/trust-center/compliance/soc-2/["ネットアップの SOC 2 レポートをご覧ください"^]
