---
sidebar: sidebar 
permalink: concept-overview.html 
keywords: overview, concepts, features, use case, cloud manager, bluexp, how bluexp works, supported cloud providers, cloud providers, hyperscalers 
summary: NetApp BlueXPは、オンプレミス環境とクラウド環境にわたってデータの構築、保護、ガバナンスを支援する単一のコントロールプレーンです。BlueXP SaaSプラットフォームには、ストレージ管理、データモビリティ、データ保護、データ分析と制御を提供するサービスが含まれています。管理機能は、WebベースのコンソールとAPIを介して提供されます。 
---
= BlueXPの詳細をご覧ください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXPは、オンプレミス環境とクラウド環境にわたってデータの構築、保護、ガバナンスを支援する単一のコントロールプレーンです。BlueXP  ソフトウェアサービス（SaaS）プラットフォームには、ストレージ管理、データモビリティ、データ保護、データ分析と制御を提供するサービスが含まれます。管理機能は、WebベースのコンソールとAPIを介して提供されます。



== 機能

BlueXPプラットフォームは、データ管理において、ストレージ、モビリティ、保護、分析と制御という4つの主要な柱を提供します。

ストレージ:: AWS、Azure、Google Cloud、オンプレミスのいずれであっても、ストレージを検出、導入、管理できます。
+
--
* クラウドファイルストレージサービスをセットアップして使用
+
** https://bluexp.netapp.com/azure-netapp-files["Azure NetApp Files の特長"^]
** https://bluexp.netapp.com/fsx-for-ontap["NetApp ONTAP 対応の Amazon FSX"^]
** https://bluexp.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service for Google Cloud"^]


* をセットアップして使用します https://bluexp.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] 複数のクラウドにわたって効率的なマルチプロトコルデータ管理を実現します。
* 検出と管理 https://bluexp.netapp.com/netapp-on-premises["オンプレミスストレージ"^]：
+
** Eシリーズシステム
** ONTAP クラスタ
** StorageGRID システム




--
モビリティ:: データを同期、コピー、階層化することで、必要な場所にデータを移動できます。
+
--
* https://bluexp.netapp.com/cloud-sync-service["コピーと同期"^]
* https://bluexp.netapp.com/cloud-tiering["階層化"^]


--
保護:: 自動化された保護メカニズムを使用して、データ損失、計画外停止、ランサムウェアなどのサイバー脅威からデータを保護します。
+
--
* https://bluexp.netapp.com/cloud-backup["バックアップとリカバリ"^]
* https://bluexp.netapp.com/disaster-recovery["ディザスタリカバリ"^]
* https://bluexp.netapp.com/replication["レプリケーション"^]
* https://bluexp.netapp.com/ransomware-protection["ランサムウェアからの保護"^]


--
分析と管理:: ツールを使用して、データストレージとインフラを監視、マッピング、最適化できます。実用的な情報を取得して、ストレージの健全性、耐障害性、経済性を最適化します。
+
--
* https://bluexp.netapp.com/netapp-cloud-data-sense["分類"^]
* https://bluexp.netapp.com/digital-advisor["デジタルアドバイザ"^]
* https://bluexp.netapp.com/digital-advisor["経済効率"^]
* https://bluexp.netapp.com/digital-advisor["運用の耐障害性"^]


--


https://bluexp.netapp.com/["BlueXP  を使用してハイブリッドマルチクラウド環境全体にわたってデータを管理する方法の詳細をご確認ください。"^]



== サポートされているクラウドプロバイダ

BlueXPを使用すると、クラウドストレージを管理し、Amazon Web Services、Microsoft Azure、Google Cloudで クラウド サービス を使用できます。



== コスト

BlueXPの価格は、使用する予定のサービスによって異なります。 https://bluexp.netapp.com/pricing["BlueXPの価格設定についてはこちらをご覧ください"^]



== BlueXPの仕組み

BlueXP  には、SaaSレイヤを通じて提供されるWebベースのコンソール、リソースおよびアクセス管理システム、作業環境を管理してBlueXP  クラウドサービスを有効にするコネクタが含まれています。



=== ソフトウェアサービス

BlueXP  には、APIとAPIを使用してアクセスでき https://console.bluexp.netapp.com["Webベースのコンソール"^]ます。このSaaSエクスペリエンスにより、リリースされた最新の機能に自動的にアクセスし、BlueXP  の組織、プロジェクト、コネクタを簡単に切り替えることができます。



=== BlueXP  IDおよびアクセス管理（IAM）

BlueXP  IDおよびアクセス管理（IAM）は、リソースとアクセス権をきめ細かく管理できるリソースおよびアクセス管理モデルです。

* 最上位の_organization_を使用すると、さまざまな_projects_へのアクセスを管理できます。
* _Folders_関連するプロジェクトをグループ化できるようにします
* リソース管理を使用すると、リソースを1つ以上のフォルダまたはプロジェクトに関連付けることができます。
* アクセス管理を使用すると、組織階層のさまざまなレベルのメンバーにロールを割り当てることができます。


BlueXP  IAMは、標準モードでBlueXP  を使用する場合にサポートされます。BlueXP  を制限モードまたはプライベートモードで使用している場合は、BlueXP  アカウント_を使用してワークスペース、ユーザー、およびリソースを管理します。

* link:concept-identity-and-access-management.html["BlueXP  IAMの詳細"]
* link:concept-netapp-accounts.html["BlueXPアカウントの詳細をご確認ください"]




=== コネクタ

BlueXPの使用を開始するにはコネクタは必要ありませんが、コネクタを作成してBlueXPのすべての機能とサービスを有効にする必要があります。コネクタにより、オンプレミス環境とクラウド環境にわたってリソースとプロセスを管理できます。作業環境（Cloud Volumes ONTAPなど）を管理し、多数のBlueXP  サービスを使用するために必要です。

link:concept-connectors.html["コネクタの詳細については、こちらをご覧ください"]。



=== 展開モード

BlueXP  は、セキュリティと接続が制限されている環境でサポートされています。restricted mode_or_private mode__を使用して、アウトバウンド接続をBlueXP SaaSレイヤへの制限できます。

link:concept-modes.html["BlueXPの導入モードの詳細については、こちらをご覧ください"]。



== SOC 2 Type 2 認定

独立した公認会計士事務所およびサービス監査人がBlueXPを調査し、該当するトラストサービスの基準に基づいてSOC 2 Type 2レポートを達成したことを確認しました。

https://www.netapp.com/company/trust-center/compliance/soc-2/["ネットアップの SOC 2 レポートをご覧ください"^]
