---
sidebar: sidebar 
permalink: concept-data-services.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: コネクタは、クラウドネットワークまたはオンプレミスネットワークで実行されるネットアップのソフトウェアです。データインフラを管理するためにBlueXPが実行する必要のあるアクションを実行します。Connectorは、必要なアクションについてBlueXP SaaSレイヤを定期的にポーリングします。BlueXPの使用を開始するにはコネクタは必要ありませんが、コネクタを作成してBlueXPのすべての機能とサービスを有効にする必要があります。 
---
= BlueXP  サービスの詳細
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXPは、オンプレミス環境とクラウド環境にわたってデータの構築、保護、ガバナンスを支援する単一のコントロールプレーンです。

BlueXP  SaaSサービス（標準モード）を使用するか、制限されたクラウド環境でBlueXP  を実行するか（制限モード）、自社のオンプレミスデータセンターにインストールするか（プライベートモード）を選択できます。どのような環境でも、一元管理と追加データサービスを利用して、ストレージリソースの健全性と保護を維持できます。

選択するモードによって、使用可能なサービスと管理可能なストレージリソースが決まります。

作業を開始する前に、各モードでサポートされるさまざまなストレージリソースと使用可能なデータサービスを比較して、自社のニーズに適したストレージリソースを判断してください。



== データサービス

次の表に、各導入モードで使用できるデータサービス、サブスクリプションが必要かどうか、サポートアカウントが必要な場合を示します。

[NOTE]
====
*コネクタ*表のコネクタ列には、標準モード用のコネクタが必要な場合が示されています。BlueXP  を制限モードまたはプライベートモードで使用する場合は、常にコネクタが必要です。

====
[cols="24,19,19,19,19"]
|===
|  | サポートアカウントが必要 | コネクターが必要 | サブスクリプションが必要 | モードの可用性 


| アラート | はい。 | はい。 | いいえ | すべて 


| バックアップとリカバリ | はい。 | はい。 | はい。 | 標準、制限付き 


| 分類 | はい。 | いいえ | いいえ | すべて 


| コピーと同期 | いいえ | いいえ | はい。 |  


| デジタルアドバイザ | はい。 | いいえ | いいえ | すべて 


| デジタルウォレット | はい。 | いいえ * | いいえ | すべて 


| ディザスタリカバリ | いいえ | はい。 | はい。 | 標準、制限付き 


| 経済効率 | はい。 | はい。 | いいえ |  


| 運用の耐障害性 | はい。 | はい* | いいえ |  


| ランサムウェアからの保護 | いいえ | はい。 | いいえ | 標準 


| レプリケーション | いいえ | いいえ * | いいえ | 標準、制限付き 


| ソフトウェアの更新 | はい。 | いいえ | いいえ | すべて 


| サポートケース管理 | はい。 | いいえ | いいえ | すべて 


| 階層化 | いいえ | いいえ * | はい。 | 標準 


| ボリュームキャッシュ | いいえ | いいえ | いいえ | 標準 
|===


== NetAppストレージ

NetAppストレージリソースのほとんどをBlueXP  から直接管理できるため、同じアプリケーションからすべてのリソースを表示できます。

次の表に、各導入モードで管理できるストレージリソースと、コネクタまたはサブスクリプションが必要な場合の一覧を示します。

[NOTE]
====
*コネクタ*表のコネクタ列には、標準モード用のコネクタが必要な場合が示されています。BlueXP  を制限モードまたはプライベートモードで使用する場合は、常にコネクタが必要です。

====
[cols="24,19,19,19,19"]
|===
|  | サポートアカウントが必要 | コネクターが必要 | サブスクリプションが必要 | モードの可用性 


| NetApp ONTAP 対応の Amazon FSX | はい。 | いいえ^1^ | はい。 | 標準 


| Amazon S3ストレージ | はい。 | いいえ | はい。 | 標準 


| Azure BLOBストレージ | はい。 | いいえ | いいえ | 標準 


| Azure NetApp Files の特長 | いいえ | いいえ^2^ | はい。 | 標準、制限付き 


| Cloud Volumes ONTAP | はい。 | はい。 | はい。 | 標準、制限付き 


| Cloud Volumes Service for Google Cloud | いいえ | いいえ | はいはい | 標準 


| Eシリーズシステム | いいえ | はい。 | いいえ | 標準 


| Google クラウドストレージ | いいえ | はい。 | はいはい | 標準 


| オンプレミスの ONTAP クラスタ | はい。 | いいえ^3^ | いいえ | すべて 


| StorageGRID | はい。 | はい。 | いいえ | 標準、制限付き 
|===
^1^一部のアクションにはコネクタまたはBlueXP  ワークロードファクトリリンクが必要です。 https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html["コネクタまたはリンクが必要なアクションを確認する"^]

^2^ Azure NetApp Filesのセットアップと管理にコネクタは必要ありませんが、BlueXP  分類を使用してAzure NetApp Filesデータをスキャンする場合はコネクタが必要です。

^3^オンプレミスのONTAPクラスタを直接検出する場合はコネクタは必要ありませんが、BlueXP  の追加機能を利用する場合はコネクタが必要です。 https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["オンプレミスのONTAP クラスタの検出オプションと管理オプションの詳細については、こちらをご覧ください"^]
