---
settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: セットアップおよび管理に関するドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/whats-new.html"
    - title: 既知の制限
      url: "/reference-limitations.html"
    - title: サポートされるLinuxオペレーティングシステムに対する変更
      url: "/reference-connector-operating-system-changes.html"
  - title: はじめに
    entries:
    - title: 基本事項をご確認ください
      entries:
      - title: BlueXP
        url: "/concept-overview.html"
      - title: アカウント
        url: "/concept-netapp-accounts.html"
      - title: コネクタ
        url: "/concept-connectors.html"
      - title: 展開モード
        url: "/concept-modes.html"
    - title: 標準モードで開始します
      entries:
      - title: スタートアップワークフロー
        url: "/task-quick-start-standard-mode.html"
      - title: BlueXPコンソールを使用するためのネットワークの準備
        url: "/reference-networking-saas-console.html"
      - title: BlueXPにサインアップします
        url: "/task-sign-up-saas.html"
      - title: コネクタを作成します
        entries:
        - title: AWS
          entries:
          - title: コネクタのインストールオプション
            url: "/concept-install-options-aws.html"
          - title: BlueXPからコネクタを作成します
            url: "/task-install-connector-aws-bluexp.html"
          - title: マーケットプレイスからコネクターを作成する
            url: "/task-install-connector-aws-marketplace.html"
          - title: コネクタを手動で取り付ける
            url: "/task-install-connector-aws-manual.html"
        - title: Azure
          entries:
          - title: コネクタのインストールオプション
            url: "/concept-install-options-azure.html"
          - title: BlueXPからコネクタを作成します
            url: "/task-install-connector-azure-bluexp.html"
          - title: マーケットプレイスからコネクターを作成する
            url: "/task-install-connector-azure-marketplace.html"
          - title: コネクタを手動で取り付ける
            url: "/task-install-connector-azure-manual.html"
        - title: Google Cloud
          entries:
          - title: コネクタのインストールオプション
            url: "/concept-install-options-google.html"
          - title: BlueXPやgcloudからコネクタを作成
            url: "/task-install-connector-google-bluexp-gcloud.html"
          - title: コネクタを手動で取り付ける
            url: "/task-install-connector-google-manual.html"
        - title: オンプレミス
          url: "/task-install-connector-on-prem.html"
      - title: BlueXPにサブスクライブします
        url: "/task-subscribe-standard-mode.html"
      - title: 次は何ができるか
        url: "/reference-whats-next.html"
    - title: 制限モードの使用を開始します
      entries:
      - title: スタートアップワークフロー
        url: "/task-quick-start-restricted-mode.html"
      - title: 導入を準備
        url: "/task-prepare-restricted-mode.html"
      - title: コネクタを展開します
        url: "/task-install-restricted-mode.html"
      - title: BlueXPにサブスクライブします
        url: "/task-subscribe-restricted-mode.html"
      - title: 次は何ができるか
        url: "/reference-whats-next-restricted-mode.html"
    - title: プライベートモードで開始します
      entries:
      - title: スタートアップワークフロー
        url: "/task-quick-start-private-mode.html"
      - title: 導入を準備
        url: "/task-prepare-private-mode.html"
      - title: コネクタを展開します
        url: "/task-install-private-mode.html"
      - title: 次は何ができるか
        url: "/reference-whats-next-private-mode.html"
    - title: BlueXPにログインします
      url: "/task-logging-in.html"
  - title: BlueXPを管理します
    entries:
    - title: アイデンティティフェデレーション
      url: "/concept-federation.html"
    - title: BlueXPのアカウント
      entries:
      - title: BlueXPアカウントを管理します
        url: "/task-managing-netapp-accounts.html"
      - title: アカウントでの処理を監視します
        url: "/task-monitor-cm-operations.html"
      - title: BlueXPアカウントをもう1つ作成します
        url: "/task-create-account.html"
      - title: ユーザロール
        url: "/reference-user-roles.html"
    - title: コネクタ
      entries:
      - title: VMとOSの保守
        url: "/task-maintain-connectors.html"
      - title: セキュアなアクセスのためのHTTPS証明書をインストールします
        url: "/task-installing-https-cert.html"
      - title: プロキシサーバを使用するようにコネクタを設定します
        url: "/task-configuring-proxy.html"
      - title: EC2インスタンスでIMDSv2を使用する必要がある
        url: "/task-require-imdsv2.html"
      - title: プライベートモード使用時のコネクタのアップグレード
        url: "/task-upgrade-connector.html"
      - title: 複数のコネクタの操作
        url: "/task-manage-multiple-connectors.html"
      - title: コネクタのトラブルシューティング
        url: "/task-troubleshoot-connector.html"
      - title: コネクタをアンインストールして取り外します
        url: "/task-uninstall-connector.html"
      - title: デフォルト設定
        url: "/reference-connector-default-config.html"
    - title: クレデンシャルとサブスクリプション
      entries:
      - title: AWS
        entries:
        - title: クレデンシャルと権限の詳細
          url: "/concept-accounts-aws.html"
        - title: クレデンシャルとサブスクリプションを管理する
          url: "/task-adding-aws-accounts.html"
      - title: Azure
        entries:
        - title: クレデンシャルと権限の詳細
          url: "/concept-accounts-azure.html"
        - title: クレデンシャルとサブスクリプションを管理する
          url: "/task-adding-azure-accounts.html"
      - title: Google Cloud
        entries:
        - title: プロジェクトと権限の詳細
          url: "/concept-accounts-gcp.html"
        - title: クレデンシャルとサブスクリプションを管理する
          url: "/task-adding-gcp-accounts.html"
      - title: BlueXPアカウントに関連付けられているNSSクレデンシャルを管理します
        url: "/task-adding-nss-accounts.html"
      - title: BlueXPログインに関連付けられているクレデンシャルを管理します
        url: "/task-manage-user-credentials.html"
  - title: 参照
    entries:
    - title: 権限
      entries:
      - title: 権限の概要
        url: "/reference-permissions.html"
      - title: Connector の AWS 権限
        url: "/reference-permissions-aws.html"
      - title: Connector の Azure 権限
        url: "/reference-permissions-azure.html"
      - title: Connector の Google Cloud 権限
        url: "/reference-permissions-gcp.html"
    - title: ポート
      entries:
      - title: AWSでのコネクタセキュリティグループのルール
        url: "/reference-ports-aws.html"
      - title: Azureでのコネクタセキュリティグループのルール
        url: "/reference-ports-azure.html"
      - title: Google Cloudのコネクタファイアウォールルール
        url: "/reference-ports-gcp.html"
      - title: オンプレミスコネクタ用のポート
        url: "/reference-ports-on-prem.html"
  - title: 知識とサポート
    entries:
    - title: サポートに登録します
      url: "/task-support-registration.html"
    - title: ヘルプを表示します
      url: "/task-get-help.html"
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
