---
settings:
  name: BlueXP setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: BlueXP  のセットアップと管理
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/whats-new.html"
    - title: 既知の制限
      url: "/reference-limitations.html"
    - title: サポートされるLinuxオペレーティングシステムに対する変更
      url: "/reference-connector-operating-system-changes.html"
  - title: はじめに
    entries:
    - title: 基本事項をご確認ください
      entries:
      - title: BlueXP
        url: "/concept-overview.html"
      - title: コネクタ
        url: "/concept-connectors.html"
      - title: 展開モード
        url: "/concept-modes.html"
    - title: 標準モードで開始します
      entries:
      - title: スタートアップワークフロー
        url: "/task-quick-start-standard-mode.html"
      - title: BlueXP  コンソールのネットワークの準備
        url: "/reference-networking-saas-console.html"
      - title: BlueXPにサインアップします
        url: "/task-sign-up-saas.html"
      - title: コネクタを作成します
        entries:
        - title: AWS
          entries:
          - title: コネクタのインストールオプション
            url: "/concept-install-options-aws.html"
          - title: BlueXPからコネクタを作成します
            url: "/task-install-connector-aws-bluexp.html"
          - title: マーケットプレイスからコネクターを作成する
            url: "/task-install-connector-aws-marketplace.html"
          - title: コネクタを手動で取り付ける
            url: "/task-install-connector-aws-manual.html"
        - title: Azure
          entries:
          - title: コネクタのインストールオプション
            url: "/concept-install-options-azure.html"
          - title: BlueXPからコネクタを作成します
            url: "/task-install-connector-azure-bluexp.html"
          - title: マーケットプレイスからコネクターを作成する
            url: "/task-install-connector-azure-marketplace.html"
          - title: コネクタを手動で取り付ける
            url: "/task-install-connector-azure-manual.html"
        - title: Google Cloud
          entries:
          - title: コネクタのインストールオプション
            url: "/concept-install-options-google.html"
          - title: BlueXPやgcloudからコネクタを作成
            url: "/task-install-connector-google-bluexp-gcloud.html"
          - title: コネクタを手動で取り付ける
            url: "/task-install-connector-google-manual.html"
        - title: オンプレミス
          url: "/task-install-connector-on-prem.html"
      - title: NetAppインテリジェントサービスにご登録ください
        url: "/task-subscribe-standard-mode.html"
      - title: 次は何ができるか
        url: "/reference-whats-next.html"
    - title: 制限モードの使用を開始します
      entries:
      - title: スタートアップワークフロー
        url: "/task-quick-start-restricted-mode.html"
      - title: 導入を準備
        url: "/task-prepare-restricted-mode.html"
      - title: コネクタを展開します
        url: "/task-install-restricted-mode.html"
      - title: NetAppインテリジェントサービスにご登録ください
        url: "/task-subscribe-restricted-mode.html"
      - title: 次は何ができるか
        url: "/reference-whats-next-restricted-mode.html"
    - title: プライベートモードで開始します
      entries:
      - title: スタートアップワークフロー
        url: "/task-quick-start-private-mode.html"
      - title: 導入を準備
        url: "/task-prepare-private-mode.html"
      - title: コネクタを展開します
        url: "/task-install-private-mode.html"
      - title: 次は何ができるか
        url: "/reference-whats-next-private-mode.html"
  - title: BlueXPを使用する
    entries:
    - title: BlueXPにログインします
      url: "/task-logging-in.html"
    - title: BlueXPのユーザー設定を管理する
      url: "/task-user-settings.html"
  - title: BlueXPを管理します
    entries:
    - title: アイデンティティ管理とアクセス管理
      entries:
      - title: BlueXP  IAMの詳細
        url: "/concept-identity-and-access-management.html"
      - title: BlueXP  IAMの使用を開始する
        url: "/task-iam-get-started.html"
      - title: フォルダとプロジェクトを使用してリソースを整理する
        url: "/task-iam-manage-folders-projects.html"
      - title: メンバーとサービスアカウントを管理する
        url: "/task-iam-manage-members-permissions.html"
      - title: ロールを使用してリソースへのメンバーアクセスを制御する
        url: "/task-iam-manage-roles.html"
      - title: リソース階層の管理
        url: "/task-iam-manage-resources.html"
      - title: コネクタを他のフォルダおよびプロジェクトに関連付ける
        url: "/task-iam-associate-connectors.html"
      - title: 組織、プロジェクト、コネクタの切り替え
        url: "/task-iam-switch-organizations-projects.html"
      - title: 組織IDとプロジェクトID
        url: "/task-iam-rename-organization.html"
      - title: IAMアクティビティの監視または監査
        url: "/task-iam-audit-actions-timeline.html"
      - title: BlueXP  アクセスロール
        entries:
        - title: BlueXP  アクセスロールの詳細
          url: "/reference-iam-predefined-roles.html"
        - title: プラットフォームの役割
          url: "/reference-iam-platform-roles.html"
        - title: アプリケーションの役割
          entries:
          - title: Keystoneロール
            url: "/reference-iam-keystone-roles.html"
          - title: ストレージの役割
            url: "/reference-iam-storage-roles.html"
        - title: データサービスの役割
          entries:
          - title: バックアップとリカバリの役割
            url: "/reference-iam-backup-rec-roles.html"
          - title: 災害復旧の役割
            url: "/reference-iam-disaster-rec-roles.html"
          - title: ランサムウェア対策の役割
            url: "/reference-iam-ransomware-roles.html"
    - title: アイデンティティフェデレーション
      entries:
      - title: アイデンティティ連携について学ぶ
        url: "/concept-federation.html"
      - title: ドメイン検証
        entries:
        - title: ドメインを確認する
          url: "/task-federation-verify-domain.html"
      - title: フェデレーションを構成する
        entries:
        - title: Active Directory フェデレーション サービス (AD FS) プロバイダーとのフェデレーション
          url: "/task-federation-adfs.html"
        - title: Microsoft Entra ID プロバイダーとの連携
          url: "/task-federation-entra-id.html"
        - title: PingFederateとの連携
          url: "/task-federation-ping.html"
        - title: SAML IDプロバイダとの連携
          url: "/task-federation-saml.html"
      - title: フェデレーションの管理
        url: "/task-federation-manage.html"
      - title: 既存のフェデレーション接続をインポートする
        url: "/task-federation-import.html"
    - title: コネクタ
      entries:
      - title: VMとOSの保守
        url: "/task-maintain-connectors.html"
      - title: Webコンソールアクセス用のCA署名証明書のインストール
        url: "/task-installing-https-cert.html"
      - title: プロキシサーバを使用するようにコネクタを設定します
        url: "/task-configuring-proxy.html"
      - title: EC2インスタンスでIMDSv2を使用する必要がある
        url: "/task-require-imdsv2.html"
      - title: コネクタのアップグレードの管理
        url: "/task-upgrade-connector.html"
      - title: 複数のコネクタの操作
        url: "/task-manage-multiple-connectors.html"
      - title: コネクタのトラブルシューティング
        url: "/task-troubleshoot-connector.html"
      - title: コネクタをアンインストールして取り外します
        url: "/task-uninstall-connector.html"
      - title: デフォルト設定
        url: "/reference-connector-default-config.html"
      - title: BlueXP  でONTAP権限を適用する
        url: "/task-ontap-access-connector.html"
    - title: クレデンシャルとサブスクリプション
      entries:
      - title: AWS
        entries:
        - title: クレデンシャルと権限の詳細
          url: "/concept-accounts-aws.html"
        - title: クレデンシャルとサブスクリプションを管理する
          url: "/task-adding-aws-accounts.html"
      - title: Azure
        entries:
        - title: クレデンシャルと権限の詳細
          url: "/concept-accounts-azure.html"
        - title: クレデンシャルとサブスクリプションを管理する
          url: "/task-adding-azure-accounts.html"
      - title: Google Cloud
        entries:
        - title: プロジェクトと権限の詳細
          url: "/concept-accounts-gcp.html"
        - title: クレデンシャルとサブスクリプションを管理する
          url: "/task-adding-gcp-accounts.html"
      - title: BlueXP  の組織またはアカウントに関連付けられたNSSクレデンシャルの管理
        url: "/task-adding-nss-accounts.html"
      - title: BlueXPログインに関連付けられているクレデンシャルを管理します
        url: "/task-manage-user-credentials.html"
    - title: BlueXP  処理の監視
      url: "/task-monitor-cm-operations.html"
  - title: 参照
    entries:
    - title: コネクタメンテナンスコンソール
      entries:
      - title: コネクタメンテナンスオンソール
        url: "/reference-connector-maint-console.html"
    - title: 権限
      entries:
      - title: 権限の概要
        url: "/reference-permissions.html"
      - title: Connector の AWS 権限
        url: "/reference-permissions-aws.html"
      - title: Connector の Azure 権限
        url: "/reference-permissions-azure.html"
      - title: Connector の Google Cloud 権限
        url: "/reference-permissions-gcp.html"
    - title: ポート
      entries:
      - title: AWSでのコネクタセキュリティグループのルール
        url: "/reference-ports-aws.html"
      - title: Azureでのコネクタセキュリティグループのルール
        url: "/reference-ports-azure.html"
      - title: Google Cloudのコネクタファイアウォールルール
        url: "/reference-ports-gcp.html"
      - title: オンプレミスコネクタのポート
        url: "/reference-ports-on-prem.html"
  - title: 知識とサポート
    entries:
    - title: サポートに登録します
      url: "/task-support-registration.html"
    - title: ヘルプを表示します
      url: "/task-get-help.html"
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
