---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: BlueXPを使い始めるときは、ネットワークでBlueXPコンソールから特定のエンドポイントへのアクセスが許可されていることを確認してください。BlueXPの使用方法によっては、コネクタや特定のBlueXPサービス用のネットワークの設定も必要になる場合があります。 
---
= ネットワークの準備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPを使い始めるときは、ネットワークでBlueXPコンソールから特定のエンドポイントへのアクセスが許可されていることを確認してください。BlueXPの使用方法によっては、コネクタや特定のBlueXPサービス用のネットワークの設定も必要になる場合があります。



== BlueXPコンソールにユーザがアクセスできるようにネットワークを準備

SaaSレイヤで提供されるWebベースのBlueXPコンソールを使用すると、IT部門は複数のエンドポイントと通信してデータ管理タスクを実行します。Webブラウザを実行しているマシンは、これらのエンドポイントに接続されている必要があります。

[cols="2*"]
|===
| エンドポイント | 目的 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | BlueXPのWebベースのコンソールを使用すると、WebブラウザからこれらのURLにアクセスできます。 


 a| 
AWS サービス（ amazonaws.com ）：

* クラウド形成
* 柔軟なコンピューティングクラウド（ EC2 ）
* キー管理サービス（ KMS ）
* セキュリティトークンサービス（ STS ）
* シンプルなストレージサービス（ S3 ）

| BlueXPからAWSにコネクタを導入する場合に必要です。正確なエンドポイントは、コネクタを配置するリージョンによって異なります。 https://docs.aws.amazon.com/general/latest/gr/rande.html["詳細については、 AWS のマニュアルを参照してください。"^] 


| \https://management.azure.com

\https://login.microsoftonline.com | ほとんどのAzureリージョンでBlueXPからコネクタを導入する場合に必要です。 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Azureドイツ地域でBlueXPからコネクタを導入する場合に必要です。 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Azure US GovリージョンでBlueXPからコネクタを導入する場合に必要です。 


| \https://www.googleapis.com | Google CloudでBlueXPからConnectorを展開するために必要です。 


| \https://signin.b2c.netapp.com | NetApp Support Site (NSS)の資格情報を更新するか、新しいNSS資格情報をBlueXPに追加する必要があります。 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | Webブラウザはこれらのエンドポイントに接続して、BlueXPを介した集中型ユーザ認証を行います。 


| \https://widget.intercom.io | 製品内でのチャットにより、ネットアップのクラウドエキスパートと会話できます。 
|===
これらのエンドポイント以外にも、日常業務のために特定のエンドポイントに接続するためのアウトバウンドインターネットアクセスがコネクタにあることを確認する必要があります。これらのエンドポイントのリストは、次のセクションのリンクに従って確認できます。



== コネクタのネットワークの準備

コネクタのネットワークをどのように準備するかは、コネクタの設置場所によって異なります。コネクタの設置場所は、クラウド内でもオンプレミスでもかまいません。コネクタのネットワーク要件の詳細については、次のページを参照してください。

* link:task-set-up-networking-aws.html["AWSネットワークをセットアップする"]
* link:task-set-up-networking-azure.html["Azureネットワークをセットアップする"]
* link:task-set-up-networking-google.html["Google Cloudネットワークをセットアップする"]
* link:task-set-up-networking-on-prem.html["オンプレミスネットワークをセットアップする"]




== BlueXPサービスのネットワークを準備

BlueXPの使用を開始するときは、使用するBlueXPサービスのネットワーク要件を満たしていることを確認する必要があります。詳細については、各サービスのマニュアルを参照してください。

https://docs.netapp.com/us-en/bluexp-family/["BlueXPのマニュアル"^]
