---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: ユーザーにプラットフォーム ロールを割り当てて、 BlueXP の管理、ロールの割り当て、ユーザーの追加、コネクタの作成、フェデレーションの管理を行う権限を付与します。 
---
= BlueXP  プラットフォームアクセスロール
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ユーザーにプラットフォーム ロールを割り当てて、 BlueXP の管理、ロールの割り当て、ユーザーの追加、コネクタの作成、フェデレーションの管理を行う権限を付与します。

.大規模な多国籍組織のBlueXP  における組織の役割の例
XYZ 社は、データ ストレージ アクセスを北米、ヨーロッパ、アジア太平洋の地域別に整理し、各地域に制御権を与えながら集中的な監視を確保しています。

XYZ 社のBlueXPの *組織管理者* は、初期組織と各地域の個別のフォルダーを作成します。各リージョンのフォルダには、そのリージョンに関連するプロジェクト（および関連リソース）が含まれています。組織管理者*は、各地域のBlueXP  ユーザーに*フォルダまたはプロジェクト管理者*ロールを割り当てます。

*フォルダ管理者またはプロジェクト管理者*の役割を持つ地域管理者は、新しいリソースとユーザーを追加することで、担当する地域（フォルダ）を管理します。また、管理するフォルダとプロジェクトの追加、削除、名前変更も行えます。*組織管理者*は新しいリソースの権限を継承し、組織全体のストレージ使用状況を可視化します。

同じ組織内で、あるユーザーに*フェデレーション管理者*ロールが割り当てられ、組織と企業IdPとのフェデレーションを管理します。このユーザーはフェデレーション組織の追加や削除はできますが、組織内のユーザーやリソースの管理はできません。組織は、フェデレーションのステータスを確認し、フェデレーション組織を（変更を加えずに）表示するための*フェデレーション閲覧者*ロールをユーザーに割り当てます

次の表は、各BlueXPプラットフォーム ロールが実行できるアクションを示しています。



== 組織管理の役割

[cols="2,1,1"]
|===
| タスク | 組織管理者 | フォルダまたはプロジェクト管理者 


| コネクタを作成します | はい。 | いいえ 


| 作業環境の作成、変更、削除（BlueXP  キャンバスを使用して新しいリソースを追加または検出） | はい。 | はい。 


| フォルダとプロジェクトの作成（削除を含む） | はい。 | いいえ 


| 既存のフォルダとプロジェクトの名前を変更する | はい。 | はい。 


| ロールの割り当てとユーザの追加 | はい。 | はい。 


| リソースとフォルダおよびプロジェクトの関連付け | はい。 | はい。 


| フォルダーおよびプロジェクトへのコネクターの関連付け | はい。 | いいえ 


| フォルダおよびプロジェクトからのコネクタの削除 | はい。 | いいえ 


| コネクタの管理（証明書、設定などの編集） | はい。 | いいえ 


| [設定]>[クレデンシャル] | はい。 | はい。 


| フェデレーションの作成、管理、表示 | はい。 | いいえ 


| サポートに登録してケースを提出する | はい。 | はい。 


| データサービスを使用する | はい。 | はい。 


| BlueXPのタイムラインと通知を表示する | はい。 | はい。 
|===


== 連盟の役割

[cols="2,1,1"]
|===
| タスク | 連盟管理者 | 連盟ビューア 


| 連盟を作成する | はい。 | いいえ 


| ドメインを確認する | はい。 | いいえ 


| フェデレーションにドメインを追加する | はい。 | いいえ 


| フェデレーションを無効化および削除する | はい。 | いいえ 


| テスト連盟 | はい。 | いいえ 


| 連盟とその詳細を表示する | はい。 | はい。 
|===