---
sidebar: sidebar 
permalink: reference-host-requirements-azure.html 
keywords: cpu requirements, ram requirements, azure requirements, azure host requirements, connector host requirements, azure vm size, vm size 
summary: コネクタソフトウェアは、特定のオペレーティングシステム要件、 RAM 要件、ポート要件などを満たすホストで実行する必要があります。コネクタを手動でインストールする場合は、以下の要件をホストが満たしていることを確認する必要があります。 
---
= Azureのインストールに必要なコネクタホストの要件を確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コネクタソフトウェアは、特定のオペレーティングシステム要件、 RAM 要件、ポート要件などを満たすホストで実行する必要があります。コネクタを手動でインストールする場合は、以下の要件をホストが満たしていることを確認する必要があります。

BlueXPまたはAzure Marketplaceからコネクタを導入する場合、イメージには必要なOSとソフトウェアコンポーネントが含まれています。

専用ホスト:: 他のアプリケーションと共有しているホストでは、このコネクタはサポートされていません。専用のホストである必要があります。
サポートされているオペレーティングシステム::
+
--
* Ubuntu 22.04.
* CentOS 7.6、7.7、7.8、7.9
* Red Hat Enterprise Linux 7.6、7.7、7.8、および7.9
+
ホストがRed Hat Subscription Managementに登録されている必要があります。登録されていない場合、ホストはコネクタのインストール時に必要なサードパーティ製ソフトウェアを更新するためのリポジトリにアクセスできません。

+
Connector は、これらのオペレーティングシステムの英語版でサポートされています。



--
ハイパーバイザー:: Ubuntu、CentOS、またはRed Hat Enterprise Linuxの実行が認定されているベアメタルまたはホスト型のハイパーバイザーが必要です。
+
--
https://access.redhat.com/certified-hypervisors["Red Hat ソリューション：「 Which hypervisors are certified to run Red Hat Enterprise Linux ？」"^]

--
CPU:: 4 コアまたは 4 個の vCPU
RAM:: 14 GB
Azure VM サイズ:: 上記の CPU と RAM の要件を満たすインスタンスタイプ。DS3 v2 を推奨します。
/opt のディスクスペース:: 100GiB のスペースが使用可能である必要があります
/var のディスク領域:: 20GiB のスペースが必要です
Docker Engine の略:: Connectorをインストールする前に、ホストにDocker Engineバージョン19.3.1以降が必要です。 https://docs.docker.com/engine/install/["インストール手順を確認します"^]

