---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: BlueXP  IDおよびアクセス管理には、組織のメンバーに割り当てることができる事前定義されたロールがいくつか含まれています。 
---
= 事前定義されたBlueXP  IAMロールと権限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP  IDおよびアクセス管理（IAM）には、リソース階層のさまざまなレベルで組織のメンバーに割り当てることができる、事前定義されたロールがいくつか含まれています。これらのロールを割り当てる前に、各ロールに含まれる権限について理解しておく必要があります。ロールは、プラットフォーム、アプリケーション、データサービスの3つのカテゴリに分類されます。



== プラットフォームの役割

プラットフォームロールは、ユーザに割り当てることができる最も広範なロールであり、ロールの割り当てやユーザの追加、BlueXP  のすべての機能の実行など、BlueXP  の管理に対する幅広い権限を許可します。BlueXP  IAMには、組織管理者とフォルダ管理者またはプロジェクト管理者という2つのプラットフォームロールがあります。2つのBlueXP  IAMプラットフォームロールの主な違いはスコープです。



=== 組織管理者

組織内のすべてのプロジェクトおよびフォルダへの無制限のアクセス、任意のプロジェクトまたはフォルダへのメンバーの追加、任意のBlueXP  タスクの実行、任意のデータサービスの使用をユーザーに許可します。



=== フォルダまたはプロジェクト管理者

割り当てられている特定のプロジェクトおよびフォルダへの無制限のアクセスをユーザーに許可します。管理するプロジェクトまたはフォルダにメンバーを追加したり、任意のBlueXP  タスクを実行したり、割り当てられたフォルダまたはプロジェクト内の任意のデータサービスを使用したりできます。

フォルダまたはプロジェクト管理者ロールはコネクタを作成できません。



=== プラットフォームの役割の比較表

[cols="24,19,19"]
|===
| タスク | 組織管理者 | フォルダまたはプロジェクト管理者 


| コネクタの作成 | はい。 | いいえ 


| 作業環境の作成、変更、削除（BlueXP  キャンバスを使用して新しいリソースを追加または検出） | はい。 | はい。 


| プロジェクト/フォルダの作成（削除を含む） | はい。 | いいえ 


| 既存のプロジェクト/フォルダの名前変更 | はい。 | はい。 


| ロールの割り当てとユーザの追加 | はい。 | はい。 


| リソースとフォルダおよびプロジェクトの関連付け | はい。 | はい。 


| フォルダーおよびプロジェクトへのコネクターの関連付け | はい。 | いいえ 


| フォルダおよびプロジェクトからのコネクタの削除 | はい。 | いいえ 


| コネクタの管理（証明書、設定などの編集） | はい。 | いいえ 


| [設定]>[クレデンシャル] | はい。 | はい。 


| BlueXP  タイムラインを表示 | はい。 | はい。 


| BlueXP  サービスの使用 | はい。 | はい。 


| BlueXP  を登録してサポートケースを送信 | はい。 | はい。 
|===
大規模な多国籍組織のBlueXP  における組織の役割の例:: 多国籍企業であるXYZ Corporationは、北米、ヨーロッパ、アジア太平洋の地理的地域に基づいて、データストレージリソースへのアクセスを分離することを目指しています。各地域には、一元的な監視を維持しながら、リソースを独占的に管理できるようにしたいと考えています。
+
--
これを実現するために、XYZ社のBlueXP  で組織管理者ロールを割り当てられたユーザーが、初期作業環境を作成してから、地域ごとにBlueXP  に別 々 のフォルダを作成します。各リージョンのフォルダには、そのリージョンに関連するプロジェクト（および関連リソース）が含まれています。組織管理者は、各地域のBlueXP  ユーザーにフォルダ/プロジェクト管理者ロールを割り当てます。

初期セットアップが完了すると、フォルダまたはプロジェクト管理者の役割を持つ地域管理者は、新しい作業環境を作成し、地域内にユーザーを追加できます。これらの地域管理者は、割り当てられているフォルダやプロジェクトを追加/削除/名前変更することもできます。組織管理者は、新しい作業環境やリソースの権限を継承し、組織全体でのストレージ使用状況の可視性を維持します。

--




== アプリケーションの役割

アプリケーションロールは、Active IQデジタルアドバイザ（デジタルアドバイザとも呼ばれる）などのBlueXP  アプリケーションへのアクセスを提供します。



=== Storage Admin

ソフトウェアの更新やBlueXP  作業環境の作成と削除など、BlueXP  でストレージ管理機能を実行できます。

権限:: BlueXP  キャンバスを表示できます。BlueXP  コネクタを作成および管理できます。次のようなBlueXP  のストレージ健全性機能とガバナンス機能への読み取り/書き込みアクセスが可能
+
--
* デジタルアドバイザ
* 運用の耐障害性
* ソフトウェアアップデート（ソフトウェアアップデートを実行可能）
* デジタルウォレット
* 経済効率
* Sustainability Dashboard
* アラート


--




=== ストレージビューア

BlueXP  の健全性機能とガバナンス機能への読み取り専用アクセスを提供します。通常、このロールは、組織のストレージリソースの健全性の監視を担当するユーザに割り当てられます。このロールのユーザは、BlueXP  内で複数のアプリケーションを表示して、ソフトウェア更新計画や効率化計画を作成したり、ストレージ全体の健全性を確認したりできます。

権限:: 次のようなBlueXP  のストレージ健全性機能とガバナンス機能に読み取り専用でアクセスできます。
+
--
* デジタルアドバイザ
* 運用の耐障害性
* ソフトウェアの更新（アップグレードプランのダウンロードが可能）
* デジタルウォレット
* 経済効率
* Sustainability Dashboard
* アラート


--




== データサービスの役割

データサービスロールは、アクセス権を持つ組織、プロジェクト、またはフォルダ内のデータサービスに対してを使用する権限をユーザに提供します。



=== SnapCenterカンリシヤ

アプリケーションのBlueXP  バックアップ/リカバリを使用して、オンプレミスのONTAPクラスタからSnapshotをバックアップできます。

権限:: このロールを持つメンバーは、BlueXP  で次の操作を実行できます。
+
--
* [Backup and Recovery]>[Applications]から任意の操作を実行します。
* 権限を持つプロジェクトおよびフォルダ内のすべての作業環境を管理します。
* すべてのBlueXP  サービスを使用する


--




=== 分類ビューア

BlueXP  分類スキャン結果を表示する機能を提供します。

権限:: コンプライアンス情報を表示し、アクセス権を持つリソースのレポートを生成します。これらのユーザは、ボリューム、バケット、データベーススキーマのスキャンを有効または無効にすることはできません。
+
--
このロールを持つメンバーは、他のアクションを使用できません。

--




== 関連リンク

* link:concept-identity-and-access-management.html["BlueXP  のアイデンティティ管理とアクセス管理の詳細"]
* link:task-iam-get-started.html["BlueXP  IAMの使用を開始する"]
* link:task-iam-manage-members-permissions.html["BlueXP  メンバーとその権限を管理します。"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["BlueXP  IAM向けAPIの詳細"^]

