---
sidebar: sidebar 
permalink: reference-connector-maint-console.html 
keywords: transparent proxy, connector certificate, agent maintenance console, proxy configuration, connector proxy 
summary: メンテナンス コンソールを使用して、コネクタが透過プロキシ サーバーを使用するように構成します。 
---
= コネクタメンテナンスコンソール
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
メンテナンス コンソールを使用して、コネクタが透過プロキシ サーバーを使用するように構成できます。



== Maintenance Consoleにアクセスします

コネクタ ホストからメンテナンス コンソールにアクセスできます。次のディレクトリに移動します。

[source, CLI]
----
/opt/application/netapp/service-manager-2/connector-maint-console
----


== 透過プロキシコマンド

メンテナンス コンソールには、透過プロキシ サーバーを使用するようにコネクタを構成するコマンドが用意されています。



=== 現在の透過プロキシ構成を表示する

現在の透過プロキシ構成を表示するには、次のコマンドを使用します。

[source, CLI]
----
./connector-maint-console proxy get
----


=== 透過プロキシサーバーを追加する

透過プロキシサーバーを追加するには、次のコマンドを使用します。  `/home/ubuntu/myCA1.pem`プロキシサーバーの証明書ファイルへのパスです。証明書ファイルはPEM形式である必要があります。

[source, CLI]
----
./connector-maint-console proxy add -c /home/ubuntu/myCA1.pem
----
証明書ファイルがコマンドと同じディレクトリにあることを確認するか、証明書ファイルへのフルパスを指定します。



=== 透過プロキシサーバーの証明書を更新する

透過プロキシサーバーの証明書を更新するには、次のコマンドを使用します。  `/home/ubuntu/myCA1.pem`プロキシサーバーの新しい証明書ファイルへのパスです。証明書ファイルはPEM形式である必要があります。

[source, CLI]
----
./connector-maint-console proxy update -c /home/ubuntu/myCA1.pem
----
証明書ファイルがコマンドと同じディレクトリにあることを確認するか、証明書ファイルへのフルパスを指定します。



=== 透過プロキシサーバーを削除する

透過プロキシ サーバーを削除するには、次のコマンドを使用します。

[source, CLI]
----
./connector-maint-console proxy remove
----


=== 任意のコマンドのヘルプを表示する

コマンドのヘルプを表示するには、  `--help`コマンドにヘルプを表示します。例えば、  `proxy add`コマンドを実行するには、次のコマンドを使用します。

[source, CLI]
----
./connector-maint-console proxy add --help
----