---
sidebar: sidebar 
permalink: reference-user-roles.html 
keywords: user, users, roles, role, task, permission, permissions, tasks, admin, Account Admin, Workspace Admin, Cloud Compliance Viewer, Cloud Data Sense, SnapCenter Admin 
summary: アカウント管理者、ワークスペース管理者、コンプライアンスビューア、および SnapCenter 管理者の各ロールは、ユーザーに特定の権限を提供します。BlueXPアカウントに新しいユーザを関連付けるときに、これらのロールのいずれかを割り当てることができます。 
---
= ユーザロール
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP  をプライベートモードで使用する場合は、_ BlueXP  account_を使用してユーザーを管理します。アカウント管理者、ワークスペース管理者、コンプライアンスビューア、SnapCenter管理者のいずれかのロールを選択して、アカウント内のユーザーに特定の権限を付与できます。


NOTE: 2025年2月以降、標準および制限付きの導入モードでは、これらのユーザロールは廃止されました。BlueXP  プライベートモードでは、ユーザに関連付けるロールが1つだけ用意されています。つまり、すべてのBlueXP  権限を付与するCloud Managerのadminロールです。

BlueXP  を標準モードまたは制限モードで使用している場合は、BlueXP  アカウントはありません。代わりに、BlueXP  IDおよびアクセス管理(IAM)を使用して管理する_ BlueXP  organization_があります。

* link:concept-identity-and-access-management.html["BlueXP  IAMの詳細"]
* link:concept-modes.html["BlueXPの導入モードについて説明します"]


[cols="24,19,19,19,19"]
|===
| タスク | アカウント管理者 | ワークスペース管理者 | Compliance Viewer （コンプライアンスビューア） | SnapCenter 管理者 


| コネクタを作成します | はい。 | いいえ | いいえ | いいえ 


| 作業環境の管理 | はい。 | はい。 | いいえ | はい。 


| 作業環境でサービスを有効にします | はい。 | はい。 | いいえ | はい。 


| BlueXP  サービスの使用 | はい。 | はい。 | いいえ | はい。 


| ワークスペースからの作業環境の削除 | はい。 | はい。 | いいえ | いいえ 


| 作業環境を削除します | はい。 | はい。 | いいえ | いいえ 


| データ複製ステータスを表示します | はい。 | はい。 | いいえ | いいえ 


| タイムラインを表示します | はい。 | はい。 | いいえ | いいえ 


| ワークスペースを切り替えます | はい。 | はい。 | はい。 | はい。 


| BlueXPの分類スキャン結果を表示します | はい。 | はい。 | はい。 | いいえ 


| Cloud Volumes ONTAP レポートを受信します | はい。 | いいえ | いいえ | いいえ 


| BlueXPアカウントの管理 | はい。 | いいえ | いいえ | いいえ 


| クレデンシャルを管理する | はい。 | はい。 | いいえ | いいえ 


| BlueXPの設定を変更します | はい。 | はい。 | いいえ | いいえ 


| サポートダッシュボードを表示および管理します | はい。 | はい。 | いいえ | いいえ 
|===
.関連情報
link:task-managing-netapp-accounts.html["BlueXPアカウントを管理します"]
