---
sidebar: sidebar 
permalink: reference-connector-default-config.html 
keywords: linux, user name, operating system, installation files, installation folder, folder, log, logs, service, mysql, packages, linux, connector configuration, connector installation folder, connector folder, connector log, ubuntu 
summary: 導入前にコネクタの詳細を確認したり、問題のトラブルシューティングが必要な場合に利用できます。 
---
= コネクタのデフォルト設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コネクタを導入する前に、または問題のトラブルシューティングが必要な場合は、コネクタの設定に関する詳細を確認しておくことを推奨します。



== インターネットアクセスを使用するデフォルト設定

次の構成の詳細は、BlueXPからコネクタを導入した場合、クラウドプロバイダのマーケットプレイスからコネクタを導入した場合、またはインターネットにアクセスできるオンプレミスのLinuxホストにコネクタを手動でインストールした場合に適用されます。



=== AWSの詳細

BlueXPまたはクラウドプロバイダのマーケットプレイスからコネクタを導入した場合は、次の点に注意してください。

* EC2インスタンスタイプはt3.2xlargeです。
* イメージのオペレーティングシステムはUbuntu 22.04 LTSです。
+
オペレーティングシステムには GUI は含まれていません。システムにアクセスするには、端末を使用する必要があります。

* インストールには、必要なコンテナオーケストレーションツールであるDocker Engineが含まれています。
* EC2 Linuxインスタンスのユーザ名はUbuntuです（2023年5月より前に作成されたコネクタの場合、ユーザ名はEC2-user）。
* デフォルトのシステムディスクは100GiBのgp2ディスクです。




=== Azureの詳細

BlueXPまたはクラウドプロバイダのマーケットプレイスからコネクタを導入した場合は、次の点に注意してください。

* VMタイプはStandard_D8s_v3です。
* イメージのオペレーティングシステムはUbuntu 22.04 LTSです。
+
オペレーティングシステムには GUI は含まれていません。システムにアクセスするには、端末を使用する必要があります。

* インストールには、必要なコンテナオーケストレーションツールであるDocker Engineが含まれています。
* デフォルトのシステムディスクは100GiBのPremium SSDディスクです。




=== Google Cloudの詳細

BlueXPからコネクタを導入した場合は、次の点に注意してください。

* VMインスタンスがn2 -標準-8である。
* イメージのオペレーティングシステムはUbuntu 22.04 LTSです。
+
オペレーティングシステムには GUI は含まれていません。システムにアクセスするには、端末を使用する必要があります。

* インストールには、必要なコンテナオーケストレーションツールであるDocker Engineが含まれています。
* デフォルトのシステムディスクは100GiBのSSD永続ディスクです。




=== インストールフォルダ

Connector インストールフォルダは、次の場所にあります。

/opt/application/netapp/cloudmanager です



=== ログファイル

ログファイルは次のフォルダに格納されます。

* /opt/application/netapp/cloudmanager/log を選択します
または
* /opt/application/netapp/service-manager-2 /ログ（新規インストール3.9.23以降）
+
これらのフォルダのログには、コネクタの詳細が表示されます。

* /opt/application/NetApp/cloudmanager/docx_occm/data/log
+
このフォルダのログには、コネクタで実行されている クラウド サービス およびBlueXPサービスの詳細が表示されます。





=== コネクタサービス

* BlueXPサービスの名前はoccmです
* OCCM サービスは MySQL サービスに依存します。
+
MySQL サービスがダウンしている場合は、 OCCM サービスもダウンしています。





=== ポート

このコネクタは Linux ホストで次のポートを使用します。

* HTTP アクセスの場合は 80
* 443 ： HTTPS アクセス用




== インターネットアクセスを使用しないデフォルトの設定

インターネットにアクセスできないオンプレミスの Linux ホストにコネクタを手動でインストールした場合、次の構成が適用されます。 link:task-quick-start-private-mode.html["このインストールオプションの詳細については、こちらをご覧ください"]。

* Connector インストールフォルダは、次の場所にあります。
+
/opt/application/NetApp/DS

* ログファイルは次のフォルダに格納されます。
+
/var/lib/docker /volumes /DS_occmdata/_data/log

+
このフォルダのログには、 Connector イメージと Docker イメージの詳細が記録されます。

* すべてのサービスが Docker コンテナ内で実行されています
+
サービスは、実行されている Docker ランタイムサービスに依存します

* このコネクタは Linux ホストで次のポートを使用します。
+
** HTTP アクセスの場合は 80
** 443 ： HTTPS アクセス用



