---
sidebar: sidebar 
permalink: reference-host-requirements-google.html 
keywords: cpu requirements, ram requirements, google cloud requirements, google cloud host requirements, connector host requirements, gcp machine type, machine type 
summary: コネクタソフトウェアは、特定のオペレーティングシステム要件、 RAM 要件、ポート要件などを満たすホストで実行する必要があります。コネクタを手動でインストールする場合は、以下の要件をホストが満たしていることを確認する必要があります。コネクタを取り付ける前に、ホストがこれらの要件を満たしていることを確認してください。 
---
= Google Cloudのインストールに必要なコネクタホストの要件を確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コネクタソフトウェアは、特定のオペレーティングシステム要件、 RAM 要件、ポート要件などを満たすホストで実行する必要があります。コネクタを手動でインストールする場合は、以下の要件をホストが満たしていることを確認する必要があります。

BlueXPからまたはglcoudを使用してコネクタを導入する場合、イメージには必要なOSとソフトウェアコンポーネントが含まれています。

専用ホスト:: 他のアプリケーションと共有しているホストでは、このコネクタはサポートされていません。専用のホストである必要があります。
サポートされているオペレーティングシステム::
+
--
* CentOS 7.6、7.7、7.8、7.9
* Red Hat Enterprise Linux 7.6、7.7、7.8、7.9、8.6、 および8.7
+
ホストがRed Hat Subscription Managementに登録されている必要があります。登録されていない場合、ホストはコネクタのインストール時に必要なサードパーティ製ソフトウェアを更新するためのリポジトリにアクセスできません。

+
Connector は、これらのオペレーティングシステムの英語版でサポートされています。



--
ハイパーバイザー:: CentOSまたはRed Hat Enterprise Linuxの実行が認定されたベアメタルまたはホスト型のハイパーバイザーが必要です。 https://access.redhat.com/certified-hypervisors["Red Hat ソリューション：「 Which hypervisors are certified to run Red Hat Enterprise Linux ？」"^]
CPU:: 4 コアまたは 4 個の vCPU
RAM:: 14 GB
Google Cloudマシンのタイプ:: 上記の CPU と RAM の要件を満たすインスタンスタイプ。私たちは、n2規格4をお勧めします。
+
--
このコネクタは、OSがサポートされているVMインスタンス上のGoogle Cloudでサポートされます https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["シールドVM機能"^]

--
/opt のディスクスペース:: 100GiB のスペースが使用可能である必要があります
/var のディスク領域:: 20GiB のスペースが必要です
Docker Engine の略:: Connectorをインストールする前に、ホストにDocker Engineバージョン19.3.1以降が必要です。 https://docs.docker.com/engine/install/["インストール手順を確認します"^]

