---
sidebar: sidebar 
permalink: reference-iam-storage-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, identity and access management, access roles, admin 
summary: BlueXP  IDおよびアクセス管理には、組織のメンバーに割り当てることができる2つの管理ロールが用意されています。 
---
= BlueXP  のストレージアクセスロール
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
次のロールをユーザに割り当てて、サポートされるストレージリソースに関連付けられているBlueXP  のストレージ管理機能へのアクセスをユーザに許可することができます。ユーザには、ストレージ管理でアクションを実行できる管理ロールを割り当てることも、監視だけの場合はビューアロールを割り当てることもできます。

ストレージロールは、次のストレージリソースおよび機能のユーザに割り当てることができます。

ストレージリソース：

* オンプレミスの ONTAP クラスタ
* StorageGRID
* E シリーズ


BlueXP  のサービスと機能：

* デジタルアドバイザ
* ソフトウェアの更新
* 運用の耐障害性
* 経済効率
* 持続可能性


.BlueXP  のストレージロールの例
多国籍企業であるXYZ Corporationには、ストレージエンジニアやストレージ管理者の大規模なチームがあります。お客様は、このチームがそれぞれの地域のストレージ資産を管理できるようにする一方で、ユーザ管理、コネクタ作成、デジタルウォレットなどのコスト管理ツールなど、BlueXP  のコア管理タスクへのアクセスを制限したいと考えています。

12人のチームでは、2人のユーザに* Storage viewer *ロールが割り当てられ、割り当てられているBlueXP  プロジェクトに関連付けられているストレージリソースを監視できます。残りの9つには* Storage Admin *ロールが割り当てられます。このロールには、ソフトウェアの更新の管理、BlueXP  からONTAP System Managerへのアクセス、ストレージリソースの検出（作業環境の追加）が含まれます。チームの1人には*システムヘルススペシャリスト*ロールが割り当てられます。このロールでは、担当地域のストレージリソースの健全性を管理できますが、作業環境の変更や削除はできません。また、割り当てられたプロジェクトのストレージリソースに対してソフトウェアの更新を実行することもできます。

組織には、ユーザー管理、コネクタ作成、デジタルウォレットなどのコスト管理ツールなど、BlueXP  のすべての側面を管理できる* Organization admin*ロールを持つ2人のユーザーと、割り当てられているフォルダおよびプロジェクトのBlueXP  管理タスクを実行できる*フォルダまたはプロジェクト管理者*ロールを持つ複数のユーザーがいます。

次の表に、各BlueXP  ストレージロールで実行できる操作を示します。

[cols="40,20a,20a,20a"]
|===
| 特徴とアクション | Storage Admin | システムヘルススペシャリスト | ストレージビューア 


4+| *キャンバス*： 


| 新しいリソースの検出（新しい作業環境の作成）  a| 
はい。
 a| 
はい。
 a| 
いいえ



| 検出されたリソースを表示  a| 
はい。
 a| 
はい。
 a| 
いいえ



| 作業環境を削除します  a| 
はい。
 a| 
いいえ
 a| 
いいえ



| 作業環境の変更  a| 
はい。
 a| 
いいえ
 a| 
いいえ



| *コネクタの作成*  a| 
いいえ
 a| 
いいえ
 a| 
いいえ



4+| *デジタルアドバイザ* 


| すべてのページと機能を表示  a| 
はい。
 a| 
はい。
 a| 
はい。



4+| *デジタルウォレット* 


| すべてのページと機能を表示  a| 
いいえ
 a| 
いいえ
 a| 
いいえ



4+| *ソフトウェアのアップデート* 


| ランディングページと推奨事項を表示する  a| 
はい。
 a| 
はい。
 a| 
はい。



| 推奨されるバージョンと主なメリットを確認する  a| 
はい。
 a| 
はい。
 a| 
はい。



| クラスタの更新の詳細を表示する  a| 
はい。
 a| 
はい。
 a| 
はい。



| 更新前チェックを実行し、アップグレードプランをダウンロード  a| 
はい。
 a| 
はい。
 a| 
はい。



| ソフトウェアアップデートのインストール  a| 
はい。
 a| 
はい。
 a| 
いいえ



4+| *運用の耐障害性* 


| セキュリティリスクの問題をレビューします  a| 
はい。
 a| 
はい。
 a| 
はい。



| Ansibleプレイブックをダウンロード  a| 
はい。
 a| 
はい。
 a| 
いいえ



| 問題を自動的に修正  a| 
はい。
 a| 
はい。
 a| 
いいえ



4+| *経済効率* 


| キャパシティプランニングのステータスを確認します  a| 
はい。
 a| 
はい。
 a| 
はい。



| 次のアクションを選択（ベストプラクティス、階層）  a| 
はい。
 a| 
いいえ
 a| 
いいえ



| コールドデータをクラウドストレージに階層化し、ストレージを解放します  a| 
はい。
 a| 
はい。
 a| 
いいえ



| リマインダーを設定する  a| 
はい。
 a| 
はい。
 a| 
はい。



4+| *持続可能性* 


| ダッシュボードと推奨事項を表示  a| 
はい。
 a| 
はい。
 a| 
はい。



| レポートデータをダウンロード  a| 
はい。
 a| 
はい。
 a| 
はい。



| 炭素軽減パーセンテージの編集  a| 
はい。
 a| 
はい。
 a| 
いいえ



| 推奨事項の修正  a| 
はい。
 a| 
はい。
 a| 
いいえ



| 推奨事項を延期  a| 
はい。
 a| 
はい。
 a| 
いいえ



4+| *システムマネージャへのアクセス* 


| クレデンシャルを入力可能  a| 
はい。
 a| 
はい。
 a| 
いいえ



4+| * 資格情報 * 


| ユーザクレデンシャル  a| 
はい。
 a| 
はい。
 a| 
いいえ

|===