---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: SaaSレイヤで提供されるWebベースのBlueXPコンソールを使用すると、いくつかの管理タスクを実行する際に複数のエンドポイントに通信します。BlueXPコンソールにアクセスするコンピュータは、これらのエンドポイントに接続する必要があります。 
---
= BlueXPコンソールを使用するためのネットワークの準備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SaaSレイヤで提供されるWebベースのBlueXPコンソールを使用すると、いくつかの管理タスクを実行する際に複数のエンドポイントに通信します。BlueXPコンソールにアクセスするコンピュータは、これらのエンドポイントに接続する必要があります。

これらのエンドポイントは、BlueXPコンソールから特定の操作を実行するときに、ユーザのコンピュータからアクセスされます。また、コネクタや特定のBlueXPサービスのネットワーク要件も参照してください。詳細については、このページの最後にある関連リンクを参照してください。

[cols="2*"]
|===
| エンドポイント | 目的 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | BlueXPのWebベースのコンソールを使用すると、WebブラウザからこれらのURLにアクセスできます。 


| \https://aiq.netapp.com | BlueXP Digital Advisorにアクセスするには必要です。 


 a| 
AWS サービス（ amazonaws.com ）：

* クラウド形成
* 柔軟なコンピューティングクラウド（ EC2 ）
* キー管理サービス（ KMS ）
* セキュリティトークンサービス（ STS ）
* シンプルなストレージサービス（ S3 ）

| BlueXPからAWSにコネクタを導入する場合に必要です。正確なエンドポイントは、コネクタを配置するリージョンによって異なります。 https://docs.aws.amazon.com/general/latest/gr/rande.html["詳細については、 AWS のマニュアルを参照してください。"^] 


| \https://management.azure.com

\https://login.microsoftonline.com | ほとんどのAzureリージョンでBlueXPからコネクタを導入する場合に必要です。 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Azureドイツ地域でBlueXPからコネクタを導入する場合に必要です。 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Azure US GovリージョンでBlueXPからコネクタを導入する場合に必要です。 


| \https://www.googleapis.com | Google CloudでBlueXPからConnectorを展開するために必要です。 


| \https://signin.b2c.netapp.com | NetApp Support Site (NSS)の資格情報を更新するか、新しいNSS資格情報をBlueXPに追加する必要があります。 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | Webブラウザはこれらのエンドポイントに接続して、BlueXPを介した集中型ユーザ認証を行います。 


| \https://widget.intercom.io | 製品内でのチャットにより、ネットアップのクラウドエキスパートと会話できます。 
|===
これらのエンドポイント以外にも、日常業務のために特定のエンドポイントに接続するためのアウトバウンドインターネットアクセスがコネクタにあることを確認する必要があります。これらのエンドポイントのリストは、次のセクションのリンクに従って確認できます。

.関連リンク
* コネクタのネットワークを準備します
+
** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking["AWSネットワークをセットアップする"]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking["Azureネットワークをセットアップする"]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking["Google Cloudネットワークをセットアップする"]
** link:task-install-connector-on-prem.html#step-3-set-up-networking["オンプレミスネットワークをセットアップする"]


* BlueXPサービスのネットワークを準備
+
各BlueXPサービスのドキュメントを参照してください。

+
https://docs.netapp.com/us-en/bluexp-family/["BlueXPのマニュアル"^]


