---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, govcloud, BlueXP, Cloud Volumes ONTAP, days, running, Connectors should remain running, imdsv2, httpstokens 
summary: 既知の制限事項は、このリリースの製品でサポートされていないプラットフォーム、デバイス、機能、または製品と正しく相互運用できない機能を特定します。これらの制限事項を慎重に確認してください 
---
= 既知の制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
既知の制限事項は、このリリースの製品でサポートされていないプラットフォーム、デバイス、機能、または製品と正しく相互運用できない機能を特定します。これらの制限事項を慎重に確認してください

これらの制限は、BlueXPのセットアップと管理に特有のものです。コネクタ、SaaSプラットフォームなどです。



== コネクタの制限



=== デフォルトのEC2インスタンス設定は変更しないでください

AWSにコネクタを導入すると、デフォルトで次のEC2インスタンス設定が構成されます。

* IMDSv2はオプションに設定されています
* HttpTokensはオプションに設定されています


これらの設定を「必須」に変更しないでください。これらの設定を[必須]に変更すると、コネクタとCloud Volumes ONTAP の可用性に影響します。



=== 172 の範囲の IP アドレスと競合する可能性があります

BlueXPは、172.17.0.0/16と172.18.0.0/16の範囲にIPアドレスを持つ2つのインターフェイスを持つコネクタを展開します。

ネットワークにこれらのいずれかの範囲が設定されたサブネットがある場合、BlueXPから接続エラーが発生する可能性があります。たとえば、BlueXPでオンプレミスのONTAP クラスタを検出できない場合があります。

技術情報アーティクルを参照してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/Cloud_Manager_shows_inactive_as_Connector_IP_range_in_172.x.x.x_conflict_with_docker_network["BlueXP ConnectorのIPが既存のネットワークと競合しています"] コネクタのインターフェイスのIPアドレスを変更する方法については、を参照してください。



=== SSL復号化はサポートされていません

BlueXPでは、SSL復号化が有効になっているファイアウォール構成はサポートされていません。SSL復号化が有効になっている場合、BlueXPにエラーメッセージが表示され、コネクタインスタンスが非アクティブとして表示されます。

セキュリティを強化するには、を選択します link:task-installing-https-cert.html["認証局（ CA ）が署名した HTTPS 証明書をインストールする"]。



=== ローカル UI のロード時に空白ページが表示される

コネクタで実行されているWebベースのコンソールをロードすると、インターフェイスが表示されず、空白のページが表示されることがあります。

この問題は、キャッシュの問題に関連しています。回避策では、 incognito モードまたはプライベート Web ブラウザセッションを使用します。



=== 共有 Linux ホストはサポートされません

コネクタは、他のアプリケーションと共有されている VM ではサポートされません。VM は、コネクタソフトウェア専用にする必要があります。



=== サードパーティのエージェントと内線番号

Connector VM では、サードパーティのエージェントや VM 拡張機能はサポートされません。
