---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: BlueXP  IDおよびアクセス管理には、組織のメンバーに割り当てることができる事前定義されたロールがいくつか含まれています。 
---
= BlueXP  アクセスロール
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP  IDおよびアクセス管理（IAM）には、リソース階層のさまざまなレベルで組織のメンバーに割り当てることができる、事前定義されたロールがいくつか含まれています。これらのロールを割り当てる前に、各ロールに含まれる権限について理解しておく必要があります。ロールは、プラットフォームとデータサービスの2つのカテゴリに分類されます。



== プラットフォームの役割

プラットフォームロールは、ユーザに割り当てることができる最も広範なロールであり、ロールの割り当てやユーザの追加、BlueXP  のすべての機能の実行など、BlueXP  の管理に対する幅広い権限を許可します。BlueXP  IAMには、組織管理者とフォルダ管理者またはプロジェクト管理者という2つのプラットフォームロールがあります。2つのBlueXP  IAMプラットフォームロールの主な違いはスコープです。



=== 組織管理者

組織内のすべてのプロジェクトおよびフォルダへの無制限のアクセス、任意のプロジェクトまたはフォルダへのメンバーの追加、任意のBlueXP  タスクの実行、任意のデータサービスの使用をユーザーに許可します。



=== フォルダまたはプロジェクト管理者

割り当てられている特定のプロジェクトおよびフォルダへの無制限のアクセスをユーザーに許可します。管理するプロジェクトまたはフォルダにメンバーを追加したり、任意のBlueXP  タスクを実行したり、割り当てられたフォルダまたはプロジェクト内の任意のデータサービスを使用したりできます。

フォルダまたはプロジェクト管理者ロールはコネクタを作成できません。



=== プラットフォームの役割の比較表

[cols="24,19,19"]
|===
| タスク | 組織管理者 | フォルダまたはプロジェクト管理者 


| コネクタの作成 | はい。 | いいえ 


| 作業環境の作成、変更、削除（BlueXP  キャンバスを使用して新しいリソースを追加または検出） | はい。 | はい。 


| プロジェクト/フォルダの作成（削除を含む） | はい。 | いいえ 


| 既存のプロジェクト/フォルダの名前変更 | はい。 | はい。 


| ロールの割り当てとユーザの追加 | はい。 | はい。 


| リソースとフォルダおよびプロジェクトの関連付け | はい。 | はい。 


| フォルダーおよびプロジェクトへのコネクターの関連付け | はい。 | いいえ 


| フォルダおよびプロジェクトからのコネクタの削除 | はい。 | いいえ 


| コネクタの管理（証明書、設定などの編集） | はい。 | いいえ 


| [設定]>[クレデンシャル] | はい。 | はい。 


| BlueXP  タイムラインを表示 | はい。 | はい。 


| BlueXP  サービスの使用 | はい。 | はい。 


| BlueXP  を登録してサポートケースを送信 | はい。 | はい。 
|===
大規模な多国籍組織のBlueXP  における組織の役割の例:: 多国籍企業であるXYZ Corporationは、北米、ヨーロッパ、アジア太平洋の地理的地域に基づいて、データストレージリソースへのアクセスを分離することを目指しています。各地域には、一元的な監視を維持しながら、リソースを独占的に管理できるようにしたいと考えています。
+
--
これを実現するために、XYZ社のBlueXP  で組織管理者ロールを割り当てられたユーザーが、初期作業環境を作成してから、地域ごとにBlueXP  に別 々 のフォルダを作成します。各リージョンのフォルダには、そのリージョンに関連するプロジェクト（および関連リソース）が含まれています。組織管理者は、各地域のBlueXP  ユーザーにフォルダ/プロジェクト管理者ロールを割り当てます。

初期セットアップが完了すると、フォルダまたはプロジェクト管理者の役割を持つ地域管理者は、新しい作業環境を作成し、地域内にユーザーを追加できます。これらの地域管理者は、割り当てられているフォルダやプロジェクトを追加/削除/名前変更することもできます。組織管理者は、新しい作業環境やリソースの権限を継承し、組織全体でのストレージ使用状況の可視性を維持します。

--




== アプリケーションの役割

アプリケーションカテゴリのロールのリストを次に示します。



=== Keystoneロール

次のロールを使用して、Keystoneへのユーザアクセスを割り当てることができます。


NOTE: 現在、BlueXP  経由でKeystoneにアクセスする作業はベータ版です。Keystoneベータ版への参加をご希望の場合は、NetAppの担当者にお問い合わせください。

* * Keystone管理者*：Keystoneサブスクリプションを管理し、アラート、レポート、サブスクリプションに対してアクションを実行します。
* * Keystone Viewer *：Keystoneサブスクリプションのほか、レポート、アラート、アセットを表示できます。


次の表に、Keystoneの各ロールで実行できるアクションを示します。

[cols="40,20a,20a"]
|===
| 特徴とアクション | Keystone管理者 | Keystoneビューア 


| [Subscription]、[Assets]、[Monitor]、および[Administration]タブを表示します。  a| 
はい。
 a| 
はい。



3+| * Keystoneサブスクリプションページ*： 


| サブスクリプションを表示できる  a| 
はい。
 a| 
はい。



| サブスクリプションの変更または更新が可能  a| 
はい。
 a| 
いいえ



3+| * Keystone関連資料ページ*： 


| アセットの表示  a| 
はい。
 a| 
はい。



| 資産の管理  a| 
はい。
 a| 
いいえ



3+| * Keystoneアラートページ*： 


| アラートを表示します  a| 
はい。
 a| 
いいえ



| アラートの管理  a| 
はい。
 a| 
いいえ



| 自分用のアラートを作成する  a| 
はい。
 a| 
はい。



3+| *デジタルウォレット*： 


| デジタルウォレットを表示できる  a| 
はい。
 a| 
はい。



3+| * Keystoneレポートページ*： 


| レポートのダウンロード  a| 
はい。
 a| 
はい。



| レポートの管理  a| 
はい。
 a| 
はい。



| 自分用のレポートの作成  a| 
はい。
 a| 
はい。



3+| *サービスリクエスト*： 


| サービスリクエストの作成  a| 
はい。
 a| 
いいえ



| 組織内の任意のユーザーが作成したサービスリクエストを表示できる  a| 
はい。
 a| 
はい。

|===


== データサービスの役割

以下は、データサービスカテゴリのロールのリストです。



=== 分類ビューア

BlueXP  分類スキャン結果を表示する機能を提供します。

分類には管理者ロールがありません。

権限:: コンプライアンス情報を表示し、アクセス権を持つリソースのレポートを生成します。これらのユーザは、ボリューム、バケット、データベーススキーマのスキャンを有効または無効にすることはできません。


このロールを持つメンバーは、他のアクションを使用できません。



=== ランサムウェアからの保護

次のロールを使用して、ランサムウェア対策へのアクセスをユーザに割り当てることができます。

* *ランサムウェア対策管理者*：[保護]、[アラート]、[リカバリ]、[設定]、[レポート]の各タブでアクションを管理します。
* *ランサムウェア対策ビューア*：ワークロードデータの表示、アラートデータの表示、リカバリデータのダウンロード、レポートのダウンロードが可能です。


次の表に、各BlueXP  ランサムウェア対策ロールで実行できるアクションを示します。

[cols="40,20a,20a"]
|===
| 特徴とアクション | ランサムウェア対策管理者 | ランサムウェア対策ツール 


| ダッシュボードとすべてのタブを表示  a| 
はい。
 a| 
はい。



| 無償トライアルを開始  a| 
はい。
 a| 
いいえ



| ワークロードの検出を開始  a| 
はい。
 a| 
いいえ



3+| *[保護]タブで*： 


| ポリシーの追加、変更、削除  a| 
はい。
 a| 
いいえ



| ワークロードを保護  a| 
はい。
 a| 
いいえ



| 機密データを特定  a| 
はい。
 a| 
いいえ



| ワークロード保護の編集  a| 
はい。
 a| 
いいえ



| ワークロードの詳細を表示  a| 
はい。
 a| 
はい。



| データをダウンロードします  a| 
はい。
 a| 
はい。



3+| *[アラート]タブ*： 


| アラートの詳細の表示  a| 
はい。
 a| 
はい。



| インシデントステータスの編集  a| 
はい。
 a| 
いいえ



| インシデント詳細の表示  a| 
はい。
 a| 
はい。



| 影響を受けるファイルの完全なリストを取得  a| 
はい。
 a| 
いいえ



| アラートデータのダウンロード  a| 
はい。
 a| 
はい。



3+| *[リカバリ]タブで*： 


| 影響を受けるファイルのダウンロード  a| 
はい。
 a| 
いいえ



| ワークロードのリストア  a| 
はい。
 a| 
いいえ



| リカバリデータのダウンロード  a| 
はい。
 a| 
はい。



| レポートのダウンロード  a| 
はい。
 a| 
はい。



3+| *[設定]タブで*： 


| バックアップターゲットの追加または変更  a| 
はい。
 a| 
いいえ



| SIEMターゲットの追加または変更  a| 
はい。
 a| 
いいえ



3+| *[レポート]タブで*： 


| レポートのダウンロード  a| 
はい。
 a| 
はい。

|===


=== SnapCenterカンリシヤ

アプリケーションのBlueXP  バックアップ/リカバリを使用して、オンプレミスのONTAPクラスタからSnapshotをバックアップできます。

SnapCenterにはビューアの役割はありません。

権限:: このロールを持つメンバーは、BlueXP  で次の操作を実行できます。
+
--
* [Backup and Recovery]>[Applications]から任意の操作を実行します。
* 権限を持つプロジェクトおよびフォルダ内のすべての作業環境を管理します。
* すべてのBlueXP  サービスを使用する


--




== 関連リンク

* link:concept-identity-and-access-management.html["BlueXP  のアイデンティティ管理とアクセス管理の詳細"]
* link:task-iam-get-started.html["BlueXP  IAMの使用を開始する"]
* link:task-iam-manage-members-permissions.html["BlueXP  メンバーとその権限を管理します。"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["BlueXP  IAM向けAPIの詳細"^]

