---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: BlueXP  IDおよびアクセス管理には、組織のメンバーに割り当てることができる事前定義されたロールがいくつか含まれています。 
---
= BlueXP  プラットフォームアクセスロール
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
プラットフォームロールは、ユーザに割り当てることができる最も広範なロールで、ロールの割り当てやユーザの追加など、BlueXPの管理に必要なすべての権限を許可します。プラットフォームロールを持つユーザは、BlueXP  内のすべてのデータサービスとアプリケーションにアクセスできます。BlueXP  には、* Organization admin*と* FolderまたはProject admin*という2つのプラットフォームロールがあります。2つのBlueXP  プラットフォームロールの主な違いは、ロールが適用される範囲です。

.大規模な多国籍組織のBlueXP  における組織の役割の例
多国籍企業であるXYZ Corporationは、北米、ヨーロッパ、アジア太平洋の地理的地域に基づいて、データストレージリソースへのアクセスを分離することを目指しています。各地域には、一元的な監視を維持しながら、リソースを独占的に管理できるようにしたいと考えています。

これを実現するために、XYZ CorporationのBlueXP  で* Organization admin*ロールを割り当てられたユーザーが、初期作業環境を作成し、地域ごとにBlueXP  に別 々 のフォルダを作成します。各リージョンのフォルダには、そのリージョンに関連するプロジェクト（および関連リソース）が含まれています。組織管理者*は、各地域のBlueXP  ユーザーに*フォルダまたはプロジェクト管理者*ロールを割り当てます。

初期セットアップが完了すると、*フォルダまたはプロジェクト管理者*ロールを持つ地域管理者は、新しい作業環境を作成し、地域内にユーザーを追加できます。これらの地域管理者は、割り当てられているフォルダやプロジェクトを追加/削除/名前変更することもできます。組織管理者*は、新しい作業環境やリソースの権限を継承し、組織全体でのストレージ使用状況の可視性を維持します。

次の表に、BlueXP  プラットフォームの各ロールで実行できるアクションを示します。

[cols="2,1,1"]
|===
| タスク | 組織管理者 | フォルダまたはプロジェクト管理者 


| コネクタを作成します | はい。 | いいえ 


| 作業環境の作成、変更、削除（BlueXP  キャンバスを使用して新しいリソースを追加または検出） | はい。 | はい。 


| フォルダとプロジェクトの作成（削除を含む） | はい。 | いいえ 


| 既存のフォルダとプロジェクトの名前を変更する | はい。 | はい。 


| ロールの割り当てとユーザの追加 | はい。 | はい。 


| リソースとフォルダおよびプロジェクトの関連付け | はい。 | はい。 


| フォルダーおよびプロジェクトへのコネクターの関連付け | はい。 | いいえ 


| フォルダおよびプロジェクトからのコネクタの削除 | はい。 | いいえ 


| コネクタの管理（証明書、設定などの編集） | はい。 | いいえ 


| [設定]>[クレデンシャル] | はい。 | はい。 


| BlueXP  タイムラインを表示 | はい。 | はい。 


| BlueXP  サービスの使用 | はい。 | はい。 


| BlueXP  を登録してサポートケースを送信 | はい。 | はい。 
|===