---
sidebar: sidebar 
permalink: reference-permissions-azure.html 
keywords: permissions, azure, azure permissions 
summary: BlueXPがAzureでConnector VMを起動すると、そのAzureサブスクリプション内のリソースとプロセスを管理するための権限をConnectorに提供するカスタムロールがVMに割り当てられます。Connectorは、権限を使用して複数のAzureサービスに対してAPI呼び出しを実行します。 
---
= Connector の Azure 権限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPがAzureでConnector VMを起動すると、そのAzureサブスクリプション内のリソースとプロセスを管理するための権限をConnectorに提供するカスタムロールがVMに割り当てられます。Connectorは、権限を使用して複数のAzureサービスに対してAPI呼び出しを実行します。



== カスタムロールの権限

以下のカスタムロールには、Azureネットワーク内のリソースとプロセスを管理するためにConnectorで必要となる権限が含まれています。

BlueXPからコネクタを直接作成すると、BlueXPは自動的にこのカスタムロールをコネクタに適用します。

Azure MarketplaceからConnectorを導入する場合、またはLinuxホストにConnectorを手動でインストールする場合は、カスタムロールを自分で設定する必要があります。

* link:task-set-up-permissions-azure.html["Azureでコネクタをインストールするための権限を設定する（標準モード）"]
* link:task-set-up-permissions-on-prem.html["オンプレミスでのコネクタインストールの権限の設定（標準モード）"]
* link:task-prepare-restricted-mode.html#prepare-cloud-permissions["制限モードの権限を設定します"]
* link:task-prepare-private-mode.html#prepare-cloud-permissions["プライベートモードの権限を設定します"]


また、新しい権限が以降のリリースで追加されるときに、ロールが最新の状態であることを確認する必要があります。

[source, json]
----
{
    "Name": "BlueXP Operator",
    "Actions": [
                    "Microsoft.Compute/disks/delete",
                    "Microsoft.Compute/disks/read",
                    "Microsoft.Compute/disks/write",
                    "Microsoft.Compute/locations/operations/read",
                    "Microsoft.Compute/locations/vmSizes/read",
                    "Microsoft.Resources/subscriptions/locations/read",
                    "Microsoft.Compute/operations/read",
                    "Microsoft.Compute/virtualMachines/instanceView/read",
                    "Microsoft.Compute/virtualMachines/powerOff/action",
                    "Microsoft.Compute/virtualMachines/read",
                    "Microsoft.Compute/virtualMachines/restart/action",
                    "Microsoft.Compute/virtualMachines/deallocate/action",
                    "Microsoft.Compute/virtualMachines/start/action",
                    "Microsoft.Compute/virtualMachines/vmSizes/read",
                    "Microsoft.Compute/virtualMachines/write",
                    "Microsoft.Compute/images/read",
                    "Microsoft.Network/locations/operationResults/read",
                    "Microsoft.Network/locations/operations/read",
                    "Microsoft.Network/networkInterfaces/read",
                    "Microsoft.Network/networkInterfaces/write",
                    "Microsoft.Network/networkInterfaces/join/action",
                    "Microsoft.Network/networkSecurityGroups/read",
                    "Microsoft.Network/networkSecurityGroups/write",
                    "Microsoft.Network/networkSecurityGroups/join/action",
                    "Microsoft.Network/virtualNetworks/read",
                    "Microsoft.Network/virtualNetworks/checkIpAddressAvailability/read",
                    "Microsoft.Network/virtualNetworks/subnets/read",
                    "Microsoft.Network/virtualNetworks/subnets/write",
                    "Microsoft.Network/virtualNetworks/subnets/virtualMachines/read",
                    "Microsoft.Network/virtualNetworks/virtualMachines/read",
                    "Microsoft.Network/virtualNetworks/subnets/join/action",
                    "Microsoft.Resources/deployments/operations/read",
                    "Microsoft.Resources/deployments/read",
                    "Microsoft.Resources/deployments/write",
                    "Microsoft.Resources/resources/read",
                    "Microsoft.Resources/subscriptions/operationresults/read",
                    "Microsoft.Resources/subscriptions/resourceGroups/delete",
                    "Microsoft.Resources/subscriptions/resourceGroups/read",
                    "Microsoft.Resources/subscriptions/resourcegroups/resources/read",
                    "Microsoft.Resources/subscriptions/resourceGroups/write",
                    "Microsoft.Storage/checknameavailability/read",
                    "Microsoft.Storage/operations/read",
                    "Microsoft.Storage/storageAccounts/listkeys/action",
                    "Microsoft.Storage/storageAccounts/read",
                    "Microsoft.Storage/storageAccounts/delete",
                    "Microsoft.Storage/storageAccounts/write",
                    "Microsoft.Storage/storageAccounts/blobServices/containers/read",
                    "Microsoft.Storage/storageAccounts/listAccountSas/action",
                    "Microsoft.Storage/usages/read",
                    "Microsoft.Compute/snapshots/write",
                    "Microsoft.Compute/snapshots/read",
                    "Microsoft.Compute/availabilitySets/write",
                    "Microsoft.Compute/availabilitySets/read",
                    "Microsoft.Compute/disks/beginGetAccess/action",
                    "Microsoft.MarketplaceOrdering/offertypes/publishers/offers/plans/agreements/read",
                    "Microsoft.MarketplaceOrdering/offertypes/publishers/offers/plans/agreements/write",
                    "Microsoft.Network/loadBalancers/read",
                    "Microsoft.Network/loadBalancers/write",
                    "Microsoft.Network/loadBalancers/delete",
                    "Microsoft.Network/loadBalancers/backendAddressPools/read",
                    "Microsoft.Network/loadBalancers/backendAddressPools/join/action",
                    "Microsoft.Network/loadBalancers/loadBalancingRules/read",
                    "Microsoft.Network/loadBalancers/probes/read",
                    "Microsoft.Network/loadBalancers/probes/join/action",
                    "Microsoft.Authorization/locks/*",
                    "Microsoft.Network/routeTables/join/action",
                    "Microsoft.NetApp/netAppAccounts/read",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/read",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/write",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/read",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/delete",
                    "Microsoft.Network/privateEndpoints/write",
                    "Microsoft.Storage/storageAccounts/PrivateEndpointConnectionsApproval/action",
                    "Microsoft.Storage/storageAccounts/privateEndpointConnections/read",
                    "Microsoft.Storage/storageAccounts/managementPolicies/read",
                    "Microsoft.Storage/storageAccounts/managementPolicies/write",
                    "Microsoft.Network/privateEndpoints/read",
                    "Microsoft.Network/privateDnsZones/write",
                    "Microsoft.Network/privateDnsZones/virtualNetworkLinks/write",
                    "Microsoft.Network/virtualNetworks/join/action",
                    "Microsoft.Network/privateDnsZones/A/write",
                    "Microsoft.Network/privateDnsZones/read",
                    "Microsoft.Network/privateDnsZones/virtualNetworkLinks/read",
                    "Microsoft.Resources/deployments/operationStatuses/read",
                    "Microsoft.Insights/Metrics/Read",
                    "Microsoft.Compute/virtualMachines/extensions/write",
                    "Microsoft.Compute/virtualMachines/extensions/delete",
                    "Microsoft.Compute/virtualMachines/extensions/read",
                    "Microsoft.Compute/virtualMachines/delete",
                    "Microsoft.Network/networkInterfaces/delete",
                    "Microsoft.Network/networkSecurityGroups/delete",
                    "Microsoft.Resources/deployments/delete",
                    "Microsoft.Compute/diskEncryptionSets/read",
                    "Microsoft.Compute/snapshots/delete",
                    "Microsoft.Network/privateEndpoints/delete",
                    "Microsoft.Compute/availabilitySets/delete",
                    "Microsoft.KeyVault/vaults/read",
                    "Microsoft.KeyVault/vaults/accessPolicies/write",
                    "Microsoft.Compute/diskEncryptionSets/write",
                    "Microsoft.KeyVault/vaults/deploy/action",
                    "Microsoft.Compute/diskEncryptionSets/delete",
                    "Microsoft.Resources/tags/read",
                    "Microsoft.Resources/tags/write",
                    "Microsoft.Resources/tags/delete",
                    "Microsoft.Network/applicationSecurityGroups/write",
                    "Microsoft.Network/applicationSecurityGroups/read",
                    "Microsoft.Network/applicationSecurityGroups/joinIpConfiguration/action",
                    "Microsoft.Network/networkSecurityGroups/securityRules/write",
                    "Microsoft.Network/applicationSecurityGroups/delete",
                    "Microsoft.Network/networkSecurityGroups/securityRules/delete",
                    "Microsoft.ContainerService/managedClusters/listClusterUserCredential/action",
                    "Microsoft.ContainerService/managedClusters/read",
                    "Microsoft.Synapse/workspaces/write",
                    "Microsoft.Synapse/workspaces/read",
                    "Microsoft.Synapse/workspaces/delete",
                    "Microsoft.Synapse/register/action",
                    "Microsoft.Synapse/checkNameAvailability/action",
                    "Microsoft.Synapse/workspaces/operationStatuses/read",
                    "Microsoft.Synapse/workspaces/firewallRules/read",
                    "Microsoft.Synapse/workspaces/replaceAllIpFirewallRules/action",
                    "Microsoft.Synapse/workspaces/operationResults/read",
                    "Microsoft.Synapse/workspaces/privateEndpointConnectionsApproval/action",
                    "Microsoft.ManagedIdentity/userAssignedIdentities/assign/action",
                    "Microsoft.Compute/images/write",
                    "Microsoft.Network/loadBalancers/frontendIPConfigurations/read"
    ],
    "NotActions": [],
    "AssignableScopes": [],
    "Description": "BlueXP Permissions",
    "IsCustom": "true"
}
----


== Azure権限の使用方法

以降のセクションでは、各BlueXPサービスでの権限の使用方法について説明します。この情報は、企業のポリシーによって、必要な場合にのみアクセス許可が指定されるように指定されている場合に役立ちます。



=== Azure NetApp Files の特長

BlueXP分類を使用してAzure NetApp Filesデータをスキャンする場合、コネクタは次のAPI要求を行います。

* Microsoft.NetApp/netAppAccounts/read
* Microsoft.NetApp/netAppAccounts/capacityPools/read
* Microsoft.NetApp/netAppAccounts/capacityPools/volumes/write
* Microsoft.NetApp/netAppAccounts/capacityPools/volumes/read
* Microsoft.NetApp/netAppAccounts/capacityPools/volumes/delete




=== バックアップとリカバリ

コネクタは、BlueXPのバックアップとリカバリ用に次のAPI要求を行います。

* Microsoft.Compute/virtualMachines/read
* Microsoft.Compute/virtualMachines/start/action
* Microsoft.Compute/virtualMachines/deallocate/action
* microsoft.Storage/storageAccounts/listkeys/action
* microsoft.Storage/storageAccounts/read
* microsoft.Storage/storageAccounts/write
* microsoft.Storage/storageAccounts/blobServices/container/read
* microsoft.Storage/storageAccountSas/action
* microsoft.KeyVault/vaults/read
* Microsoft。KeyVault/vaults/accessPolicies/write
* Microsoft.Network/networkInterfaces/read
* microsoft.Resources/Subscriptions /locations /read
* Microsoft.Network/virtualNetworks/read
* Microsoft.Network/virtualNetworks/subnets/read
* microsoft.Resources/Subscriptions /resourceGroups/read
* microsoft.resources/Subscriptions /resourcegroups/resources/read
* microsoft.Resources/Subscriptions /resourceGroups/write
* Microsoft *。許可/ロック/*
* Microsoft.Network/privateEndpoints/write
* Microsoft.Network/privateEndpoints/read
* Microsoft.Network/privateDnsZones/virtualNetworkLinks/write
* Microsoft.Network/virtualNetworks/join/action
* Microsoft.Network/privateDnsZones/A/write
* Microsoft.Network/privateDnsZones/read
* Microsoft.Network/privateDnsZones/virtualNetworkLinks/read
* Microsoft.Compute/virtualMachines/extensions/delete
* Microsoft.Compute/virtualMachines/delete
* Microsoft.Network/networkInterfaces/delete
* Microsoft.Network/networkSecurityGroups/delete
* microsoft.Resources/Deployments/delete
* microsoft.ManagedIdentity/userAssignedIdentities/assign/action


検索とリストア機能を使用すると、コネクタは次のAPI要求を実行します。

* Microsoft .Synapse/workspaces /書き込み
* Microsoft . Synapse/workspaces / read
* Microsoft .Synapse/workspaces /削除
* Microsoft .Synapse/register/action
* microsoft.Synapse/checkNameAvailability/action
* Microsoft .Synapse/workspaces /operationStatuses /read
* Microsoft . Synapse/workspaces / firewallRules/read
* Microsoft .Synapse/workspaces/replaceAllIpFirewallRules/action
* Microsoft .Synapse/workspaces /操作結果/読み取り
* Microsoft .Synapse/workspaces /privateEndpointConnectionsApproval / action




=== 分類

BlueXP分類を使用する場合、コネクタは次のAPI要求を行います。

[cols="3*"]
|===
| アクション | セットアップに使用？ | 日々の業務に使用されるか？ 


| Microsoft.Compute/locations/operations/read | はい。 | はい。 


| Microsoft.Compute/locations/vmSizes/read | はい。 | はい。 


| Microsoft.Compute/operations/read | はい。 | はい。 


| Microsoft.Compute/virtualMachines/instanceView/read | はい。 | はい。 


| Microsoft.Compute/virtualMachines/powerOff/action | はい。 | いいえ 


| Microsoft.Compute/virtualMachines/read | はい。 | はい。 


| Microsoft.Compute/virtualMachines/restart/action | はい。 | いいえ 


| Microsoft.Compute/virtualMachines/start/action | はい。 | いいえ 


| Microsoft.Compute/virtualMachines/vmSizes/read | いいえ | はい。 


| Microsoft.Compute/virtualMachines/write | はい。 | いいえ 


| Microsoft.Compute/images/read | はい。 | はい。 


| Microsoft.Compute/disks/delete | はい。 | いいえ 


| Microsoft.Compute/disks/read | はい。 | はい。 


| Microsoft.Compute/disks/write | はい。 | いいえ 


| Microsoft. Storage/checknameavailability/read | はい。 | はい。 


| Microsoft。ストレージ/運用/読み取り | はい。 | はい。 


| microsoft.Storage/storageAccounts/listkeys/action | はい。 | いいえ 


| microsoft.Storage/storageAccounts/read | はい。 | はい。 


| microsoft.Storage/storageAccounts/write | はい。 | いいえ 


| microsoft.Storage/storageAccounts/blobServices/container/read | はい。 | はい。 


| Microsoft.Network/networkInterfaces/read | はい。 | はい。 


| Microsoft.Network/networkInterfaces/write | はい。 | いいえ 


| Microsoft.Network/networkInterfaces/join/action | はい。 | いいえ 


| Microsoft.Network/networkSecurityGroups/read | はい。 | はい。 


| Microsoft.Network/networkSecurityGroups/write | はい。 | いいえ 


| microsoft.Resources/Subscriptions /locations /read | はい。 | はい。 


| Microsoft.Network/locations/operationResults/read | はい。 | はい。 


| Microsoft.Network/locations/operations/read | はい。 | はい。 


| Microsoft.Network/virtualNetworks/read | はい。 | はい。 


| Microsoft.Network/virtualNetworks/checkIpAddressAvailability/read | はい。 | はい。 


| Microsoft.Network/virtualNetworks/subnets/read | はい。 | はい。 


| Microsoft.Network/virtualNetworks/subnets/virtualMachines/read | はい。 | はい。 


| Microsoft.Network/virtualNetworks/virtualMachines/read | はい。 | はい。 


| Microsoft.Network/virtualNetworks/subnets/join/action | はい。 | いいえ 


| Microsoft.Network/virtualNetworks/subnets/write | はい。 | いいえ 


| Microsoft.Network/routeTables/join/action | はい。 | いいえ 


| microsoft.Resources/Deployments/operations/read | はい。 | はい。 


| Microsoft .Resources/Deployments/read | はい。 | はい。 


| Microsoft .Resources/Deployments/write | はい。 | いいえ 


| microsoft.resources/resources/read | はい。 | はい。 


| microsoft.Resources/Subscriptions /operationresults/read | はい。 | はい。 


| microsoft.Resources/Subscriptions /resourceGroups/delete | はい。 | いいえ 


| microsoft.Resources/Subscriptions /resourceGroups/read | はい。 | はい。 


| microsoft.resources/Subscriptions /resourcegroups/resources/read | はい。 | はい。 


| microsoft.Resources/Subscriptions /resourceGroups/write | はい。 | いいえ 
|===


=== Cloud Volumes ONTAP

Connectorは、AzureでCloud Volumes ONTAP の導入と管理を行うために次のAPI要求を実行します。

[cols="5*"]
|===
| 目的 | アクション | 導入に使用 | 日々の業務に使用されるか？ | 削除しますか？ 


.14+| VMの作成と管理 | Microsoft.Compute/locations/operations/read | はい。 | はい。 | いいえ 


| Microsoft.Compute/locations/vmSizes/read | はい。 | はい。 | いいえ 


| microsoft.Resources/Subscriptions /locations /read | はい。 | いいえ | いいえ 


| Microsoft.Compute/operations/read | はい。 | はい。 | いいえ 


| Microsoft.Compute/virtualMachines/instanceView/read | はい。 | はい。 | いいえ 


| Microsoft.Compute/virtualMachines/powerOff/action | はい。 | はい。 | いいえ 


| Microsoft.Compute/virtualMachines/read | はい。 | はい。 | いいえ 


| Microsoft.Compute/virtualMachines/restart/action | はい。 | はい。 | いいえ 


| Microsoft.Compute/virtualMachines/start/action | はい。 | はい。 | いいえ 


| Microsoft.Compute/virtualMachines/deallocate/action | いいえ | はい。 | はい。 


| Microsoft.Compute/virtualMachines/vmSizes/read | いいえ | はい。 | いいえ 


| Microsoft.Compute/virtualMachines/write | はい。 | はい。 | いいえ 


| Microsoft.Compute/virtualMachines/delete | はい。 | はい。 | はい。 


| microsoft.Resources/Deployments/delete | はい。 | いいえ | いいえ 


.2+| VHDからの導入を有効にします | Microsoft.Compute/images/read | はい。 | いいえ | いいえ 


| Microsoft.Compute/images/write | はい。 | いいえ | いいえ 


.4+| ターゲットサブネットのネットワークインターフェイスを作成および管理します | Microsoft.Network/networkInterfaces/read | はい。 | はい。 | いいえ 


| Microsoft.Network/networkInterfaces/write | はい。 | はい。 | いいえ 


| Microsoft.Network/networkInterfaces/join/action | はい。 | はい。 | いいえ 


| Microsoft.Network/networkInterfaces/delete | はい。 | はい。 | いいえ 


.4+| ネットワークセキュリティグループを作成および管理します | Microsoft.Network/networkSecurityGroups/read | はい。 | はい。 | いいえ 


| Microsoft.Network/networkSecurityGroups/write | はい。 | はい。 | いいえ 


| Microsoft.Network/networkSecurityGroups/join/action | はい。 | いいえ | いいえ 


| Microsoft.Network/networkSecurityGroups/delete | いいえ | はい。 | はい。 


.8+| リージョンおよびターゲットのVNetとサブネットのネットワーク情報を取得し、VMをVNetに追加します | Microsoft.Network/locations/operationResults/read | はい。 | はい。 | いいえ 


| Microsoft.Network/locations/operations/read | はい。 | はい。 | いいえ 


| Microsoft.Network/virtualNetworks/read | はい。 | いいえ | いいえ 


| Microsoft.Network/virtualNetworks/checkIpAddressAvailability/read | はい。 | いいえ | いいえ 


| Microsoft.Network/virtualNetworks/subnets/read | はい。 | はい。 | いいえ 


| Microsoft.Network/virtualNetworks/subnets/virtualMachines/read | はい。 | はい。 | いいえ 


| Microsoft.Network/virtualNetworks/virtualMachines/read | はい。 | はい。 | いいえ 


| Microsoft.Network/virtualNetworks/subnets/join/action | はい。 | はい。 | いいえ 


.9+| リソースグループを作成および管理する | microsoft.Resources/Deployments/operations/read | はい。 | はい。 | いいえ 


| Microsoft .Resources/Deployments/read | はい。 | はい。 | いいえ 


| Microsoft .Resources/Deployments/write | はい。 | はい。 | いいえ 


| microsoft.resources/resources/read | はい。 | はい。 | いいえ 


| microsoft.Resources/Subscriptions /operationresults/read | はい。 | はい。 | いいえ 


| microsoft.Resources/Subscriptions /resourceGroups/delete | はい。 | はい。 | はい。 


| microsoft.Resources/Subscriptions /resourceGroups/read | いいえ | はい。 | いいえ 


| microsoft.resources/Subscriptions /resourcegroups/resources/read | はい。 | はい。 | いいえ 


| microsoft.Resources/Subscriptions /resourceGroups/write | はい。 | はい。 | いいえ 


.10+| Azureストレージアカウントおよびディスクを管理する | Microsoft.Compute/disks/read | はい。 | はい。 | はい。 


| Microsoft.Compute/disks/write | はい。 | はい。 | いいえ 


| Microsoft.Compute/disks/delete | はい。 | はい。 | はい。 


| Microsoft. Storage/checknameavailability/read | はい。 | はい。 | いいえ 


| Microsoft。ストレージ/運用/読み取り | はい。 | はい。 | いいえ 


| microsoft.Storage/storageAccounts/listkeys/action | はい。 | はい。 | いいえ 


| microsoft.Storage/storageAccounts/read | はい。 | はい。 | いいえ 


| microsoft.Storage/storageAccounts/delete | いいえ | はい。 | はい。 


| microsoft.Storage/storageAccounts/write | はい。 | はい。 | いいえ 


| Microsoft. Storage/uses/read：ストレージ/使用状況/読み取り | いいえ | はい。 | いいえ 


.3+| ストレージアカウントのBLOBストレージへのバックアップと暗号化を有効にします | microsoft.Storage/storageAccounts/blobServices/container/read | はい。 | はい。 | いいえ 


| microsoft.KeyVault/vaults/read | はい。 | はい。 | いいえ 


| Microsoft。KeyVault/vaults/accessPolicies/write | はい。 | はい。 | いいえ 


.2+| データ階層化のためのVNetサービスエンドポイントを有効にします | Microsoft.Network/virtualNetworks/subnets/write | はい。 | はい。 | いいえ 


| Microsoft.Network/routeTables/join/action | はい。 | はい。 | いいえ 


.4+| Azureで管理されるSnapshotを作成および管理します | Microsoft.Compute/snapshots/write | はい。 | はい。 | いいえ 


| Microsoft.Compute/snapshots/read | はい。 | はい。 | いいえ 


| Microsoft.Compute/snapshots/delete | いいえ | はい。 | はい。 


| Microsoft.Compute/disks/beginGetAccess/action | いいえ | はい。 | いいえ 


.2+| アベイラビリティセットを作成および管理します | Microsoft.Compute/availabilitySets/write | はい。 | いいえ | いいえ 


| Microsoft.Compute/availabilitySets/read | はい。 | いいえ | いいえ 


.2+| 市場からのプログラムによる導入を可能にします | "Microsoft.MarketplaceOrdering/offerTypes/publisher/offers/plans/agrees/read | はい。 | いいえ | いいえ 


| "Microsoft.MarketplaceOrdering/offerTypes/publisher/offers/plans/agrees/write | はい。 | はい。 | いいえ 


.9+| HAペアのロードバランサを管理します | Microsoft.Network/loadBalancers/read | はい。 | はい。 | いいえ 


| Microsoft.Network/loadBalancers/write | はい。 | いいえ | いいえ 


| Microsoft.Network/loadBalancers/delete | いいえ | はい。 | はい。 


| Microsoft.Network/loadBalancers/backendAddressPools/read | はい。 | いいえ | いいえ 


| Microsoft.Network/loadBalancers/backendAddressPools/join/action | はい。 | いいえ | いいえ 


| Microsoft.Network/loadBalancers/frontendIPConfigurations/read | はい。 | はい。 | いいえ 


| Microsoft.Network/loadBalancers/loadBalancingRules/read | はい。 | いいえ | いいえ 


| Microsoft.Network/loadBalancers/probes/read | はい。 | いいえ | いいえ 


| Microsoft.Network/loadBalancers/probes/join/action | はい。 | いいえ | いいえ 


| Azureディスク上のロックの管理を有効にします | Microsoft *。許可/ロック/* | はい。 | はい。 | いいえ 


.10+| サブネット外に接続がない場合は、HAペアのプライベートエンドポイントを有効にします | Microsoft.Network/privateEndpoints/write | はい。 | はい。 | いいえ 


| microsoft.Storage/storageAccounts/PrivateEndpointConnectionsApproval / action | はい。 | いいえ | いいえ 


| microsoft.Storage/storageAccounts/privateEndpointConnections/ read | はい。 | はい。 | はい。 


| Microsoft.Network/privateEndpoints/read | はい。 | はい。 | はい。 


| Microsoft.Network/privateDnsZones/write | はい。 | はい。 | いいえ 


| Microsoft.Network/privateDnsZones/virtualNetworkLinks/write | はい。 | はい。 | いいえ 


| Microsoft.Network/virtualNetworks/join/action | はい。 | はい。 | いいえ 


| Microsoft.Network/privateDnsZones/A/write | はい。 | はい。 | いいえ 


| Microsoft.Network/privateDnsZones/read | はい。 | はい。 | いいえ 


| Microsoft.Network/privateDnsZones/virtualNetworkLinks/read | はい。 | はい。 | いいえ 


| 基盤となる物理ハードウェアに応じて、一部のVM環境で必要です | microsoft.Resources/Deployments/operationStatuses /read | はい。 | はい。 | いいえ 


.2+| 導入に失敗した場合やリソースを削除した場合は、リソースグループからリソースを削除します | Microsoft.Network/privateEndpoints/delete | はい。 | はい。 | いいえ 


| Microsoft.Compute/availabilitySets/delete | はい。 | はい。 | いいえ 


.4+| APIを使用する際に、お客様が管理する暗号化キーの使用を有効にします | Microsoft.Compute/diskEncryptionSets/read | はい。 | はい。 | はい。 


| Microsoft.Compute/diskEncryptionSets/write | はい。 | はい。 | いいえ 


| microsoft.KeyVault/vaults/deploy/action | はい。 | いいえ | いいえ 


| Microsoft.Compute/diskEncryptionSets/delete | はい。 | はい。 | はい。 


.6+| HAペアのアプリケーションセキュリティグループを設定して、HAインターコネクトのNICとクラスタネットワークのNICを分離します | Microsoft.Network/applicationSecurityGroups/write | いいえ | はい。 | いいえ 


| Microsoft.Network/applicationSecurityGroups/read | いいえ | はい。 | いいえ 


| Microsoft.Network/applicationSecurityGroups/joinIpConfiguration/action | いいえ | はい。 | いいえ 


| Microsoft.Network/networkSecurityGroups/securityRules/write | はい。 | はい。 | いいえ 


| Microsoft.Network/applicationSecurityGroups/delete | いいえ | はい。 | はい。 


| Microsoft.Network/networkSecurityGroups/securityRules/delete | いいえ | はい。 | はい。 


.3+| Cloud Volumes ONTAP リソースに関連付けられたタグの読み取り、書き込み、および削除 | microsoft.Resources/tags/read | いいえ | はい。 | いいえ 


| microsoft.Resources/tags/write | はい。 | はい。 | いいえ 


| microsoft.Resources/tags/delete | はい。 | いいえ | いいえ 


| 作成時にストレージアカウントを暗号化 | microsoft.ManagedIdentity/userAssignedIdentities/assign/action | はい。 | はい。 | いいえ 
|===


=== エッジキャッシュ

BlueXPエッジキャッシングを使用する場合、コネクタは次のAPI要求を行います。

* Microsoft .Insights / Metrics / Read
* Microsoft.Compute/virtualMachines/extensions/write
* Microsoft.Compute/virtualMachines/extensions/read
* Microsoft.Compute/virtualMachines/extensions/delete
* Microsoft.Compute/virtualMachines/delete
* Microsoft.Network/networkInterfaces/delete
* Microsoft.Network/networkSecurityGroups/delete
* microsoft.Resources/Deployments/delete




=== Kubernetes

Connectorは、Azure Kubernetes Service（AKS）で実行されているクラスタを検出し管理するために次のAPI要求を実行します。

* Microsoft.Compute/virtualMachines/read
* microsoft.Resources/Subscriptions /locations /read
* microsoft.Resources/Subscriptions /operationresults/read
* microsoft.Resources/Subscriptions /resourceGroups/read
* microsoft.resources/Subscriptions /resourcegroups/resources/read
* Microsoft .ContainerService/managedClusters/read
* Microsoft .ContainerService/managedClusters/listClusterUserCredential/action




=== 修正

BlueXPの修正措置を使用すると、コネクタはAzureリソースのタグを管理するために次のAPI要求を行います。

* microsoft.resources/resources/read
* microsoft.Resources/Subscriptions /operationresults/read
* microsoft.Resources/Subscriptions /resourceGroups/read
* microsoft.resources/Subscriptions /resourcegroups/resources/read
* microsoft.Resources/tags/read
* microsoft.Resources/tags/write




=== 階層化

BlueXP階層化のセットアップ時に、コネクタは次のAPI要求を行います。

* microsoft.Storage/storageAccounts/listkeys/action
* microsoft.Resources/Subscriptions /resourceGroups/read
* microsoft.Resources/Subscriptions /locations /read


このコネクタは、次のAPI要求を日々の処理に送信します。

* microsoft.Storage/storageAccounts/blobServices/container/read
* Microsoft。Storage/storageAccounts/managementPolicies/read
* microsoft.StorageAccounts/managementPolicies/write
* microsoft.Storage/storageAccounts/read




== 変更ログ

権限が追加および削除されると、以下のセクションにそれらの権限が表示されます。



=== 2023年5月12日

次の権限はCloud Volumes ONTAP の管理に必要なため、JSONポリシーに追加されました。

* Microsoft.Compute/images/write
* Microsoft.Network/loadBalancers/frontendIPConfigurations/read


JSONポリシーから次の権限が削除されました。これらの権限は不要になりました。

* microsoft.Storage/storageAccounts/blobServices/container/write
* Microsoft.Network/publicIPAddresses/delete




=== 2023年3月23日

BlueXPの分類に「Microsoft.Storage/storageAccounts/delete」権限は不要になりました。

この権限はCloud Volumes ONTAP では引き続き必要です。



=== 2023年1月5日

JSONポリシーに次の権限が追加されました。

* microsoft.Storage/storageAccountSas/action
* Microsoft .Synapse/workspaces /privateEndpointConnectionsApproval / action
+
これらの権限はBlueXPのバックアップとリカバリに必要です。

* Microsoft.Network/loadBalancers/backendAddressPools/join/action
+
この権限はCloud Volumes ONTAP の導入に必要です。


