---
sidebar: sidebar 
permalink: reference-connector-default-config.html 
keywords: linux, user name, operating system, installation files, installation folder, folder, log, logs, service, mysql, packages, linux 
summary: コネクタのトラブルシューティングが必要な場合は、コネクタの設定を理解すると役立つことがあります。 
---
= コネクタのデフォルト設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
導入前にコネクタの詳細を確認したり、問題のトラブルシューティングが必要な場合に利用できます。



== インターネットアクセスを使用するデフォルト設定

次の構成の詳細は、BlueXPからコネクタを導入した場合、クラウドプロバイダのマーケットプレイスからコネクタを導入した場合、またはインターネットにアクセスできるオンプレミスのLinuxホストにコネクタを手動でインストールした場合に適用されます。



=== AWSの詳細

BlueXPまたはクラウドプロバイダのマーケットプレイスからコネクタを導入した場合は、次の点に注意してください。

* EC2インスタンスタイプはt3.xlargeです。
* イメージのオペレーティングシステムはRed Hat Enterprise Linux 7.6（HVM）です。
+
オペレーティングシステムには GUI は含まれていません。システムにアクセスするには、端末を使用する必要があります。

* EC2 Linuxインスタンスのユーザ名はec2-userです。
* デフォルトのシステムディスクは100GiBのgp2ディスクです。




=== Azureの詳細

BlueXPまたはクラウドプロバイダのマーケットプレイスからコネクタを導入した場合は、次の点に注意してください。

* VMタイプはDS3 v2です。
* イメージのオペレーティングシステムはCentOS 7.6です。
+
オペレーティングシステムには GUI は含まれていません。システムにアクセスするには、端末を使用する必要があります。

* デフォルトのシステムディスクは100GiBのPremium SSDディスクです。




=== Google Cloudの詳細

BlueXPまたはクラウドプロバイダのマーケットプレイスからコネクタを導入した場合は、次の点に注意してください。

* VMインスタンスがn2 -標準-4である。
* イメージのオペレーティングシステムはRed Hat Enterprise Linux 8.6です。
+
オペレーティングシステムには GUI は含まれていません。システムにアクセスするには、端末を使用する必要があります。

* デフォルトのシステムディスクは100GiBのSSD永続ディスクです。




=== インストールフォルダ

Connector インストールフォルダは、次の場所にあります。

/opt/application/netapp/cloudmanager です



=== ログファイル

ログファイルは次のフォルダに格納されます。

* /opt/application/netapp/cloudmanager/log を選択します
+
このフォルダのログには、 Connector イメージと Docker イメージの詳細が記録されます。

* /opt/application/NetApp/cloudmanager/docx_occm/data/log
+
このフォルダのログには、コネクタで実行されている クラウド サービス およびBlueXPサービスの詳細が表示されます。





=== コネクタサービス

* BlueXPサービスの名前はoccmです
* OCCM サービスは MySQL サービスに依存します。
+
MySQL サービスがダウンしている場合は、 OCCM サービスもダウンしています。





=== パッケージ

BlueXPでは、次のパッケージがまだインストールされていない場合、Linuxホストにインストールされます。

* 7 郵便番号
* AWSCLI
* Java
* Kubectl のように入力する
* MySQL
* Tridentctl
* プル
* 取得




=== ポート

このコネクタは Linux ホストで次のポートを使用します。

* HTTP アクセスの場合は 80
* 443 ： HTTPS アクセス用
* BlueXPデータベース用に3306
* 8080はBlueXP APIプロキシ
* Service Manager API の場合は 8666
* 8777 （ Health-Checker コンテナサービス API の場合）




== インターネットアクセスを使用しないデフォルトの設定

インターネットにアクセスできないオンプレミスの Linux ホストにコネクタを手動でインストールした場合、次の構成が適用されます。 link:task-install-connector-onprem-no-internet.html["このインストールオプションの詳細については、こちらをご覧ください"]。

* Connector インストールフォルダは、次の場所にあります。
+
/opt/application/NetApp/DS

* ログファイルは次のフォルダに格納されます。
+
/var/lib/docker /volumes /DS_occmdata/_data/log

+
このフォルダのログには、 Connector イメージと Docker イメージの詳細が記録されます。

* すべてのサービスが Docker コンテナ内で実行されています
+
サービスは、実行されている Docker ランタイムサービスに依存します

* このコネクタは Linux ホストで次のポートを使用します。
+
** HTTP アクセスの場合は 80
** 443 ： HTTPS アクセス用



