---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: SaaSレイヤで提供されるWebベースのBlueXPコンソールを使用すると、いくつかの管理タスクを実行する際に複数のエンドポイントに通信します。BlueXPコンソールにアクセスするコンピュータは、これらのエンドポイントに接続する必要があります。 
---
= BlueXP  コンソールのネットワークの準備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ログインしてWebベースのコンソールを使用すると、BlueXPは複数のエンドポイントに接続して、ユーザーが開始したアクションを実行します。コンソールにアクセスするコンピューターは、これらのエンドポイントに接続している必要があります。

これらのエンドポイントには、次の2つのシナリオがあります。

* ユーザーのコンピュータから、  https://console.bluexp.netapp.com["WebベースのBlueXPコンソール"^] SaaS (サービスとしてのソフトウェア) として利用できます。
* ユーザーのコンピュータからWebブラウザを開いて、コネクタホストのIPアドレスを入力し、ログインしてコネクタを設定します。これらの手順は、コネクタを手動で取り付ける場合に必要です。


[cols="2*"]
|===
| エンドポイント | 目的 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | これは、Web ベースのコンソールを使用するために Web ブラウザに入力するエンドポイントです。 


| \https://api.bluexp.netapp.com | Web ベースのコンソールは、このエンドポイントに接続して API と対話し、承認、ライセンス、サブスクリプション、資格情報、通知などに関連するアクションを実行します。 


| \https://aiq.netapp.com | デジタルアドバイザーにアクセスするために必要です。 


 a| 
AWS サービス（ amazonaws.com ）：

* クラウド形成
* 柔軟なコンピューティングクラウド（ EC2 ）
* キー管理サービス（ KMS ）
* セキュリティトークンサービス（ STS ）
* シンプルなストレージサービス（ S3 ）

| BlueXPからAWSにコネクタを導入する場合に必要です。正確なエンドポイントは、コネクタをデプロイするリージョンによって異なります。  https://docs.aws.amazon.com/general/latest/gr/rande.html["詳細については、AWS のドキュメントを参照してください。"]提案：  https://docs.aws.amazon.com/general/latest/gr/rande.html["詳細については、AWS のドキュメントを参照してください。"] 


| \https://management.azure.com

\https://login.microsoftonline.com | ほとんどのAzureリージョンでBlueXPからコネクタを導入する場合に必要です。 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Azureドイツ地域でBlueXPからコネクタを導入する場合に必要です。 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Azure US GovリージョンでBlueXPからコネクタを導入する場合に必要です。 


| \https://www.googleapis.com | Google CloudでBlueXPからConnectorを展開するために必要です。 


| \https://signin.b2c.netapp.com | NetApp Support Site (NSS)の資格情報を更新するか、新しいNSS資格情報をBlueXPに追加する必要があります。 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | Webブラウザはこれらのエンドポイントに接続して、BlueXPを介した集中型ユーザ認証を行います。 


| \https://widget.intercom.io | NetApp サポートと会話できる製品内チャットです。 
|===
コネクタが日常業務で使用するエンドポイントへのアウトバウンドインターネットアクセスを確保していることを確認してください。これらのエンドポイントのリストについては、次のセクションのリンクをご覧ください。

.関連情報
* コネクタのネットワークを準備します
+
** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking["AWSネットワークをセットアップする"]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking["Azureネットワークをセットアップする"]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking["Google Cloudネットワークをセットアップする"]
** link:task-install-connector-on-prem.html#step-3-set-up-networking["オンプレミスネットワークをセットアップする"]


* BlueXPサービスのネットワークを準備
+
各BlueXPサービスのドキュメントを参照してください。

+
https://docs.netapp.com/us-en/bluexp-family/["BlueXPのマニュアル"^]


