---
sidebar: sidebar 
permalink: reference-connector-operating-system-changes.html 
keywords: connector, operating systems, connector operating systems, os support, supported operating systems, rhel 8, rhel 9, red hat, docker, podman 
summary: 特定のLinuxオペレーティングシステムでコネクタのサポートを追加または削除する際に、このサポートが既存のコネクタの展開にどのように影響するかについて質問がある場合があります。 
---
= サポートされるLinuxオペレーティングシステムに対する変更
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
特定のLinuxオペレーティングシステムでコネクタのサポートを追加または削除する際に、このサポートが既存のコネクタの展開にどのように影響するかについて質問がある場合があります。



== サポートされているオペレーティングシステム

BlueXP Connectorは次のLinuxオペレーティングシステムでサポートされます。

[role="tabbed-block"]
====
.標準モード
--
手動インストール::
+
--
* Ubuntu 22.04 LTS
* Red Hat Enterprise Linux の場合
+
** 8.6～8.10
** 9.1から9.3




--
BlueXPからの導入:: Ubuntu 22.04 LTS
AWS Marketplaceからの導入:: Ubuntu 22.04 LTS
Azure Marketplaceからの導入:: Ubuntu 22.04 LTS


--
.制限モード
--
手動インストール::
+
--
* Ubuntu 22.04 LTS
* Red Hat Enterprise Linux の場合
+
** 8.6～8.10
** 9.1から9.3




--
AWS Marketplaceからの導入:: Ubuntu 22.04 LTS
Azure Marketplaceからの導入:: Ubuntu 22.04 LTS


--
.プライベートモード
--
手動インストール::
+
--
* Ubuntu 22.04 LTS
* Red Hat Enterprise Linux の場合
+
** 8.6～8.10
** 9.1から9.3




--


--
====


== RHEL 8および9のサポート

RHEL 8および9のサポートについては、次の点に注意してください。

制限::
+
--
* コネクタがRHEL 8または9ホストにインストールされている場合、BlueXPのバックアップとリカバリには、単一ファイルのリストアとランサムウェアスキャンに関する制限があります。詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-limitations.html["BlueXPのバックアップとリカバリに関する既知の制限事項"^]
* BlueXPの分類は、オンプレミスのRHEL 8または9ホストにコネクタをインストールする場合にサポートされます。RHEL 8または9ホストがAWS、Azure、Google Cloudにある場合はサポートされません。


--
コンテナオーケストレーションツール:: RHEL 8または9ホストにコネクタをインストールする場合は、コンテナオーケストレーションツールとしてPodmanが必要です。Docker EngineはRHEL 8および9ではサポートされていません。
導入モード:: RHEL 8および9は、BlueXPを標準モード、制限モード、およびプライベートモードで使用している場合にサポートされます。
新規の手動インストールのみ:: RHEL 8および9は、オンプレミスまたはクラウドで実行されているホストにコネクタを手動でインストールする場合、_new_connectorのインストールでサポートされます。
RHELノアツフクレエト:: RHEL 7ホストで既存のコネクタを実行している場合、RHEL 7オペレーティングシステムをRHEL 8または9にアップグレードすることはできません。 <<RHEL 7またはCentOS 7の既存のコネクタ,RHEL 7またはCentOS 7の既存のコネクタに関する詳細情報>>。




== RHEL 7およびCentOS 7のサポート終了

2024年6月30日、RHEL 7はメンテナンス終了（EOM）に達し、CentOS 7はサポート終了（EOL）に達しました。NetAppは2024年6月30日にこれらのLinuxディストリビューションでのコネクタのサポートを停止しました。

https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/rhel-7-end-of-maintenance["Red Hat: Red Hat Enterprise Linux 7のメンテナンス終了について知っておくべきこと"^]



=== RHEL 7またはCentOS 7の既存のコネクタ

RHEL 7またはCentOS 7で既存のコネクタを実行している場合、オペレーティングシステムのRHEL 8または9へのアップグレードや変換はサポートされていません。代わりにRHEL 8または9ホストでコネクタの実行を開始するには、次の手順を実行する必要があります。

. RHEL 8または9ホストをセットアップします。
. Podmanをインストールします。
. _new_connectorのインストールを実行します。
. 古いコネクタが管理していた作業環境を検出するようにコネクタを設定します。




== Ubuntu 22.04 LTSの継続サポート

このコネクタはUbuntu 22.04 LTSで引き続きサポートされており、BlueXPや市場向けのデフォルトのオペレーティングシステムです。

このオペレーティングシステムにはDocker Engineが必要です。Podmanはサポートされていません。



== 関連リンク



=== RHEL 8および9の使用方法

ホスト要件、Podman要件、およびPodmanとコネクタのインストール手順の詳細については、次のページを参照してください。

[role="tabbed-block"]
====
.標準モード
--
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["コネクタをオンプレミスにインストールしてセットアップします"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-manual.html["AWSにコネクタを手動でインストールする"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure-manual.html["Azureへのコネクタの手動インストール"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-google-manual.html["Google Cloudにコネクタを手動でインストールする"]


--
.制限モード
--
https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-restricted-mode.html["制限モードでの展開を準備します"]

--
.プライベートモード
--
https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html["プライベートモードでの導入を準備します"]

--
====


=== 作業環境を再検出する方法

新しいコネクタの導入後に作業環境を再検出するには、次のページを参照してください。

* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-adding-systems.html["既存のCloud Volumes ONTAP システムをBlueXPに追加します"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["オンプレミスのONTAP クラスタを検出"^]
* https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-creating-fsx-working-environment.html["FSx for ONTAP作業環境の作成と検出"^]
* https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-create-working-env.html["Azure NetApp Files 作業環境を作成します"^]
* https://docs.netapp.com/us-en/bluexp-e-series/task-discover-e-series.html["Eシリーズシステムの検出"^]
* https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["StorageGRID システムを検出"^]

