---
sidebar: sidebar 
permalink: task-install-connector-google-manual.html 
keywords: install connector, google cloud connector installation, google cloud connector, install connector in google cloud, bluexp, gcloud, manual install, create connector, gcp installation, gcp connector 
summary: 独自のLinuxホストにコネクタを手動でインストールするには、ホストの要件を確認し、ネットワークをセットアップし、Google Cloudの権限を準備し、Google Cloud APIを有効にしてから、コネクタをインストールし、準備した権限を指定する必要があります。 
---
= Google Cloudにコネクタを手動でインストールする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloudで実行されているLinuxホストには、q Connectorを手動でインストールできます。独自のLinuxホストにコネクタを手動でインストールするには、ホストの要件を確認し、ネットワークをセットアップし、Google Cloudの権限を準備し、APIを有効にしてから、コネクタをインストールし、準備した権限を指定する必要があります。

.作業を開始する前に
* が必要ですlink:concept-connectors.html["コネクタの概要"]。
* 確認が必要です link:reference-limitations.html["コネクタの制限"]。




== 手順1：ホスト要件を確認する

コネクタソフトウェアは、特定のオペレーティングシステム要件、 RAM 要件、ポート要件などを満たすホストで実行する必要があります。


NOTE: コネクタは19000～19200のUIDとGIDの範囲を予約します。この範囲は固定されており、変更できません。ホスト上のサードパーティ製ソフトウェアがこの範囲内のUIDまたはGIDを使用している場合、コネクタのインストールは失敗します。NetAppでは、競合を避けるため、サードパーティ製ソフトウェアがインストールされていないホストを使用することを推奨します。

専用ホスト:: 他のアプリケーションと共有しているホストでは、このコネクタはサポートされていません。専用のホストである必要があります。
+
--
ホストは、次のサイズ要件を満たす任意のアーキテクチャで構成できます。

* CPU：8コアまたは8 vCPU
* RAM ： 32GB


--
ハイパーバイザー:: サポート対象のオペレーティングシステムの実行が認定されているベアメタルまたはホスト型ハイパーバイザーが必要です。
[[podman-versions]]オペレーティングシステムとコンテナの要件:: BlueXP  は、標準モードまたは制限モードでBlueXP  を使用する場合、次のオペレーティングシステムでコネクタをサポートします。コネクタをインストールする前に、コンテナオーケストレーションツールが必要です。
+
--
[cols="2a,2a,2a,2a,2a"]
|===
| オペレーティングシステム | サポートされるOSバージョン | サポートされるコネクタのバージョン | 必要なコンテナツール | SELinux 


 a| 
Red Hat Enterprise Linux の場合
 a| 
9.1～9.4

8.6～8.10

7.9
 a| 
3.9.40以降（BlueXP  を標準モードまたは制限モードで使用）
 a| 
Podmanバージョン4.6.1または4.9.4

<<podman-configuration,Podman設定要件の表示>>です。
 a| 
強制モードまたは許可モードでサポート^1^



 a| 
Ubuntu
 a| 
24.04 LTS
 a| 
3.9.45以降（BlueXP  を標準モードまたは制限モードで使用）
 a| 
Docker エンジン 23.06 から 28.0.0。
 a| 
サポート対象外



 a| 
22.04 LTS
 a| 
3.9.29以降
 a| 
Docker エンジン 23.0.6 から 28.0.0。
 a| 
サポート対象外

|===
注：

. Cloud Volumes ONTAPシステムの管理は、オペレーティングシステムでSELinuxが有効になっているコネクタではサポートされていません。
. Connector は、これらのオペレーティングシステムの英語版でサポートされています。
. RHELの場合は、ホストをRed Hat Subscription Managementに登録する必要があります。登録されていない場合、ホストはコネクタのインストール時に必要なサードパーティ製ソフトウェアを更新するためのリポジトリにアクセスできません。


--
Google Cloudマシンのタイプ:: 上記の CPU と RAM の要件を満たすインスタンスタイプ。n2-standard-8を推奨します。
+
--
このコネクタは、OSがサポートされているVMインスタンス上のGoogle Cloudでサポートされます https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["シールドVM機能"^]

--
/opt のディスクスペース:: 100GiB のスペースが使用可能である必要があります
+
--
BlueXP  は、を使用して `/opt`ディレクトリとその内容をインストールし `/opt/application/netapp`ます。

--
/var のディスク領域:: 20GiB のスペースが必要です
+
--
このスペースはBlueXPの `/var` DockerやPodmanは、このディレクトリ内にコンテナを作成するように設計されているためです。具体的には、 `/var/lib/containers/storage` ディレクトリ。このスペースでは外部マウントやシンボリックリンクは使用できません。

--




== 手順2：PodmanまたはDocker Engineをインストールする

オペレーティングシステムに応じて、コネクタをインストールする前にPodmanまたはDocker Engineのいずれかが必要です。

* Red Hat Enterprise Linux 8および9にはPodmanが必要です。
+
<<podman-versions,BlueXP  がサポートするPodmanバージョンを表示する>>です。

* UbuntuにはDocker Engineが必要です。
+
<<podman-versions,BlueXP  がサポートするDocker Engineのバージョンを表示する>>です。



.手順
[role="tabbed-block"]
====
.ポドマン
--
次の手順に従って、Podmanをインストールし、次の要件を満たすように設定します。

* podman.socket サービスを有効にして起動します
* python3の設置
* podman-compose パッケージ バージョン 1.0.6 をインストールします。
* podman-composeをPATH環境変数に追加する



NOTE: Podmanを使用する場合は、コネクタをインストールした後、ホストのDNSポートとの競合を避けるため、aardvark-dnsサービスのポート（デフォルト：53）を調整してください。ポートの設定方法については、手順に従ってください。

.手順
. podman-dockerパッケージがホストにインストールされている場合は削除します。
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Podmanをインストールします。
+
PodmanはRed Hat Enterprise Linuxの公式リポジトリから入手できます。

+
Red Hat Enterprise Linux 9の場合：

+
[source, cli]
----
sudo dnf install podman-2:<version>
----
+
<version>は、インストールするPodmanのサポートされているバージョンです。<<podman-versions,BlueXP  がサポートするPodmanバージョンを表示する>>です。

+
Red Hat Enterprise Linux 8の場合：

+
[source, cli]
----
sudo dnf install podman-3:<version>
----
+
<version>は、インストールするPodmanのサポートされているバージョンです。<<podman-versions,BlueXP  がサポートするPodmanバージョンを表示する>>です。

. podman.socketサービスを有効にして開始します。
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. python3をインストールします。
+
[source, cli]
----
sudo dnf install python3
----
. EPELリポジトリパッケージがシステムにない場合はインストールします。
+
podman-composeはExtra Packages for Enterprise Linux（EPEL）リポジトリから利用できるため、この手順が必要です。

+
Red Hat Enterprise Linux 9の場合：

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----
+
Red Hat Enterprise Linux 8の場合：

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----
. podman-composeパッケージ1.0.6をインストールします。
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: を使用する `dnf install` コマンドは、PATH環境変数にpodman-composeを追加するための要件を満たしています。インストールコマンドを実行すると、/usr/binにpodman-composeが追加されます。 `secure_path` オプションを指定します。



--
.Docker Engine の略
--
Dockerのドキュメントに従ってDocker Engineをインストールします。

.手順
. https://docs.docker.com/engine/install/["Dockerからインストール手順を表示"^]
+
特定のバージョンのDocker Engineをインストールするには、必ず次の手順に従ってください。最新バージョンをインストールすると、BlueXPでサポートされていないバージョンのDockerがインストールされます。

. Dockerが有効で実行されていることを確認します。
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====


== 手順3：ネットワークをセットアップする

コネクタがハイブリッドクラウド環境内のリソースとプロセスを管理できるように、ネットワークをセットアップします。たとえば、ターゲットネットワークへの接続が可能で、アウトバウンドのインターネットアクセスが利用可能であることを確認する必要があります。

ターゲットネットワークへの接続:: コネクタには、作業環境を作成および管理する予定の場所へのネットワーク接続が必要です。たとえば、オンプレミス環境にCloud Volumes ONTAPシステムやストレージシステムを作成するネットワークなどです。


アウトバウンドインターネットアクセス:: コネクタを展開するネットワークの場所には、特定のエンドポイントに接続するためのアウトバウンドインターネット接続が必要です。


BlueXP  Webベースのコンソールを使用しているときにコンピュータから接続されるエンドポイント:: WebブラウザからBlueXP  コンソールにアクセスするコンピュータには、複数のエンドポイントに接続できる必要があります。BlueXP  コンソールを使用してコネクタを設定し、BlueXP  を日常的に使用する必要があります。
+
--
link:reference-networking-saas-console.html["BlueXP  コンソールのネットワークの準備"]です。

--


手動インストール中にエンドポイントに接続しました:: 独自のLinuxホストにコネクタを手動でインストールする場合、コネクタのインストーラは、インストールプロセス中に次のURLにアクセスする必要があります。
+
--
* \https://mysupport.netapp.com
* \ https://signin.b2c .CNAME.com NetApp（このエンドポイントは、\ https://mysupport .CNAME.comのCNAME URL NetAppです）
* \https://cloudmanager.cloud.netapp.com/tenancy
* \https://stream.cloudmanager.cloud.netapp.com
* \https://production-artifacts.cloudmanager.cloud.netapp.com
* イメージを取得するには、インストーラが次の2つのエンドポイントセットのいずれかにアクセスする必要があります。
+
** オプション1（推奨）：
+
*** \https://bluexpinfraprod.eastus2.data.azurecr.io
*** \https://bluexpinfraprod.azurecr.io


** オプション2：
+
*** \https://*.blob.core.windows.net
*** \https://cloudmanagerinfraprod.azurecr.io




+
オプション1にリストされているエンドポイントは、より安全であるため推奨されます。オプション1にリストされているエンドポイントを許可し、オプション2にリストされているエンドポイントを拒否するようにファイアウォールを設定することをお勧めします。これらのエンドポイントについて、次の点に注意してください。

+
** オプション1にリストされているエンドポイントは、コネクタの3.9.47リリース以降でサポートされています。以前のリリースのコネクタとの下位互換性はありません。
** コネクタは、最初にオプション2にリストされているエンドポイントに接続します。これらのエンドポイントにアクセスできない場合、コネクタはオプション1にリストされているエンドポイントに自動的に接続します。
** コネクタをBlueXP  のバックアップおよびリカバリまたはBlueXP  ランサムウェア対策で使用する場合、オプション1のエンドポイントはサポートされません。この場合、オプション1にリストされているエンドポイントを禁止し、オプション2にリストされているエンドポイントを許可することができます。




ホストは、インストール中にオペレーティングシステムパッケージの更新を試みる可能性があります。ホストは、これらの OS パッケージの別のミラーリングサイトにアクセスできます。

--


コネクタから接続されたエンドポイント:: このコネクタは、パブリッククラウド環境内のリソースとプロセスを日常的に管理するために、次のエンドポイントに接続するためのアウトバウンドインターネットアクセスを必要とします。
+
--
次に示すエンドポイントはすべてCNAMEエントリであることに注意してください。

[cols="2a,1a"]
|===
| エンドポイント | 目的 


 a| 
\https://www.googleapis.com/compute/v1/
\https://compute.googleapis.com/compute/v1
\https://cloudresourcemanager.googleapis.com/v1/projects
\https://www.googleapis.com/compute/beta
\https://storage.googleapis.com/storage/v1
\https://www.googleapis.com/storage/v1
\https://iam.googleapis.com/v1
\https://cloudkms.googleapis.com/v1
\https://www.googleapis.com/deploymentmanager/v2/projects
 a| 
Google Cloudでリソースを管理します。



 a| 
\ https://support.netapp.com
https://mysupport.netapp.com をご覧ください
 a| 
ライセンス情報を取得し、ネットアップサポートに AutoSupport メッセージを送信するため。



 a| 
\https://\*.api。BlueXP 。NetApp。com\https://api。BlueXP 。NetApp。com\https://*.cloudmanager.cloud。NetApp。com\https://cloudmanager.cloud。NetApp。com\https：// NetApp -cloud-account.auth0.com
 a| 
BlueXPでSaaSの機能とサービスを提供するため。



 a| 
2つのエンドポイントセットから選択します。

* オプション1（推奨）^1^
+
\https://bluexpinfraprod.eastus2.data.azurecr.io \https://bluexpinfraprod.azurecr.io

* オプション2
+
\https://*.blob.core.windows.net \https://cloudmanagerinfraprod.azurecr.io


 a| 
コネクタのアップグレード用のイメージを取得します。

|===
^1^オプション1にリストされているエンドポイントは、より安全であるため推奨されます。オプション1にリストされているエンドポイントを許可し、オプション2にリストされているエンドポイントを拒否するようにファイアウォールを設定することをお勧めします。これらのエンドポイントについて、次の点に注意してください。

* オプション1にリストされているエンドポイントは、コネクタの3.9.47リリース以降でサポートされています。以前のリリースのコネクタとの下位互換性はありません。
* コネクタは、最初にオプション2にリストされているエンドポイントに接続します。これらのエンドポイントにアクセスできない場合、コネクタはオプション1にリストされているエンドポイントに自動的に接続します。
* コネクタをBlueXP  のバックアップおよびリカバリまたはBlueXP  ランサムウェア対策で使用する場合、オプション1のエンドポイントはサポートされません。この場合、オプション1にリストされているエンドポイントを禁止し、オプション2にリストされているエンドポイントを許可することができます。


--


プロキシサーバ:: すべての送信インターネットトラフィック用にプロキシサーバーを展開する必要がある場合は、HTTPまたはHTTPSプロキシに関する次の情報を取得します。この情報は、インストール時に入力する必要があります。BlueXPでは透過型プロキシサーバはサポートされません。
+
--
* IP アドレス
* クレデンシャル
* HTTPS証明書


--


ポート:: コネクタを起動するか、コネクタがCloud Volumes ONTAPからNetAppサポートにAutoSupportメッセージを送信するためのプロキシとして使用されている場合を除き、コネクタへの受信トラフィックはありません。
+
--
* HTTP （ 80 ）と HTTPS （ 443 ）はローカル UI へのアクセスを提供しますが、これはまれに使用されます。
* SSH （ 22 ）は、トラブルシューティングのためにホストに接続する必要がある場合にのみ必要です。
* アウトバウンドインターネット接続を使用できないサブネットにCloud Volumes ONTAP システムを導入する場合は、ポート3128経由のインバウンド接続が必要です。
+
Cloud Volumes ONTAPシステムでAutoSupportメッセージを送信するためのアウトバウンドインターネット接続が確立されていない場合は、コネクタに付属のプロキシサーバを使用するように自動的に設定されます。唯一の要件は、コネクタのセキュリティグループがポート3128を介したインバウンド接続を許可することです。コネクタを展開した後、このポートを開く必要があります。



--


NTPを有効にする:: BlueXP分類を使用して企業データソースをスキャンする場合は、システム間で時刻が同期されるように、BlueXP ConnectorシステムとBlueXP分類システムの両方でネットワークタイムプロトコル（NTP）サービスを有効にする必要があります。 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXPの分類の詳細については、こちらをご覧ください"^]




== 手順4：コネクタの権限を設定する

Google Cloudでリソースを管理するためにBlueXPで必要な権限をコネクタに付与するには、Google Cloudサービスアカウントが必要です。コネクタを作成するときは、このサービスアカウントをコネクタVMに関連付ける必要があります。

以降のリリースで新しい権限が追加された場合は、カスタムロールを更新する必要があります。新しい権限が必要な場合は、リリースノートに記載されます。

.手順
. Google Cloudでカスタムロールを作成します。
+
.. の内容を含むYAMLファイルを作成します link:reference-permissions-gcp.html["コネクタのサービスアカウント権限"]。
.. Google CloudからCloud Shellをアクティブ化します。
.. 必要な権限を含むYAMLファイルをアップロードします。
.. を使用して、カスタムロールを作成します `gcloud iam roles create` コマンドを実行します
+
次の例では、プロジェクトレベルで「Connector」という名前のロールを作成します。

+
`gcloud iam roles create connector --project=myproject --file=connector.yaml`

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloudのドキュメント：カスタムロールの作成と管理"^]



. Google Cloudでサービスアカウントを作成し、ロールをサービスアカウントに割り当てます。
+
.. IAMおよび管理サービスから、*サービスアカウント>サービスアカウントの作成*を選択します。
.. サービスアカウントの詳細を入力し、*作成して続行*を選択します。
.. 作成したロールを選択します。
.. 残りの手順を完了してロールを作成します。
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Google Cloudドキュメント：サービスアカウントの作成"^]



. Cloud Volumes ONTAP システムを、Connectorが存在するプロジェクトとは異なるプロジェクトに導入する場合は、Connectorのサービスアカウントにこれらのプロジェクトへのアクセスを提供する必要があります。
+
たとえば、コネクタがプロジェクト1にあり、プロジェクト2でCloud Volumes ONTAP システムを作成するとします。プロジェクト2のサービスアカウントへのアクセス権を付与する必要があります。

+
.. IAMと管理サービスで、Cloud Volumes ONTAPシステムを作成するGoogle Cloudプロジェクトを選択します。
.. [* iAM*（* IAM）]ページで、[*アクセスを許可（Grant Access）]を選択し、必要な詳細を入力します。
+
*** コネクタのサービスアカウントのEメールを入力します。
*** コネクタのカスタムロールを選択します。
*** [ 保存（ Save ） ] を選択します。




+
詳細については、を参照してください https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Google Cloudのドキュメント"^]



.結果
Connector VMのサービスアカウントが設定されます。



== 手順5：共有VPC権限を設定する

共有VPCを使用してサービスプロジェクトにリソースを導入する場合は、権限を準備する必要があります。

IAM の設定が完了したら、この表を参考にして権限の表を環境に反映させる必要があります。

.共有VPC権限の表示
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| ID | 作成者 | でホストされています | サービスプロジェクトの権限 | ホストプロジェクトの権限 | 目的 


| コネクタを展開するためのGoogleアカウント | カスタム | サービスプロジェクト  a| 
link:task-install-connector-google-bluexp-gcloud.html#step-2-set-up-permissions-to-create-the-connector["コネクタ展開ポリシー"]
 a| 
compute.networkUser
| サービスプロジェクトへのコネクタの配置 


| Connectorサービスアカウント | カスタム | サービスプロジェクト  a| 
link:reference-permissions-gcp.html["コネクタサービスアカウントポリシー"]
| compute.networkUser

deploymentmanager. editor | サービスプロジェクトへの Cloud Volumes ONTAP とサービスの導入と保守 


| Cloud Volumes ONTAP サービスアカウント | カスタム | サービスプロジェクト | storagec.admin

メンバー：BlueXPサービスアカウントをserviceAccount.userとして登録します | 該当なし | （オプション）データ階層化とBlueXPのバックアップとリカバリに使用します 


| Google API サービスエージェント | Google Cloud | サービスプロジェクト  a| 
（デフォルト） Editor
 a| 
compute.networkUser
| 導入に代わってGoogle Cloud APIと対話します。BlueXPが共有ネットワークを使用できるようにします 


| Google Compute Engine のデフォルトのサービスアカウント | Google Cloud | サービスプロジェクト  a| 
（デフォルト） Editor
 a| 
compute.networkUser
| 導入に代わってGoogle Cloudインスタンスとコンピューティングインフラストラクチャを導入します。BlueXPが共有ネットワークを使用できるようにします 
|===
注：

. deploymentmanager. editorは、ファイアウォール規則を配備に渡していない場合にのみホストプロジェクトで必要です。BlueXPで作成することを選択している場合にのみ必要です。ルールが指定されていない場合、ホストプロジェクトにVPC0ファイアウォールルールが含まれているデプロイメントがBlueXPによって作成されます。
. ファイアウォールの作成とfirewall.deleteは、ファイアウォールルールを配布に渡しておらず、BlueXPで作成することを選択している場合にのみ必要です。これらの権限はBlueXPアカウント.yamlファイルにあります。共有 VPC を使用して HA ペアを導入する場合は、これらの権限を使用して VPC1 、 2 、および 3 のファイアウォールルールが作成されます。他のすべての展開では、これらの権限は VPC0 のルールの作成にも使用されます。
. データ階層化の場合、階層化サービスアカウントは、プロジェクトレベルだけでなく、サービスアカウントに対して serviceAccount.user ロールを持つ必要があります。現在、プロジェクトレベルで serviceAccount.user を割り当てている場合、 getIAMPolicy でサービスアカウントを照会しても権限は表示されません。


====


== ステップ6：Google Cloud APIを有効にする

Cloud Volumes ONTAPシステムをGoogle Cloudに導入する前に、いくつかのGoogle Cloud APIを有効にする必要があります。

.ステップ
. プロジェクトで次のGoogle Cloud APIを有効にします。
+
** Cloud Deployment Manager V2 API
** クラウドロギング API
** Cloud Resource Manager API の略
** Compute Engine API
** ID およびアクセス管理（ IAM ） API
** Cloud Key Management Service（KMS）APIの略
+
（お客様が管理する暗号化キー（CMEK）でBlueXPのバックアップとリカバリを使用する場合にのみ必要）





https://cloud.google.com/apis/docs/getting-started#enabling_apis["Google Cloudドキュメント：APIの有効化"^]



== 手順7：コネクタを取り付ける

前提条件が完了したら、ソフトウェアを自分のLinuxホストに手動でインストールできます。

.作業を開始する前に
次の情報が必要です。

* コネクタをインストールするためのroot権限。
* コネクタからのインターネットアクセスにプロキシが必要な場合は、プロキシサーバに関する詳細。
+
インストール後にプロキシサーバを設定することもできますが、その場合はコネクタを再起動する必要があります。

+
BlueXPでは透過型プロキシサーバはサポートされません。

* プロキシサーバがHTTPSを使用している場合、またはプロキシが代行受信プロキシの場合は、CA署名証明書。


.このタスクについて
NetApp Support Siteで入手できるインストーラは、それよりも古いバージョンの場合があります。インストール後、新しいバージョンが利用可能になると、コネクタは自動的に更新されます。

.手順
. ホストに_http_proxy_or_https_proxy_system変数が設定されている場合は、削除します。
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
これらのシステム変数を削除しないと、インストールは失敗します。

. からConnectorソフトウェアをダウンロードします https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp Support Site"^]をクリックし、 Linux ホストにコピーします。
+
ネットワークまたはクラウドで使用するための「オンライン」コネクタインストーラをダウンロードする必要があります。コネクタには別の「オフライン」インストーラが用意されていますが、プライベートモード展開でのみサポートされています。

. スクリプトを実行する権限を割り当てます。
+
[source, cli]
----
chmod +x BlueXP-Connector-Cloud-<version>
----
+
<version> は、ダウンロードしたコネクタのバージョンです。

. インストールスクリプトを実行します。
+
[source, cli]
----
 ./BlueXP-Connector-Cloud-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
--proxyパラメータと--cacert.pemパラメータはオプションです。プロキシサーバを使用している場合は、次のようにパラメータを入力する必要があります。プロキシに関する情報の入力を求めるプロンプトは表示されません。

+
次に、両方のオプションパラメータを使用したコマンドの例を示します。

+
[source, cli]
----
 ./BlueXP-Connector-Cloud-v3.9.40--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxyは、次のいずれかの形式を使用してHTTPまたはHTTPSプロキシサーバを使用するようにコネクタを設定します。

+
** \http://address:port
** \http://user-name:password@address:port
** \http://domain-name%92user-name:password@address:port
** \https://address:port
** \https://user-name:password@address:port
** \https://domain-name%92user-name:password@address:port
+
次の点に注意してください。

+
*** ユーザには、ローカルユーザまたはドメインユーザを指定できます。
*** ドメインユーザの場合は、上に示すように、\にASCIIコードを使用する必要があります。
*** BlueXPでは、@文字を含むユーザ名やパスワードはサポートされていません。
*** パスワードに次の特殊文字が含まれている場合は、その特殊文字の前にバックスラッシュ（&または！）を付けてエスケープする必要があります。
+
例：

+
\http://bxpproxyuser:netapp1\!@address:3128





+
--cacertsは、コネクタとプロキシサーバ間のHTTPSアクセスに使用するCA署名証明書を指定しています。このパラメータは、HTTPSプロキシサーバを指定する場合、または代行受信プロキシを指定する場合にのみ必要です。

. Podman を使用した場合は、aardvark-dns ポートを調整する必要があります。
+
.. BlueXP Connector 仮想マシンに SSH で接続します。
.. podman _/usr/share/containers/containers.conf_ ファイルを開き、Aardvark DNS サービスに選択したポートを変更します。例えば、54 に変更します。
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. コネクタ仮想マシンを再起動します。


. インストールが完了するまで待ちます。
+
プロキシサーバを指定した場合は、インストールの終了時にConnectorサービス（occm）が2回再起動されます。

. Connector 仮想マシンに接続されているホストから Web ブラウザを開き、次の URL を入力します。
+
https://_ipaddress_[]

. ログイン後、コネクタを設定します。
+
.. コネクタに関連付けるBlueXP  組織を指定します。
.. システムの名前を入力します。
.. *では、セキュリティ保護された環境で実行していますか？*制限モードを無効にしたままにします。
+
標準モードでBlueXPを使用する手順について説明しているため、制限モードは無効にしておく必要があります。セキュアな環境でBlueXPバックエンドサービスからこのアカウントを切断する場合にのみ、制限モードを有効にしてください。その場合は、 link:task-quick-start-restricted-mode.html["制限モードでBlueXPの使用を開始するには、次の手順に従います"]。

.. [* Let's start]*を選択します。




コネクタを作成したのと同じGoogle CloudアカウントにGoogle Cloud Storageバケットがある場合は、BlueXPキャンバスにGoogle Cloud Storageの作業環境が自動的に表示されます。 https://docs.netapp.com/us-en/bluexp-google-cloud-storage/index.html["BlueXPからGoogle Cloud Storageを管理する方法をご確認ください"^]



== 手順8：BlueXPに権限を付与する

以前に設定したGoogle Cloud権限をBlueXPに付与する必要があります。権限を付与することで、BlueXPでGoogle Cloudのデータとストレージインフラを管理できるようになります。

.手順
. Google Cloudポータルに移動し、コネクタVMインスタンスにサービスアカウントを割り当てます。
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["Google Cloudドキュメント：インスタンスのサービスアカウントとアクセス範囲の変更"^]

. 他のGoogle Cloudプロジェクトのリソースを管理する場合は、BlueXPロールを持つサービスアカウントをそのプロジェクトに追加してアクセスを許可します。プロジェクトごとにこの手順を繰り返す必要があります。


.結果
BlueXPに、Google Cloudでユーザに代わって操作を実行するために必要な権限が付与されました。
