---
sidebar: sidebar 
permalink: task-installing-linux.html 
keywords: install connector, manually install connector, install connector software, installation, installing, linux, installer, software, on prem, on-prem, silent, configurations, ec2, vm, ports, ram, operating system, os, host, requirement, requirements, hypervisor, disk, space, mysql, centos, rhel, red hat, cpu, disk space 
summary: コネクタを作成する最も一般的な方法は、BlueXPから直接、またはクラウドプロバイダの市場から取得することです。ただし、ネットワークまたはクラウドにある既存の Linux ホストに Connector ソフトウェアをダウンロードしてインストールすることもできます。以下の手順は、インターネットにアクセスできるホストに固有の手順です。 
---
= インターネットにアクセスできる既存の Linux ホストにコネクタをインストールします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コネクタを作成する最も一般的な方法は、BlueXPから直接、またはクラウドプロバイダの市場から取得することです。ただし、ネットワークまたはクラウドにある既存の Linux ホストに Connector ソフトウェアをダウンロードしてインストールすることもできます。以下の手順は、インターネットにアクセスできるホストに固有の手順です。

link:concept-connectors.html["コネクタを配置するその他の方法について説明します"]。


NOTE: Google Cloud で Cloud Volumes ONTAP システムを作成する場合は、 Google Cloud でも実行されているコネクタが必要です。AWS 、 Azure 、オンプレミスで実行されているコネクタは使用できません。



== ホストの要件を確認

コネクタソフトウェアは、特定のオペレーティングシステム要件、 RAM 要件、ポート要件などを満たすホストで実行する必要があります。

専用のホストが必要です:: 他のアプリケーションと共有しているホストでは、このコネクタはサポートされていません。専用のホストである必要があります。
CPU:: 4 コアまたは 4 個の vCPU
RAM:: 14 GB
AWS EC2 インスタンスタイプ:: 上記の CPU と RAM の要件を満たすインスタンスタイプ。t3.xlarge をお勧めします。
Azure VM サイズ:: 上記の CPU と RAM の要件を満たすインスタンスタイプ。DS3 v2 を推奨します。
GCP マシンタイプ:: 上記の CPU と RAM の要件を満たすインスタンスタイプ。私たちは、n2規格4をお勧めします。
+
--
このコネクタは、OSがサポートされているVMインスタンス上のGoogle Cloudでサポートされます https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["シールドVM機能"^]

--
サポートされているオペレーティングシステム::
+
--
* CentOS 7.6、7.7、7.8、7.9
* Red Hat Enterprise Linux 7.6、7.7、7.8、7.9、8.6、 および8.7
+
Red Hat Enterprise Linux システムは、 Red Hat サブスクリプション管理に登録する必要があります。登録されていない場合、 Connector のインストール中に必要なサードパーティ製ソフトウェアを更新するためのリポジトリにアクセスできません。

+
Connector は、これらのオペレーティングシステムの英語版でサポートされています。



--
ハイパーバイザー:: 認定済みのベアメタルハイパーバイザーまたはホスト型ハイパーバイザー CentOS または Red Hat Enterprise Linux を実行しますhttps://access.redhat.com/certified-hypervisors["Red Hat ソリューション：「 Which hypervisors are certified to run Red Hat Enterprise Linux ？」"^]
/opt のディスクスペース:: 100GiB のスペースが使用可能である必要があります
/var のディスク領域:: 20GiB のスペースが必要です
Docker Engine の略:: Connectorをインストールする前に、ホストにDocker Engineバージョン19.3.1以降が必要です。 https://docs.docker.com/engine/install/["インストール手順を確認します"^]
アウトバウンドインターネットアクセス:: Connectorのインストーラは、インストールプロセス中に次のURLにアクセスする必要があります。
+
--
* \ https://support.netapp.com
* https://mysupport.netapp.com をご覧ください
* \ https://cloudmanager.cloud.netapp.com/tenancy
* \ https://stream.cloudmanager.cloud.netapp.com
* \ https://cloudmanagerinfraprod.azurecr.io
* \ https://production-artifacts.cloudmanager.cloud.netapp.com
* \ https://*.blob.core.windows.net


ホストは、インストール中にオペレーティングシステムパッケージの更新を試みる可能性があります。ホストは、これらの OS パッケージの別のミラーリングサイトにアクセスできます。

--




== コネクタを取り付ける

サポートされている Linux ホストがあることを確認したら、コネクタソフトウェアを取得してインストールできます。

.必要なもの
* コネクタをインストールするためのroot権限。
* コネクタからのインターネットアクセスにプロキシが必要な場合は、プロキシサーバに関する詳細。HTTPとHTTPSがサポートされています。
+
インストール後にプロキシサーバを設定することもできますが、その場合はコネクタを再起動する必要があります。

* プロキシサーバでHTTPSを使用する場合は、CA署名証明書。


.このタスクについて
* インストールを実行すると、ネットアップサポートからのリカバリ手順用に AWS コマンドラインツール（ awscli ）がインストールされます。
+
AWSCLI のインストールに失敗したというメッセージが表示された場合は、このメッセージを無視しても問題ありません。コネクタは、工具なしで正常に作動する。

* ネットアップサポートサイトで入手できるインストーラは、それよりも古いバージョンの場合があります。インストール後、新しいバージョンが利用可能になると、コネクタは自動的に更新されます。


.手順
. Docker が有効で実行されていることを確認します。
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----
. ホストに_http_proxy_or_https_proxy_system変数が設定されている場合は、削除します。
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
これらのシステム変数を削除しないと、インストールは失敗します。

. からConnectorソフトウェアをダウンロードします https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["ネットアップサポートサイト"^]をクリックし、 Linux ホストにコピーします。
+
ネットワークまたはクラウドで使用するコネクタインストーラをダウンロードする必要があります。

. スクリプトを実行する権限を割り当てます。
+
[source, cli]
----
chmod +x OnCommandCloudManager-V3.9.23
----
. インストールスクリプトを実行します。
+
[source, cli]
----
 ./OnCommandCloudManager-V3.9.23 --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
--proxyパラメータと--cacert.pemパラメータはオプションです。プロキシサーバがある場合は、次のようにパラメータを入力する必要があります。プロキシに関する情報の入力を求めるプロンプトは表示されません。

+
次に、両方のオプションパラメータを使用したコマンドの例を示します。

+
[source, cli]
----
 ./OnCommandCloudManager-V3.9.23 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxyは、次のいずれかの形式を使用してHTTPまたはHTTPSプロキシサーバを使用するようにコネクタを設定します。

+
** \ http://address:port
** \ http://username:password@address:port
** \ https://address:port
** \ https://username:password@address:port


+
--cacertsは、コネクタとプロキシサーバ間のHTTPSアクセスに使用するCA署名証明書を指定しています。このパラメータは、HTTPSプロキシサーバを指定する場合にのみ必要です。



.結果
これでコネクタがインストールされました。プロキシサーバを指定した場合は、インストールの終了時にConnectorサービス（occm）が2回再起動されます。



== コネクタをセットアップします

サインアップまたはログインして、アカウントで使用できるようにコネクタを設定します。

.手順
. Web ブラウザを開き、次の URL を入力します。
+
https://_ipaddress_[]

+
_ipaddress _ には、ホストの設定に応じて、 localhost 、プライベート IP アドレス、またはパブリック IP アドレスを指定できます。たとえば、パブリック IP アドレスのないパブリッククラウドにコネクタがある場合は、コネクタホストに接続されているホストからプライベート IP アドレスを入力する必要があります。

. サインアップまたはログインします。
. ConnectorをGoogle Cloudにインストールした場合は、BlueXPがプロジェクトでCloud Volumes ONTAP システムを作成および管理するために必要な権限を持つサービスアカウントを設定します。
+
.. https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["GCP で役割を作成します"^] で定義した権限を含むポリシーを作成します link:reference-permissions-gcp.html["GCPのコネクターポリシー"]。
.. https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["GCP サービスアカウントを作成し、カスタムロールを適用します を作成しました"^]。
.. https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["このサービスアカウントを Connector VM に関連付けます"^]。
.. Cloud Volumes ONTAP を他のプロジェクトに導入する場合は、 https://cloud.google.com/iam/docs/granting-changing-revoking-access#granting-console["BlueXPロールを持つサービスアカウントをそのプロジェクトに追加して、アクセスを許可します"^]。プロジェクトごとにこの手順を繰り返す必要があります。


. ログインしたら、BlueXPをセットアップします。
+
.. コネクタに関連付けるネットアップアカウントを指定します。
+
link:concept-netapp-accounts.html["ネットアップアカウントについて"]。

.. システムの名前を入力します。




.結果
これで、 Connector のインストールとセットアップが完了しました。新しい作業環境を作成するときに、BlueXPではこのコネクタが自動的に使用されます。

.完了後
BlueXPがパブリッククラウド環境内のリソースとプロセスを管理できるように権限を設定します。

* AWS link:task-adding-aws-accounts.html["AWSアカウントを設定して、BlueXPに追加します"]
* Azure link:task-adding-azure-accounts.html["Azureアカウントをセットアップして、BlueXPに追加します"]
* Google Cloud：上記のステップ3を参照してください

