---
sidebar: sidebar 
permalink: task-upgrade-connector.html 
keywords: upgrade, manual upgrade, connector upgrade, manual connector upgrade, upgrade connector manually, private mode upgrade, offline upgrade, upgrade private mode 
summary: 標準モードまたは制限モードでBlueXPを使用している場合、BlueXPは自動的にコネクタを最新リリースにアップグレードします。新しいバージョンは通常、新機能を導入し、安定性を向上させるために毎月リリースされます。必要に応じて、代わりにローカルリポジトリからイメージの更新をプルするようにコネクタを設定できます。プライベートモード展開の場合は、コネクタを手動で手動でアップグレードする必要があります。 
---
= コネクタのアップグレードの管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP  を標準モードまたは制限モードで使用すると、コネクタにソフトウェアの更新を取得するためのアウトバウンドインターネットアクセスがある限り、BlueXP  はコネクタを自動的に最新リリースにアップグレードします。コネクタのアップグレード時に手動で管理する必要がある場合は、標準モードまたは制限モードの自動アップグレードを無効にできます。


NOTE: BlueXP  をプライベートモードで実行する場合は、コネクタを常に自分でアップグレードする必要があります。



== 自動アップグレードを無効にする

コネクタの自動アップグレードを無効にするには、2つの手順を実行します。まず、コネクタが正常で最新であることを確認する必要があります。次に、設定ファイルを編集して、自動アップグレード機能をオフにします。


NOTE: コネクタのバージョンが3.9.48以上の場合にのみ、自動アップグレードを無効にできます。



=== コネクタの状態を確認する

コネクタが安定しており、コネクタVMで実行されているすべてのコンテナが正常に動作していることを確認する必要があります。自動アップグレードを無効にすると、Connector VMは新しいサービスまたはアップグレードパッケージのチェックを停止します。

次のいずれかのコマンドを使用して、コネクタを確認します。すべてのサービスのステータスが_running_になっている必要があります。そうでない場合は、自動アップグレードを無効にする前にNetAppサポートにお問い合わせください。

Docker::
+
--
[source, cli]
----
docker ps -a
----
--
ポドマン::
+
--
[source, cli]
----
podman ps -a
----
--




=== コネクタの自動アップグレードを無効にする

自動アップグレードを無効にするには、_com/opt/application/service-manager-2/config.json_fileで_isUpgradeDisabled_flagを設定しNetAppます。デフォルトでは、このフラグはfalseに設定され、コネクタは自動的にアップグレードされます。このフラグをtrueに設定すると、自動アップグレードを無効にできます。この手順を実行する前に、JSON構文を理解しておく必要があります。

自動アップグレードを再度有効にするには、次の手順を実行して_isUpgradeDisabled_flagをfalseに設定します。

.手順
. コネクタが最新で正常であることを確認します。
. _/opt/application/service-manager-2/config.json_ NetAppファイルのバックアップコピーを作成して、変更を元に戻せるようにします。
. _/opt/application/service-manager-2/config.json_file NetAppを編集し、_isUpgradeDisabled_flagの値をtrueに変更します。
+
[source]
----
  "isUpgradeDisabled": true,
----
. ファイルを保存します。
. 次のコマンドを実行して、Service Manager 2サービスを再起動します。
+
[source, cli]
----
systemctl restart netapp-service-manager.service
----
. 次のコマンドを実行して、コネクタのステータスが_active（running）_と表示されていることを確認します。_
+
[source, cli]
----
systemctl status netapp-service-manager.service
----




== コネクタのアップグレード

アップグレード中にWebベースのコンソールを使用できなくなるように、アップグレードプロセス中にコネクタを再起動する必要があります。

.手順
. からConnectorソフトウェアをダウンロードします https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp Support Site"^]。
+
インターネットにアクセスできないプライベートネットワーク用のオフラインインストーラを必ずダウンロードしてください。

. インストーラを Linux ホストにコピーします。
. スクリプトを実行する権限を割り当てます。
+
[source, cli]
----
chmod +x /path/BlueXP-Connector-offline-<version>
----
+
<version> は、ダウンロードしたコネクタのバージョンです。

. インストールスクリプトを実行します。
+
[source, cli]
----
sudo /path/BlueXP-Connector-offline-<version>
----
+
<version> は、ダウンロードしたコネクタのバージョンです。

. アップグレードが完了したら、 * Help > Support > Connector * を選択してコネクタのバージョンを確認できます。

