---
sidebar: sidebar 
permalink: task-create-connectors-gov.html 
keywords: government region, gov, govcloud, connector 
summary: 行政機関で運用している場合は、クラウドプロバイダのマーケットプレイスからConnectorを導入するか、手動でインストールする必要があります。Connectorは、Cloud ManagerのSaaS Webサイトからは政府機関のリージョンに導入できません。 
---
= 政府機関リージョンでコネクタを作成します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
政府機関で運用している場合は、クラウドプロバイダのマーケットプレイスからConnectorを導入するか、既存のLinuxホストにConnectorソフトウェアを手動でインストールする必要があります。Connectorは、Cloud ManagerのSaaS Webサイトからは政府機関のリージョンに導入できません。

次のいずれかのリンクを使用して、コネクタの作成手順を表示します。

* link:task-launching-aws-mktp.html#create-the-connector-in-an-aws-government-region["AWS Marketplace からコネクタを作成します"]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws-c2s.html["AWS C2S環境でコネクタとCloud Volumes ONTAP を作成します"^]
* link:task-launching-azure-mktp.html["Azure Marketplace からコネクタを作成します"]
* link:task-installing-linux.html["コネクタを独自のLinuxホストにインストールします"]
+
Linuxホストを手動でインストールする場合は、「オンライン」インストーラを使用して、インターネットにアクセスできるホストにコネクタをインストールする必要があります。Cloud Managerでは個別の「オフライン」インストーラを使用できますが、インターネットにアクセスできないオンプレミスサイトでのみサポートされます。政府機関ではサポートされていません。



コネクタを導入したら、Webブラウザを開いてコネクタインスタンスのIPアドレスに接続し、Cloud Managerにアクセスできます。 https://_ipaddress_[]

コネクタは政府機関に導入されているため、からはアクセスできません https://cloudmanager.netapp.com[]。
