---
sidebar: sidebar 
permalink: task-maintain-connectors.html 
keywords: connector operating system, connector maintenance, vm maintenance, os updates, operating system updates, stop connector, restart connector, notifications, connector health, connector disk space, connector cpu usage, connector ram usage, connector vm, connector ip address, connector uri 
summary: コネクタホストでのオペレーティングシステムの保守はお客様の責任で行ってください。たとえば、オペレーティングシステムの配布に関する会社の標準手順に従って、コネクタホストのオペレーティングシステムにセキュリティ更新プログラムを適用する必要があります。 
---
= コネクタVMとオペレーティングシステムの保守
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コネクタホスト上のオペレーティングシステムのメンテナンスは、お客様（お客様）の責任となります。例えば、お客様は、社内の標準的なオペレーティングシステム配布手順に従って、コネクタホスト上のオペレーティングシステムにセキュリティアップデートを適用する必要があります。


TIP: 既存のコネクタがある場合は、次の点に注意する必要があります。 link:reference-connector-operating-system-changes.html["サポートされるLinuxオペレーティングシステムに対する変更"]。



== オペレーティングシステムのパッチとコネクタ

コネクタ ホスト サービスを停止せずに OS セキュリティ パッチを適用します。



== VMまたはインスタンスタイプ

BlueXPからコネクタを作成すると、クラウドプロバイダーにデフォルト構成の VM インスタンスがデプロイされます。コネクタを作成した後は、CPU や RAM が少ない、より小さな VM インスタンスに切り替えないでください。

次の表に、CPU および RAM の要件を示します。

CPU:: 8 コアまたは 8 個の vCPU
RAM:: 32 GB


link:reference-connector-default-config.html["コネクタのデフォルト設定について説明します"]。



== コネクタを監視する

BlueXPは、コネクタVMのディスク容量、RAM、CPUに問題がある場合など、異常な状態になった際に通知します。これらの通知は、 BlueXPの通知センターで監視するか、メール通知を設定してください。ディスク容量、メモリ、CPU使用率が時折増加するのは正常ですが、頻繁に発生する場合は、解決のための措置を講じる必要があります。

BlueXPは、コネクタリソース（CPU、RAM、またはディスク容量）が30分連続して総容量の90%を超えると通知します。その後、リソース使用量がそのしきい値を下回ると、通知センターに「解決済み」（緑色）として表示されます。


NOTE: コネクタ VM の変更について質問がある場合は、 NetAppサポートにお問い合わせください。

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#notification-center["詳細はこちら。"^]

[cols="47,47"]
|===
| 通知 | 必要な行動 


| ディスク容量が多すぎる | link:https://kb.netapp.com/Cloud/BlueXP/Cloud_Manager/How_to_resolve_disk_space_issues_on_BlueXP_connector_VM["NetAppナレッジベースの記事を確認する"^]です。 


| CPU使用率が高すぎる | インストール場所に応じて、ハイパースケーラーまたはオンプレミスのコネクタVMのCPUサイズを増やします。または、追加のコネクタを作成し、複数のコネクタにワークロードを分散します。RAMの使用率は、環境、 ONTAPワークロード、 Cloud Volumes ONTAPシステムの数、および使用しているデータサービスによって異なります。 


| RAM使用量が高すぎる | コネクタVMのRAMを、ハイパースケーラーまたはオンプレミス（インストール場所によって異なります）で増設してください。または、追加のコネクタを作成し、複数のコネクタにワークロードを分散することもできます。RAMの使用率は、環境、 ONTAPワークロード、 Cloud Volumes ONTAPシステムの数、および使用しているデータサービスによって異なります。 
|===


== コネクタVMの停止と起動

必要に応じて、クラウド プロバイダーのコンソールまたは標準のオンプレミス手順を使用して、コネクタ VM を停止および起動します。

link:concept-connectors.html#connectors-must-be-operational-at-all-times["コネクタは常に動作している必要があることに注意してください"]。



== Linux VM に接続します

コネクタが実行される Linux VM に接続する必要がある場合は、クラウド プロバイダーの接続オプションを使用します。

AWS:: AWSでコネクタインスタンスを作成する際は、AWSアクセスキーとシークレットキーを入力してください。EC2このキーペアを使用して、 SSH でインスタンスに接続できます。Linuxインスタンスの場合はユーザー名「ubuntu」を使用してください。2023年5月以前に作成されたコネクタの場合は、ユーザー名「ec2-user」を使用してください。
+
--
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html["AWS Docs ： Linux インスタンスに接続します"^]

--
Azure:: Azure でコネクタ VM を作成するときは、ユーザー名を指定し、パスワードまたは SSH 公開キーで認証することを選択します。選択した認証方式を使用して VM に接続します。
+
--
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys#ssh-into-your-vm["Azure Docs ： SSH を使用して VM を接続します"^]

--
Google Cloud:: Google Cloud でコネクタを作成するときに認証方法を指定することはできません。ただし、 Google Cloud Console または Google Cloud CLI （ gcloud ）を使用して Linux VM インスタンスに接続することができます。
+
--
https://cloud.google.com/compute/docs/instances/connecting-to-instance["Google Cloud Docs ： Linux VM に接続します"^]

--




== コネクタの IP アドレスを変更します

必要に応じて、クラウド プロバイダーによって割り当てられたコネクタ インスタンスの内部 IP アドレスとパブリック IP アドレスを変更できます。

.手順
. クラウドプロバイダからの指示に従って、 Connector インスタンスのローカル IP アドレスまたはパブリック IP アドレス（またはその両方）を変更します。
. コネクタ インスタンスを再起動して、新しいパブリック IP アドレスをBlueXPに登録します。
. プライベート IP アドレスを変更した場合は、 Cloud Volumes ONTAP 構成ファイルのバックアップ先を更新して、コネクタ上の新しいプライベート IP アドレスにバックアップが送信されるようにします。
+
各Cloud Volumes ONTAPシステムのバックアップの場所を更新します。

+
.. Cloud Volumes ONTAP CLIで、権限レベルをadvancedに設定します。
+
[source, cli]
----
set -privilege advanced
----
.. 次のコマンドを実行して、現在のバックアップターゲットを表示します。
+
[source, cli]
----
system configuration backup settings show
----
.. 次のコマンドを実行して、バックアップターゲットのIPアドレスを更新します。
+
[source, cli]
----
system configuration backup settings modify -destination <target-location>
----






== コネクターのURIを編集します

コネクタの Uniform Resource Identifier (URI) を追加および削除できます。

.手順
. BlueXPヘッダーの* Connector *ドロップダウンを選択します。
. [コネクタの管理]*を選択します。
. コネクタ URI を表示するには、*コネクタ URI* バーを展開します。
. URIを追加および削除し、*適用*を選択します。

