---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: BlueXPにサインアップすると、WebブラウザからSaaSベースのユーザーインターフェイスを介してログインできます。 
---
= BlueXPにログインします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPにサインアップすると、WebブラウザからSaaSベースのユーザーインターフェイスを介してログインできます。

link:task-sign-up-saas.html["BlueXPにサインアップして組織を作成する方法について説明します"]。

政府機関またはアウトバウンドのインターネットアクセスがないサイトからBlueXPにアクセスしている場合は、コネクタでローカルに実行されているBlueXPユーザーインターフェイスにログインする必要があります。 link:task-managing-connectors.html#access-the-local-ui["ConnectorでローカルUIにアクセスする方法について説明します"]。

.ログインオプション
次のいずれかのオプションを使用して、BlueXPにログインできます。

* 既存のNetApp Support Site （NSS）のクレデンシャルを必要に応じて変更
* Eメールアドレスとパスワードを使用したネットアップクラウドへのログイン
* フェデレーテッド接続
+
シングルサインオンを使用して、社内ディレクトリ（フェデレーション ID ）からのクレデンシャルを使用してログインできます。 link:concept-federation.html["BlueXPでアイデンティティフェデレーションを使用する方法をご紹介します"]。



.手順
. Webブラウザを開き、にアクセスします https://console.bluexp.netapp.com["BlueXPコンソール"^]
. [ログイン*]ページで、ログインに関連付けられている電子メールアドレスを入力します。
. ログインに関連付けられている認証方法に応じて、クレデンシャルの入力を求められます。
+
** ネットアップクラウドクレデンシャル：パスワードを入力します
** フェデレーテッドユーザ：フェデレーテッドアイデンティティクレデンシャルを入力します
** NetApp Support Site アカウント：NetApp Support Site クレデンシャルを入力します




.結果
ログインして、BlueXPを使用してハイブリッドマルチクラウドインフラを管理できるようになりました。
