---
sidebar: sidebar 
permalink: task-manage-user-credentials.html 
keywords: credentials, ontap credentials, update ontap credentials, update ontap password, nss account, nss credentials, nss login, nss password 
summary: BlueXPで実行した操作によっては、ONTAP クレデンシャルとNetApp Support Site NSSクレデンシャルをBlueXPユーザログインに関連付けることができます。関連付けたクレデンシャルは、BlueXPで表示および管理できます。たとえば、これらのクレデンシャルのパスワードを変更した場合は、BlueXPでパスワードを更新する必要があります。 
---
= BlueXPログインに関連付けられているクレデンシャルを管理します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPで実行した操作によっては、ONTAP クレデンシャルとNetApp Support Site （NSS）クレデンシャルがBlueXPユーザログインに関連付けられている場合があります。関連付けたクレデンシャルは、BlueXPで表示および管理できます。たとえば、これらのクレデンシャルのパスワードを変更した場合は、BlueXPでパスワードを更新する必要があります。



== ONTAP クレデンシャル

BlueXP で ONTAP クラスターを検出するには、ユーザーは ONTAP 管理者の認証情報が必要です。ただし、ONTAPシステムマネージャへのアクセスは、コネクタを使用しているかどうかによって異なります。

.コネクタなし
クラスタのONTAP System Managerにアクセスするために、ONTAPクレデンシャルを入力するように求められます。ユーザは、これらのクレデンシャルをBlueXP  に保存することを選択できます。つまり、クレデンシャルを毎回入力するように求められることはありません。ユーザクレデンシャルは、それぞれのユーザにのみ表示され、[User Credentials]ページから管理できます。

.コネクタ付き
デフォルトでは、ONTAPシステムマネージャにアクセスするためのONTAPクレデンシャルの入力は求められません。ただし、BlueXP  管理者（Organization adminロールを持つ）は、ユーザにONTAPクレデンシャルの入力を求めるようにBlueXP  を設定できます。この設定を[Enabled]にすると、ユーザは毎回ONTAPクレデンシャルを入力する必要があります。

link:task-ontap-access-connector.html["詳細はこちら。"^]



== NSSクレデンシャル

BlueXPログインに関連付けられたNSSクレデンシャルにより、サポート登録、ケース管理、Digital Advisorへのアクセスが可能になります。

* [サポート]>[リソース]*にアクセスしてサポートに登録すると、NSSクレデンシャルをBlueXPログインに関連付けるように求められます。
+
これにより、組織またはアカウントがサポートに登録され、サポート資格が有効になります。サポートに登録してサポート利用資格をアクティブ化するために、NetAppサポートサイトのアカウントをBlueXP  ログインに関連付ける必要があるのは、BlueXP  組織またはアカウント内の1人のユーザだけです。これが完了すると、*リソース*ページにアカウントがサポートに登録されたことが表示されます。

+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-support-registration.html["サポートに登録する方法について説明します"^]

* [サポート]>[ケース管理]*にアクセスすると、NSSクレデンシャルを入力するように求められます（まだ入力していない場合）。このページでは、NSSアカウントと会社に関連付けられたサポートケースを作成および管理できます。
* BlueXPでDigital Advisorにアクセスすると、NSS資格情報を入力してDigital Advisorにログインするように求められます。


BlueXPログインに関連付けられているNSSアカウントについては、次の点に注意してください。

* アカウントはユーザレベルで管理されるため、他のユーザがログインしても表示できません。
* Digital Advisorとサポートケース管理に関連付けることができるNSSアカウントは、ユーザごとに1つだけです。
* NetAppサポートサイトのアカウントをCloud Volumes ONTAP作業環境に関連付ける場合は、BlueXP  組織またはメンバーであるアカウントに追加されたNSSアカウントからのみ選択できます。
+
NSSアカウントレベルのクレデンシャルは、BlueXPログインに関連付けられたNSSアカウントとは異なります。NSS アカウント レベルの認証情報を使用すると、BYOL を使用して Cloud Volumes ONTAP をデプロイし、PAYGO システムを登録し、ソフトウェアをアップグレードできます。

+
link:task-adding-nss-accounts.html["BlueXP  組織またはアカウントでのNSSクレデンシャルの使用に関する詳細"]です。





== ユーザクレデンシャルを管理します

ユーザ名とパスワードを更新するか、クレデンシャルを削除して、ユーザクレデンシャルを管理します。

.手順
. BlueXPコンソールの右上で、[設定]アイコンを選択し、*[クレデンシャル]*を選択します。
. [ユーザクレデンシャル]*を選択します。
. まだユーザクレデンシャルがない場合は、*[NSSクレデンシャルの追加]*を選択してNetApp Support Site アカウントを追加できます。
. [アクション] メニューから次のオプションを選択して、既存の資格情報を管理します。
+
** *資格情報の更新*：アカウントのユーザー名とパスワードを更新します。
** *クレデンシャルを削除*：BlueXPユーザアカウントに関連付けられているアカウントを削除します。




.結果
BlueXP によって資格情報が更新され、ONTAP クラスタ、デジタル アドバイザー、またはケース管理ページにアクセスすると変更が表示されます。
