---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: BlueXPへのログイン方法は、アカウントで使用しているBlueXP導入モードによって異なります。 
---
= BlueXPにログインします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPへのログイン方法は、アカウントで使用しているBlueXP導入モードによって異なります。

link:concept-modes.html["BlueXPの導入モードについて説明します"]。

[role="tabbed-block"]
====
.標準モード
--
BlueXPに登録すると、Webベースのコンソールからログインしてデータとストレージインフラの管理を開始できます。

.このタスクについて
BlueXPのWebベースのコンソールには、次のいずれかの方法でログインできます。

* 既存のNetApp Support Site （NSS）のクレデンシャルを必要に応じて変更
* Eメールアドレスとパスワードを使用したネットアップクラウドへのログイン
* フェデレーテッド接続
+
シングルサインオンを使用して、社内ディレクトリ（フェデレーション ID ）からのクレデンシャルを使用してログインできます。 link:concept-federation.html["BlueXPでアイデンティティフェデレーションを使用する方法をご紹介します"]。



.手順
. Webブラウザを開き、にアクセスします https://console.bluexp.netapp.com["BlueXPコンソール"^]
. [ログイン*]ページで、ログインに関連付けられている電子メールアドレスを入力します。
. ログインに関連付けられている認証方法に応じて、クレデンシャルの入力を求められます。
+
** ネットアップクラウドクレデンシャル：パスワードを入力します
** フェデレーテッドユーザ：フェデレーテッドアイデンティティクレデンシャルを入力します
** NetApp Support Site アカウント：NetApp Support Site クレデンシャルを入力します




.結果
ログインして、BlueXPを使用してハイブリッドマルチクラウドインフラを管理できるようになりました。

--
.制限モード
--
制限モードでBlueXPを使用する場合は、コネクタでローカルに実行されるユーザインターフェイスからBlueXPコンソールにログインする必要があります。

.このタスクについて
BlueXPでは、アカウントが制限モードで設定されている場合、次のいずれかの方法でログインできます。

* Eメールアドレスとパスワードを使用したネットアップクラウドへのログイン
* フェデレーテッド接続
+
シングルサインオンを使用して、社内ディレクトリ（フェデレーション ID ）からのクレデンシャルを使用してログインできます。 link:concept-federation.html["BlueXPでアイデンティティフェデレーションを使用する方法をご紹介します"]。



.手順
. Web ブラウザを開き、次の URL を入力します。
+
https://_ipaddress_[]

+
_ipaddress_には、コネクタをインストールしたホストの構成に応じて、localhost、プライベートIPアドレス、またはパブリックIPアドレスを指定できます。たとえば、コネクタホストに接続されているホストからプライベートIPアドレスを入力する必要がある場合があります。

. ログインするためのユーザ名とパスワードを入力します。


.結果
ログインして、BlueXPを使用してハイブリッドマルチクラウドインフラを管理できるようになりました。

--
.プライベートモード
--
BlueXPをプライベートモードで使用する場合は、コネクタでローカルに実行されるユーザインターフェイスからBlueXPコンソールにログインする必要があります。

.このタスクについて
プライベートモードでは、ローカルユーザの管理とアクセスがサポートされます。BlueXPのクラウドサービスでは認証が行われません。

.手順
. Web ブラウザを開き、次の URL を入力します。
+
https://_ipaddress_[]

+
_ipaddress_には、コネクタをインストールしたホストの構成に応じて、localhost、プライベートIPアドレス、またはパブリックIPアドレスを指定できます。たとえば、コネクタホストに接続されているホストからプライベートIPアドレスを入力する必要がある場合があります。

. ログインするためのユーザ名とパスワードを入力します。


.結果
ログインして、BlueXPを使用してハイブリッドマルチクラウドインフラを管理できるようになりました。

--
====