= コネクタイメージを取得するための新しいセキュアエンドポイント
:allow-uri-read: 




=== コネクタイメージを取得するための新しいセキュアエンドポイント

コネクタをインストールするとき、または自動アップグレードが発生すると、コネクタはリポジトリに接続してインストールまたはアップグレード用のイメージをダウンロードします。デフォルトでは、コネクタは常に次のエンドポイントに接続しています。

* \https://*.blob.core.windows.net
* \https://cloudmanagerinfraprod.azurecr.io


最初のエンドポイントには、最終的な場所を指定できないため、ワイルドカードが含まれています。リポジトリのロードバランシングはサービスプロバイダーによって管理されます。つまり、ダウンロードはさまざまなエンドポイントから実行できます。

セキュリティを強化するために、コネクタは専用エンドポイントからインストールイメージとアップグレードイメージをダウンロードできるようになりました。

* \https://bluexpinfraprod.eastus2.data.azurecr.io
* \https://bluexpinfraprod.azurecr.io


これらの新しいエンドポイントの使用を開始するには、ファイアウォールルールから既存のエンドポイントを削除し、新しいエンドポイントを許可することを推奨します。

これらの新しいエンドポイントは、コネクタの3.9.47リリース以降でサポートされています。以前のリリースのコネクタとの下位互換性はありません。

次の点に注意してください。

* 既存のエンドポイントは引き続きサポートされます。新しいエンドポイントを使用しない場合は、変更は必要ありません。
* コネクタは最初に既存のエンドポイントに接続します。これらのエンドポイントにアクセスできない場合、コネクタは自動的に新しいエンドポイントに接続します。
* 新しいエンドポイントは、次のシナリオではサポートされません。
+
** コネクタが政府機関地域に設置されている場合。
** BlueXP  のバックアップとリカバリまたはBlueXP  ランサムウェア対策でコネクタを使用する場合。


+
どちらの場合も、既存のエンドポイントを引き続き使用できます。


