= コネクタ3.9.52
:allow-uri-read: 




=== コネクタ3.9.52

このリリースのBlueXP  Connectorには、セキュリティのマイナーな改善とバグの修正、およびいくつかの追加アップデートが含まれています。

現時点では、3.9.52リリースは標準モードと制限モードで使用できます。



==== Docker 27およびDocker 28のサポート

コネクタでDocker 27とDocker 28がサポートされるようになりました。



==== Cloud Volumes ONTAP

Cloud Volumes ONTAPノードは、コネクタがコンプライアンス違反または14日間以上ダウンしている場合でもシャットダウンしなくなりました。CloudVolumes ONTAPは、コネクタへのアクセスを失った場合でも、イベント管理メッセージを送信します。この変更は、コネクタが長期間ダウンした場合でも、Cloud Volumes ONTAPが動作を継続できるようにするためのものです。コネクタのコンプライアンス要件は変更されません。



=== Keystoneの管理はBlueXP  で可能

BlueXP  のNetApp Keystoneベータ版では、Keystone管理機能へのアクセスが追加されました。NetApp Keystoneベータ版のサインアップページには、BlueXP  の左側のナビゲーションバーからアクセスできます。



=== BlueXP  IDおよびアクセス管理（IAM）



==== 新しいストレージ管理の役割

ストレージ管理者、システム正常性スペシャリスト、ストレージ閲覧者の役割が利用可能であり、ユーザーに割り当てることができます。

これらのロールを使用すると、組織内のどのユーザーがストレージ リソースを検出および管理できるかを管理できるほか、ストレージの正常性情報を表示したり、ソフトウェアの更新を実行したりすることもできます。

これらのロールは、次のストレージ リソースへのアクセスを制御するためにサポートされています。

* Eシリーズシステム
* StorageGRID システム
* オンプレミスの ONTAP システム


これらのロールを使用して、次の BlueXP サービスへのアクセスを制御することもできます。

* ソフトウェアの更新
* デジタルアドバイザ
* 運用の耐障害性
* 経済効率
* 持続可能性


次のロールが追加されました:

* *ストレージ管理者*
+
組織内のストレージリソースの健全性、ガバナンス、検出を管理します。このロールは、ストレージリソースのソフトウェア更新も実行できます。

* *システムヘルススペシャリスト*
+
組織内のストレージリソースの健全性とガバナンスを管理します。このロールは、ストレージリソースのソフトウェアアップデートも実行できます。作業環境を変更または削除することはできません。

* *ストレージビューア*
+
ストレージの健全性情報とガバナンス データを表示します。

+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["アクセスロールについて説明します。"^]


