= コネクタ3.9.54
:allow-uri-read: 




=== コネクタ3.9.54

BlueXPコネクタのこのリリースには、セキュリティの改善、バグ修正、および次の新機能が含まれています。

* Cloud Volumes ONTAPサービスのサポート専用のコネクタの透過プロキシのサポート。 link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["透過プロキシの構成について詳しく学びます。"]
* コネクタが Google Cloud 環境にデプロイされているときに、ネットワーク タグを使用してコネクタ トラフィックをルーティングする機能。
* CPU および RAM の使用状況を含む、コネクタのヘルス監視に関する追加の製品内通知。


現時点では、3.9.54リリースは標準モードと制限モードで使用できます。



=== BlueXP  IDおよびアクセス管理（IAM）

BlueXPの ID およびアクセス管理では、次の機能が提供されるようになりました。

* プライベート モードでの IAM のサポートにより、 BlueXPサービスおよびアプリケーションに対するユーザー アクセスと権限を管理できます。
* より簡単なナビゲーション、フェデレーション接続を構成するためのより明確なオプション、既存のフェデレーションの可視性の向上など、ID フェデレーションの管理が合理化されます。
* BlueXP backup and recovery、 BlueXP disaster recovery、およびフェデレーション管理のアクセス ロール。




==== プライベートモードでのIAMのサポート

BlueXPはプライベートモードでIAMをサポートするようになりました。これにより、 BlueXPのサービスとアプリケーションに対するユーザーアクセスと権限を管理できるようになります。この機能強化により、プライベートモードのお客様はロールベースアクセス制御（RBAC）を活用して、セキュリティとコンプライアンスを強化できます。

link:https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#iam["BlueXPの IAM について詳しく学びます。"]



==== アイデンティティ連携の効率的な管理

BlueXPは、ID連携を管理するためのより直感的なインターフェースを提供します。これにより、ナビゲーションが簡素化され、連携接続の設定オプションが明確になり、既存の連携の可視性が向上します。

ID連携によるシングルサインオン（SSO）を有効にすると、ユーザーは企業の認証情報でBlueXPにログインできるようになります。これにより、セキュリティが向上し、パスワードの使用が削減され、オンボーディングが簡素化されます。

新しい管理機能にアクセスするには、既存のフェデレーション接続を新しいインターフェースにインポートするよう求められます。これにより、フェデレーション接続を再作成することなく、最新の機能強化を活用できます。 link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-federation-import.html["既存のフェデレーション接続をBlueXPにインポートする方法の詳細をご覧ください。"]

改善されたフェデレーション管理により、次のことが可能になります。

* フェデレーション接続に複数の検証済みドメインを追加すると、同じ ID プロバイダー (IdP) で複数のドメインを使用できるようになります。
* 必要に応じてフェデレーション接続を無効化または削除し、ユーザー アクセスとセキュリティを制御できます。
* IAM ロールを使用してフェデレーション管理へのアクセスを制御します。


link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-federation.html["BlueXPの ID フェデレーションの詳細をご覧ください。"]



==== BlueXP backup and recovery、 BlueXP disaster recovery、フェデレーション管理の新しいアクセス ロール

BlueXPでは、次の機能とデータ サービスに対する IAM ロールの使用がサポートされるようになりました。

* BlueXPのバックアップとリカバリ
* BlueXPディザスタリカバリ
* フェデレーション


link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["アクセス ロールの使用について詳しく学習します。"]
