= コネクタ3.9.53
:allow-uri-read: 




=== コネクタ3.9.53

BlueXP コネクタのこのリリースには、セキュリティの改善とバグ修正が含まれています。

3.9.53リリースは、標準モードと制限モードで使用できます。



=== ディスク容量使用状況アラート

通知センターに、コネクタのディスク領域の使用状況に関するアラートが含まれるようになりました。 link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#monitor-disk-space["詳細はこちら。"^]



=== 監査の改善

タイムラインにユーザーのログインとログアウトのイベントが表示されるようになりました。ログインアクティビティがいつ発生したかを確認できるため、監査やセキュリティ監視に役立ちます。組織管理者ロールを持つAPIユーザーは、ログインしたユーザーのメールアドレスをタイムラインに表示できます。  `includeUserData=true``パラメータは次のようになります。  `/audit/<account_id>?includeUserData=true` 。



=== BlueXPでKeystoneサブスクリプション管理が利用可能

BlueXP から NetApp Keystone サブスクリプションを管理できます。

link:https://docs.netapp.com/us-en/keystone-staas/index.html["BlueXP での Keystone サブスクリプション管理について学習します。"^]



=== BlueXP  IDおよびアクセス管理（IAM）



==== 多要素認証（MFA）

フェデレーションされていないユーザーは、 BlueXPアカウントでMFAを有効にしてセキュリティを強化できます。管理者は、必要に応じてユーザーのMFAをリセットまたは無効化するなど、MFA設定を管理できます。これは標準モードでのみサポートされます。

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-user-settings.html#task-user-mfa["自分自身に多要素認証を設定する方法について説明します。"^] link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-manage-members-permissions.html#manage-mfa["ユーザーに対する多要素認証の管理について学習します。"^]



=== ワークロード

BlueXP の認証情報ページから Amazon FSx for NetApp ONTAP の認証情報を表示および削除できるようになりました。
