= ターゲットネットワークへの接続
:allow-uri-read: 


コネクタがパブリッククラウド環境内のリソースやプロセスを管理できるように、ネットワークを設定します。コネクタの仮想ネットワークとサブネットを使用する以外に、次の要件が満たされていることを確認する必要があります。



=== ターゲットネットワークへの接続

Connectorでは、作成する作業環境の種類と有効にするサービスへのネットワーク接続が必要です。

たとえば、会社のネットワークにコネクタをインストールする場合は、Cloud Volumes ONTAP を起動する仮想ネットワークへのVPN接続を設定する必要があります。



=== アウトバウンドインターネットアクセス

Connector では、パブリッククラウド環境内のリソースとプロセスを管理するためにアウトバウンドインターネットアクセスが必要です。

[cols="2*"]
|===
| エンドポイント | 目的 


| \ https://support.netapp.com | ライセンス情報を取得し、ネットアップサポートに AutoSupport メッセージを送信するため。 


 a| 
\ https://*.api.bluexp.netapp.com

\ https://api.bluexp.netapp.com

\ https://*.cloudmanager.cloud.netapp.com

\ https://cloudmanager.cloud.netapp.com
 a| 
BlueXPでSaaSの機能とサービスを提供するため。


NOTE: コネクターは現在、「cloudmanager.cloud.netapp.com"」に接続していますが、今後のリリースでapi.bluexp.netapp.com"への連絡を開始します。



| ¥ https://cloudmanagerinfraprod.azurecr.io ¥ https://*.blob.core.windows.net | をクリックして、 Connector と Docker コンポーネントをアップグレードします。 


| \https://<region> .amazonaws.com | AWSでリソースを管理できます。 


| https://management.azure.com https://login.microsoftonline.com | Azureパブリックリージョン内のリソースを管理します。 


| ¥https://management.usgovcloudapi.net¥https://login.microsoftonline.us | Azure Governmentリージョンのリソースを管理 


| \shttps/management.azure.microsoft.scloud\https://login.microsoftonline.microsoft.scloudに移動します | をクリックして、Azure IL6リージョン内のリソースを管理します。 


| ¥https://management.chinacloudapi.cn¥https://login.chinacloudapi.cn | をクリックしてAzure中国地域のリソースを管理してください。 


| ¥https://www.googleapis.com/compute/v1/¥https://cloudresourcemanager.googleapis.com/v1/projects¥https://www.googleapis.com/compute/beta¥https://storage.googleapis.com/storage/v1¥https://iam.googleapis.com/v1¥https://cloudkms.googleapis.com/v1¥https://www.googleapis.com/storage/v1 https://www.googleapis.com/deploymentmanager/v2/projects | Google Cloudでリソースを管理します。 
|===


=== プロキシサーバ

すべての送信インターネットトラフィックにHTTPプロキシを導入する必要がある場合は、HTTPプロキシに関する次の情報を取得します。

* IP アドレス
* クレデンシャル
* HTTPS証明書




=== セキュリティグループ

コネクタへの着信トラフィックは、コネクタを起動した場合や、コネクタがAutoSupport メッセージのプロキシとして使用されている場合を除き、受信トラフィックはありません。へのアクセスは、 HTTP および HTTPS を使用して提供されます https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html#the-local-user-interface["ローカル UI"]は、まれな状況で使用します。SSH が必要になるのは、トラブルシューティングのためにホストに接続する必要がある場合のみです。



=== IPアドレスの制限

172の範囲のIPアドレスと競合する可能性があります。 https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-limitations.html["この制限事項の詳細については、こちらをご覧ください"]。
